class AccessoryData {
  final String imagePath;
  final String accessoryName;
  final int coin;

  AccessoryData(this.imagePath, this.accessoryName, this.coin);
}

class AccessoryCategory {
  final String accessoryCategoryImagePath;
  final String accessoryCategoryName;

  AccessoryCategory(
      this.accessoryCategoryImagePath, this.accessoryCategoryName);
}

Map<AccessoryCategory, List<AccessoryData>> list = {
  AccessoryCategory('assets/accessories/alphabet.png', 'Alphabet'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/animal.png', 'Animal'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/camera.png', 'camera'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/clothes.png', 'Clothes'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/electronic.png', 'Electronic'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/emotion.png', 'Emotions'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/fruit.png', 'Fruits'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/furniture.png', 'Furniture'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/grains.png', 'Grains'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/mic.png', 'Mic'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/number.png', 'number'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/stickers.png', 'stickers'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/shape.png', 'Shape'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/stationary.png', 'Stationary'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/text.png', 'Text'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
  AccessoryCategory('assets/accessories/tools.png', 'Tools'): [
    AccessoryData('assets/accessories/camera.png', 'hat2', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses1', 100),
    AccessoryData('assets/accessories/camera.png', 'glasses2', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo1', 100),
    AccessoryData('assets/accessories/camera.png', 'tattoo2', 100),
    AccessoryData('assets/accessories/camera.png', 'earring1', 100),
    AccessoryData('assets/accessories/camera.png', 'earring2', 100),
    AccessoryData('assets/accessories/camera.png', 'hat1', 100),
    AccessoryData('assets/accessories/camera.png', 'beard1', 100),
  ],
};
