cp id.ogg ~/Downloads/audio
cp A.ogg ~/Downloads/audio
cp B.ogg ~/Downloads/audio
cp C.ogg ~/Downloads/audio
cp D.ogg ~/Downloads/audio
cp E.ogg ~/Downloads/audio
cp F.ogg ~/Downloads/audio
cp G.ogg ~/Downloads/audio
cp H.ogg ~/Downloads/audio
cp I.ogg ~/Downloads/audio
cp J.ogg ~/Downloads/audio
cp K.ogg ~/Downloads/audio
cp L.ogg ~/Downloads/audio
cp M.ogg ~/Downloads/audio
cp N.ogg ~/Downloads/audio
cp O.ogg ~/Downloads/audio
cp P.ogg ~/Downloads/audio
cp R.ogg ~/Downloads/audio
cp S.ogg ~/Downloads/audio
cp T.ogg ~/Downloads/audio
cp U.ogg ~/Downloads/audio
cp V.ogg ~/Downloads/audio
cp W.ogg ~/Downloads/audio
cp Y.ogg ~/Downloads/audio
cp Z.ogg ~/Downloads/audio
cp a.ogg ~/Downloads/audio
cp b.ogg ~/Downloads/audio
cp c.ogg ~/Downloads/audio
cp d.ogg ~/Downloads/audio
cp e.ogg ~/Downloads/audio
cp f.ogg ~/Downloads/audio
cp g.ogg ~/Downloads/audio
cp h.ogg ~/Downloads/audio
cp i.ogg ~/Downloads/audio
cp j.ogg ~/Downloads/audio
cp k.ogg ~/Downloads/audio
cp l.ogg ~/Downloads/audio
cp m.ogg ~/Downloads/audio
cp n.ogg ~/Downloads/audio
cp o.ogg ~/Downloads/audio
cp p.ogg ~/Downloads/audio
cp r.ogg ~/Downloads/audio
cp s.ogg ~/Downloads/audio
cp t.ogg ~/Downloads/audio
cp u.ogg ~/Downloads/audio
cp v.ogg ~/Downloads/audio
cp w.ogg ~/Downloads/audio
cp y.ogg ~/Downloads/audio
cp z.ogg ~/Downloads/audio
cp limau.ogg ~/Downloads/audio
cp ndala.ogg ~/Downloads/audio
cp tawi.ogg ~/Downloads/audio
cp wafu.ogg ~/Downloads/audio
cp ukwaju.ogg ~/Downloads/audio
cp kabichi.ogg ~/Downloads/audio
cp behewa.ogg ~/Downloads/audio
cp upawa.ogg ~/Downloads/audio
cp visiwa.ogg ~/Downloads/audio
cp papa.ogg ~/Downloads/audio
cp magamba.ogg ~/Downloads/audio
cp ini.ogg ~/Downloads/audio
cp mimina.ogg ~/Downloads/audio
cp viatu.ogg ~/Downloads/audio
cp chapa.ogg ~/Downloads/audio
cp figili.ogg ~/Downloads/audio
cp shoka.ogg ~/Downloads/audio
cp leso.ogg ~/Downloads/audio
cp paja.ogg ~/Downloads/audio
cp jambo.ogg ~/Downloads/audio
cp nyama.ogg ~/Downloads/audio
cp ndoano.ogg ~/Downloads/audio
cp nta.ogg ~/Downloads/audio
cp goti.ogg ~/Downloads/audio
cp sayansi.ogg ~/Downloads/audio
cp hoteli.ogg ~/Downloads/audio
cp mnara.ogg ~/Downloads/audio
cp elfu.ogg ~/Downloads/audio
cp farasi.ogg ~/Downloads/audio
cp bana.ogg ~/Downloads/audio
cp mbuni.ogg ~/Downloads/audio
cp kope.ogg ~/Downloads/audio
cp embe.ogg ~/Downloads/audio
cp misuli.ogg ~/Downloads/audio
cp ajali.ogg ~/Downloads/audio
cp nanga.ogg ~/Downloads/audio
cp dumu.ogg ~/Downloads/audio
cp rubani.ogg ~/Downloads/audio
cp chuchunge.ogg ~/Downloads/audio
cp nguo.ogg ~/Downloads/audio
cp fidia.ogg ~/Downloads/audio
cp tausi.ogg ~/Downloads/audio
cp jagi.ogg ~/Downloads/audio
cp kipenyo.ogg ~/Downloads/audio
cp mkeka.ogg ~/Downloads/audio
cp uzito.ogg ~/Downloads/audio
cp ujana.ogg ~/Downloads/audio
cp oktoba.ogg ~/Downloads/audio
cp nyangumi.ogg ~/Downloads/audio
cp zahanati.ogg ~/Downloads/audio
cp sarafu.ogg ~/Downloads/audio
cp oti.ogg ~/Downloads/audio
cp piramidi.ogg ~/Downloads/audio
cp bangili.ogg ~/Downloads/audio
cp mchele.ogg ~/Downloads/audio
cp haragwe.ogg ~/Downloads/audio
cp bafu.ogg ~/Downloads/audio
cp wamechoka.ogg ~/Downloads/audio
cp lazima.ogg ~/Downloads/audio
cp hatua.ogg ~/Downloads/audio
cp injili.ogg ~/Downloads/audio
cp mche.ogg ~/Downloads/audio
cp mkanda.ogg ~/Downloads/audio
cp nyuki.ogg ~/Downloads/audio
cp kabwela.ogg ~/Downloads/audio
cp ukaguzi.ogg ~/Downloads/audio
cp buibui.ogg ~/Downloads/audio
cp ushanga.ogg ~/Downloads/audio
cp mlima.ogg ~/Downloads/audio
cp masika.ogg ~/Downloads/audio
cp jicho.ogg ~/Downloads/audio
cp rekodi.ogg ~/Downloads/audio
cp kiwiko.ogg ~/Downloads/audio
cp dakika.ogg ~/Downloads/audio
cp zana.ogg ~/Downloads/audio
cp ongeza.ogg ~/Downloads/audio
cp sukari.ogg ~/Downloads/audio
cp nguruwe.ogg ~/Downloads/audio
cp laana.ogg ~/Downloads/audio
cp hakimu.ogg ~/Downloads/audio
cp kaanga.ogg ~/Downloads/audio
cp kilio.ogg ~/Downloads/audio
cp kona.ogg ~/Downloads/audio
cp mwezi.ogg ~/Downloads/audio
cp shamba.ogg ~/Downloads/audio
cp skrubu.ogg ~/Downloads/audio
cp nje.ogg ~/Downloads/audio
cp fasiri.ogg ~/Downloads/audio
cp robo.ogg ~/Downloads/audio
cp rai.ogg ~/Downloads/audio
cp cheki.ogg ~/Downloads/audio
cp hata.ogg ~/Downloads/audio
cp kikokotoa.ogg ~/Downloads/audio
cp chuma.ogg ~/Downloads/audio
cp dereva.ogg ~/Downloads/audio
cp benki.ogg ~/Downloads/audio
cp kivukisha.ogg ~/Downloads/audio
cp bomba.ogg ~/Downloads/audio
cp chombo.ogg ~/Downloads/audio
cp mchwa.ogg ~/Downloads/audio
cp tatu.ogg ~/Downloads/audio
cp geji.ogg ~/Downloads/audio
cp chanzo.ogg ~/Downloads/audio
cp misumari.ogg ~/Downloads/audio
cp jana.ogg ~/Downloads/audio
cp kupika.ogg ~/Downloads/audio
cp hamu.ogg ~/Downloads/audio
cp isimu.ogg ~/Downloads/audio
cp akaunti.ogg ~/Downloads/audio
cp bamia.ogg ~/Downloads/audio
cp taratibu.ogg ~/Downloads/audio
cp bahasha.ogg ~/Downloads/audio
cp kekeo.ogg ~/Downloads/audio
cp wachezaji.ogg ~/Downloads/audio
cp vikwazo.ogg ~/Downloads/audio
cp ujeuri.ogg ~/Downloads/audio
cp magoti.ogg ~/Downloads/audio
cp chonga.ogg ~/Downloads/audio
cp redio.ogg ~/Downloads/audio
cp fizikia.ogg ~/Downloads/audio
cp vitabu.ogg ~/Downloads/audio
cp kinubi.ogg ~/Downloads/audio
cp kichwa.ogg ~/Downloads/audio
cp bendera.ogg ~/Downloads/audio
cp darana.ogg ~/Downloads/audio
cp jaja.ogg ~/Downloads/audio
cp nguchiro.ogg ~/Downloads/audio
cp theluji.ogg ~/Downloads/audio
cp jembe.ogg ~/Downloads/audio
cp nywele.ogg ~/Downloads/audio
cp mapazia.ogg ~/Downloads/audio
cp ndimu.ogg ~/Downloads/audio
cp mwari.ogg ~/Downloads/audio
cp taaluma.ogg ~/Downloads/audio
cp ufa.ogg ~/Downloads/audio
cp wakili.ogg ~/Downloads/audio
cp vikombe.ogg ~/Downloads/audio
cp bolt.ogg ~/Downloads/audio
cp baridi.ogg ~/Downloads/audio
cp handaki.ogg ~/Downloads/audio
cp butu.ogg ~/Downloads/audio
cp kichapishi.ogg ~/Downloads/audio
cp muuguzi.ogg ~/Downloads/audio
cp hereni.ogg ~/Downloads/audio
cp bao.ogg ~/Downloads/audio
cp televisheni.ogg ~/Downloads/audio
cp duara.ogg ~/Downloads/audio
cp kali.ogg ~/Downloads/audio
cp hasara.ogg ~/Downloads/audio
cp uchoraji.ogg ~/Downloads/audio
cp mawingu.ogg ~/Downloads/audio
cp lori.ogg ~/Downloads/audio
cp kitambazo.ogg ~/Downloads/audio
cp sabini.ogg ~/Downloads/audio
cp taya.ogg ~/Downloads/audio
cp ngoma.ogg ~/Downloads/audio
cp samaki.ogg ~/Downloads/audio
cp muhindi.ogg ~/Downloads/audio
cp chache.ogg ~/Downloads/audio
cp jamii.ogg ~/Downloads/audio
cp jaji.ogg ~/Downloads/audio
cp kindi.ogg ~/Downloads/audio
cp tulivu.ogg ~/Downloads/audio
cp dira.ogg ~/Downloads/audio
cp mstatili.ogg ~/Downloads/audio
cp kiwi.ogg ~/Downloads/audio
cp roboti.ogg ~/Downloads/audio
cp ndevu.ogg ~/Downloads/audio
cp mhudumu.ogg ~/Downloads/audio
cp madarasa.ogg ~/Downloads/audio
cp kivuli.ogg ~/Downloads/audio
cp ngamia.ogg ~/Downloads/audio
cp harimuni.ogg ~/Downloads/audio
cp ndizi.ogg ~/Downloads/audio
cp wanasheria.ogg ~/Downloads/audio
cp kalenda.ogg ~/Downloads/audio
cp paa.ogg ~/Downloads/audio
cp hadhi.ogg ~/Downloads/audio
cp jalada.ogg ~/Downloads/audio
cp tumbo.ogg ~/Downloads/audio
cp chanjo.ogg ~/Downloads/audio
cp msumeno.ogg ~/Downloads/audio
cp kikombe.ogg ~/Downloads/audio
cp achari.ogg ~/Downloads/audio
cp gavana.ogg ~/Downloads/audio
cp chupi.ogg ~/Downloads/audio
cp zabibu.ogg ~/Downloads/audio
cp gharika.ogg ~/Downloads/audio
cp kadha.ogg ~/Downloads/audio
cp kipanya.ogg ~/Downloads/audio
cp vipimo.ogg ~/Downloads/audio
cp baba.ogg ~/Downloads/audio
cp soda.ogg ~/Downloads/audio
cp jangwa.ogg ~/Downloads/audio
cp jioni.ogg ~/Downloads/audio
cp kaptura.ogg ~/Downloads/audio
cp uhai.ogg ~/Downloads/audio
cp fungu.ogg ~/Downloads/audio
cp vilema.ogg ~/Downloads/audio
cp maharagwe.ogg ~/Downloads/audio
cp hasira.ogg ~/Downloads/audio
cp mbwa.ogg ~/Downloads/audio
cp madaktari.ogg ~/Downloads/audio
cp madini.ogg ~/Downloads/audio
cp hanjamu.ogg ~/Downloads/audio
cp chawa.ogg ~/Downloads/audio
cp mgongo.ogg ~/Downloads/audio
cp korongo.ogg ~/Downloads/audio
cp siagi.ogg ~/Downloads/audio
cp safu.ogg ~/Downloads/audio
cp koroga.ogg ~/Downloads/audio
cp wakuu.ogg ~/Downloads/audio
cp maembe.ogg ~/Downloads/audio
cp biscuit.ogg ~/Downloads/audio
cp mrija.ogg ~/Downloads/audio
cp changanya.ogg ~/Downloads/audio
cp hatia.ogg ~/Downloads/audio
cp mkono.ogg ~/Downloads/audio
cp kata.ogg ~/Downloads/audio
cp balagha.ogg ~/Downloads/audio
cp uvuvi.ogg ~/Downloads/audio
cp kiberiti.ogg ~/Downloads/audio
cp pete.ogg ~/Downloads/audio
cp kaktas.ogg ~/Downloads/audio
cp pana.ogg ~/Downloads/audio
cp kupima.ogg ~/Downloads/audio
cp ganda.ogg ~/Downloads/audio
cp jino.ogg ~/Downloads/audio
cp pua.ogg ~/Downloads/audio
cp funza.ogg ~/Downloads/audio
cp kidole.ogg ~/Downloads/audio
cp bata.ogg ~/Downloads/audio
cp hospitali.ogg ~/Downloads/audio
cp kupigana.ogg ~/Downloads/audio
cp sweta.ogg ~/Downloads/audio
cp simba.ogg ~/Downloads/audio
cp machozi.ogg ~/Downloads/audio
cp fagio.ogg ~/Downloads/audio
cp vifo.ogg ~/Downloads/audio
cp kiti.ogg ~/Downloads/audio
cp hema.ogg ~/Downloads/audio
cp sketi.ogg ~/Downloads/audio
cp nyungunyungu.ogg ~/Downloads/audio
cp gofu.ogg ~/Downloads/audio
cp kuganda.ogg ~/Downloads/audio
cp mpishi.ogg ~/Downloads/audio
cp dunia.ogg ~/Downloads/audio
cp nyasi.ogg ~/Downloads/audio
cp abiria.ogg ~/Downloads/audio
cp kunguru.ogg ~/Downloads/audio
cp kombe.ogg ~/Downloads/audio
cp nako.ogg ~/Downloads/audio
cp kadi.ogg ~/Downloads/audio
cp punda.ogg ~/Downloads/audio
cp kiuno.ogg ~/Downloads/audio
cp asubuhi.ogg ~/Downloads/audio
cp kaka.ogg ~/Downloads/audio
cp jikoni.ogg ~/Downloads/audio
cp ngano.ogg ~/Downloads/audio
cp mama.ogg ~/Downloads/audio
cp njia.ogg ~/Downloads/audio
cp tende.ogg ~/Downloads/audio
cp bingirisha.ogg ~/Downloads/audio
cp mtego.ogg ~/Downloads/audio
cp ajira.ogg ~/Downloads/audio
cp furushi.ogg ~/Downloads/audio
cp eropleni.ogg ~/Downloads/audio
cp nyekundu.ogg ~/Downloads/audio
cp nguvu.ogg ~/Downloads/audio
cp kimbia.ogg ~/Downloads/audio
cp waajiri.ogg ~/Downloads/audio
cp tajiri.ogg ~/Downloads/audio
cp fidla.ogg ~/Downloads/audio
cp sekta.ogg ~/Downloads/audio
cp wajibu.ogg ~/Downloads/audio
cp gharama.ogg ~/Downloads/audio
cp ukuta.ogg ~/Downloads/audio
cp chura.ogg ~/Downloads/audio
cp pamba.ogg ~/Downloads/audio
cp mkokoteni.ogg ~/Downloads/audio
cp bandari.ogg ~/Downloads/audio
cp figo.ogg ~/Downloads/audio
cp ndoo.ogg ~/Downloads/audio
cp magari.ogg ~/Downloads/audio
cp idhini.ogg ~/Downloads/audio
cp jani.ogg ~/Downloads/audio
cp kengele.ogg ~/Downloads/audio
cp chui.ogg ~/Downloads/audio
cp mende.ogg ~/Downloads/audio
cp mviringo.ogg ~/Downloads/audio
cp umeme.ogg ~/Downloads/audio
cp reli.ogg ~/Downloads/audio
cp chujio.ogg ~/Downloads/audio
cp vita.ogg ~/Downloads/audio
cp baiskeli.ogg ~/Downloads/audio
cp pakiti.ogg ~/Downloads/audio
cp uchaguzi.ogg ~/Downloads/audio
cp haki.ogg ~/Downloads/audio
cp pundamilia.ogg ~/Downloads/audio
cp kuogelea.ogg ~/Downloads/audio
cp kichongeo.ogg ~/Downloads/audio
cp bandeji.ogg ~/Downloads/audio
cp kufoka.ogg ~/Downloads/audio
cp injini.ogg ~/Downloads/audio
cp dondola.ogg ~/Downloads/audio
cp kifua.ogg ~/Downloads/audio
cp chati.ogg ~/Downloads/audio
cp ghairi.ogg ~/Downloads/audio
cp mjukuu.ogg ~/Downloads/audio
cp kriketi.ogg ~/Downloads/audio
cp jangili.ogg ~/Downloads/audio
cp safi.ogg ~/Downloads/audio
cp wazi.ogg ~/Downloads/audio
cp riwaya.ogg ~/Downloads/audio
cp maziwa.ogg ~/Downloads/audio
cp birika.ogg ~/Downloads/audio
cp fataki.ogg ~/Downloads/audio
cp pedi.ogg ~/Downloads/audio
cp huzuni.ogg ~/Downloads/audio
cp upinde.ogg ~/Downloads/audio
cp ubongo.ogg ~/Downloads/audio
cp mifupa.ogg ~/Downloads/audio
cp zaidi.ogg ~/Downloads/audio
cp ulinzi.ogg ~/Downloads/audio
cp afiki.ogg ~/Downloads/audio
cp changanyikiwa.ogg ~/Downloads/audio
cp daktari.ogg ~/Downloads/audio
cp damisi.ogg ~/Downloads/audio
cp ngome.ogg ~/Downloads/audio
cp msumari.ogg ~/Downloads/audio
cp mbweha.ogg ~/Downloads/audio
cp mtoto.ogg ~/Downloads/audio
cp mchanga.ogg ~/Downloads/audio
cp sofa.ogg ~/Downloads/audio
cp dhahabu.ogg ~/Downloads/audio
cp penseli.ogg ~/Downloads/audio
cp septemba.ogg ~/Downloads/audio
cp kuoka.ogg ~/Downloads/audio
cp damu.ogg ~/Downloads/audio
cp vyakula.ogg ~/Downloads/audio
cp pembe.ogg ~/Downloads/audio
cp silinda.ogg ~/Downloads/audio
cp tumbili.ogg ~/Downloads/audio
cp babu.ogg ~/Downloads/audio
cp fungasha.ogg ~/Downloads/audio
cp akili.ogg ~/Downloads/audio
cp uchafu.ogg ~/Downloads/audio
cp mundu.ogg ~/Downloads/audio
cp mwanasesere.ogg ~/Downloads/audio
cp mtama.ogg ~/Downloads/audio
cp brashi.ogg ~/Downloads/audio
cp nyanja.ogg ~/Downloads/audio
cp ahali.ogg ~/Downloads/audio
cp zulia.ogg ~/Downloads/audio
cp wembe.ogg ~/Downloads/audio
cp vipuli.ogg ~/Downloads/audio
cp panya.ogg ~/Downloads/audio
cp yai.ogg ~/Downloads/audio
cp biringani.ogg ~/Downloads/audio
cp kukimbia.ogg ~/Downloads/audio
cp mishipa.ogg ~/Downloads/audio
cp rafu.ogg ~/Downloads/audio
cp kaboni.ogg ~/Downloads/audio
cp shangazi.ogg ~/Downloads/audio
cp shati.ogg ~/Downloads/audio
cp karoti.ogg ~/Downloads/audio
cp bundi.ogg ~/Downloads/audio
cp kinga.ogg ~/Downloads/audio
cp mguu.ogg ~/Downloads/audio
cp myna.ogg ~/Downloads/audio
cp jinzi.ogg ~/Downloads/audio
cp ishirini.ogg ~/Downloads/audio
cp kipepeo.ogg ~/Downloads/audio
cp sehemu.ogg ~/Downloads/audio
cp kipofu.ogg ~/Downloads/audio
cp taa.ogg ~/Downloads/audio
cp nyonga.ogg ~/Downloads/audio
cp dirisha.ogg ~/Downloads/audio
cp kijiko.ogg ~/Downloads/audio
cp fainali.ogg ~/Downloads/audio
cp kijani.ogg ~/Downloads/audio
cp dawati.ogg ~/Downloads/audio
cp tingatinga.ogg ~/Downloads/audio
cp itikadi.ogg ~/Downloads/audio
cp wanyama.ogg ~/Downloads/audio
cp waya.ogg ~/Downloads/audio
cp joto.ogg ~/Downloads/audio
cp abudu.ogg ~/Downloads/audio
cp kipepea.ogg ~/Downloads/audio
cp kuziba.ogg ~/Downloads/audio
cp mdogo.ogg ~/Downloads/audio
cp viti.ogg ~/Downloads/audio
cp tamasha.ogg ~/Downloads/audio
cp bibi.ogg ~/Downloads/audio
cp lengo.ogg ~/Downloads/audio
cp tangawizi.ogg ~/Downloads/audio
cp patasi.ogg ~/Downloads/audio
cp njegere.ogg ~/Downloads/audio
cp safisha.ogg ~/Downloads/audio
cp daka.ogg ~/Downloads/audio
cp koni.ogg ~/Downloads/audio
cp soka.ogg ~/Downloads/audio
cp kabati.ogg ~/Downloads/audio
cp baraka.ogg ~/Downloads/audio
cp menya.ogg ~/Downloads/audio
cp kofia.ogg ~/Downloads/audio
cp chiriku.ogg ~/Downloads/audio
cp kuku.ogg ~/Downloads/audio
cp dampo.ogg ~/Downloads/audio
cp leja.ogg ~/Downloads/audio
cp kutembea.ogg ~/Downloads/audio
cp filimbi.ogg ~/Downloads/audio
cp lango.ogg ~/Downloads/audio
cp fomu.ogg ~/Downloads/audio
cp falaki.ogg ~/Downloads/audio
cp mbao.ogg ~/Downloads/audio
cp madereva.ogg ~/Downloads/audio
cp pochi.ogg ~/Downloads/audio
cp kiroboto.ogg ~/Downloads/audio
cp virusi.ogg ~/Downloads/audio
cp kipande.ogg ~/Downloads/audio
cp manyoya.ogg ~/Downloads/audio
cp ombi.ogg ~/Downloads/audio
cp aki.ogg ~/Downloads/audio
cp walimu.ogg ~/Downloads/audio
cp ghala.ogg ~/Downloads/audio
cp shika.ogg ~/Downloads/audio
cp mjomba.ogg ~/Downloads/audio
cp dawa.ogg ~/Downloads/audio
cp shayiri.ogg ~/Downloads/audio
cp kibaniko.ogg ~/Downloads/audio
cp mbu.ogg ~/Downloads/audio
cp yowe.ogg ~/Downloads/audio
cp koleo.ogg ~/Downloads/audio
cp serikali.ogg ~/Downloads/audio
cp kerengende.ogg ~/Downloads/audio
cp ulimi.ogg ~/Downloads/audio
cp kamanda.ogg ~/Downloads/audio
cp mwani.ogg ~/Downloads/audio
cp vyama.ogg ~/Downloads/audio
cp deni.ogg ~/Downloads/audio
cp jibini.ogg ~/Downloads/audio
cp jiko.ogg ~/Downloads/audio
cp sumaku.ogg ~/Downloads/audio
cp goli.ogg ~/Downloads/audio
cp mwanzi.ogg ~/Downloads/audio
cp koti.ogg ~/Downloads/audio
cp mchemraba.ogg ~/Downloads/audio
cp mchana.ogg ~/Downloads/audio
cp moyo.ogg ~/Downloads/audio
cp ishi.ogg ~/Downloads/audio
cp idhinisha.ogg ~/Downloads/audio
cp bezi.ogg ~/Downloads/audio
cp shingo.ogg ~/Downloads/audio
cp ndondi.ogg ~/Downloads/audio
cp bega.ogg ~/Downloads/audio
cp kushughulikia.ogg ~/Downloads/audio
cp balozi.ogg ~/Downloads/audio
cp walinzi.ogg ~/Downloads/audio
cp tamko.ogg ~/Downloads/audio
cp nyeusi.ogg ~/Downloads/audio
cp ruka.ogg ~/Downloads/audio
cp mkufu.ogg ~/Downloads/audio
cp chemsha.ogg ~/Downloads/audio
cp mkuki.ogg ~/Downloads/audio
cp cheche.ogg ~/Downloads/audio
cp alama.ogg ~/Downloads/audio
cp snuka.ogg ~/Downloads/audio
cp mjusi.ogg ~/Downloads/audio
cp taarifa.ogg ~/Downloads/audio
cp ujasiri.ogg ~/Downloads/audio
cp pole.ogg ~/Downloads/audio
cp ndogo.ogg ~/Downloads/audio
cp riadha.ogg ~/Downloads/audio
cp tai.ogg ~/Downloads/audio
cp macho.ogg ~/Downloads/audio
cp usiku.ogg ~/Downloads/audio
cp gauni.ogg ~/Downloads/audio
cp fenesi.ogg ~/Downloads/audio
cp kipupwe.ogg ~/Downloads/audio
cp rasharasha.ogg ~/Downloads/audio
cp kanzu.ogg ~/Downloads/audio
cp sungura.ogg ~/Downloads/audio
cp elimu.ogg ~/Downloads/audio
cp taulo.ogg ~/Downloads/audio
cp ufunguo.ogg ~/Downloads/audio
cp popo.ogg ~/Downloads/audio
cp chakula.ogg ~/Downloads/audio
cp sufuria.ogg ~/Downloads/audio
cp darasa.ogg ~/Downloads/audio
cp gundi.ogg ~/Downloads/audio
cp inzi.ogg ~/Downloads/audio
cp sifuri.ogg ~/Downloads/audio
cp adhabu.ogg ~/Downloads/audio
cp imani.ogg ~/Downloads/audio
cp deki.ogg ~/Downloads/audio
cp mfuko.ogg ~/Downloads/audio
cp kamera.ogg ~/Downloads/audio
cp hati.ogg ~/Downloads/audio
cp nazi.ogg ~/Downloads/audio
cp kobe.ogg ~/Downloads/audio
cp pilipili.ogg ~/Downloads/audio
cp kuchimba.ogg ~/Downloads/audio
cp ofisa.ogg ~/Downloads/audio
cp lawama.ogg ~/Downloads/audio
cp kasuku.ogg ~/Downloads/audio
cp ilani.ogg ~/Downloads/audio
cp adui.ogg ~/Downloads/audio
cp takwimu.ogg ~/Downloads/audio
cp furaha.ogg ~/Downloads/audio
cp pipi.ogg ~/Downloads/audio
cp jua.ogg ~/Downloads/audio
cp bahari.ogg ~/Downloads/audio
cp viazi.ogg ~/Downloads/audio
cp lozi.ogg ~/Downloads/audio
cp ligi.ogg ~/Downloads/audio
cp wakurugenzi.ogg ~/Downloads/audio
cp pini.ogg ~/Downloads/audio
cp kiwavi.ogg ~/Downloads/audio
cp saba.ogg ~/Downloads/audio
cp chemli.ogg ~/Downloads/audio
cp kibolili.ogg ~/Downloads/audio
cp kiokeo.ogg ~/Downloads/audio
cp pink.ogg ~/Downloads/audio
cp kondoo.ogg ~/Downloads/audio
cp gego.ogg ~/Downloads/audio
cp kucheza.ogg ~/Downloads/audio
cp kunde.ogg ~/Downloads/audio
cp almasi.ogg ~/Downloads/audio
cp leo.ogg ~/Downloads/audio
cp nati.ogg ~/Downloads/audio
cp sikio.ogg ~/Downloads/audio
cp jengo.ogg ~/Downloads/audio
cp paka.ogg ~/Downloads/audio
cp chupa.ogg ~/Downloads/audio
cp polisi.ogg ~/Downloads/audio
cp kahawa.ogg ~/Downloads/audio
cp kifaru.ogg ~/Downloads/audio
cp ngumi.ogg ~/Downloads/audio
cp kinyonga.ogg ~/Downloads/audio
cp madiwani.ogg ~/Downloads/audio
cp pomboo.ogg ~/Downloads/audio
cp kichakato.ogg ~/Downloads/audio
cp kaakaa.ogg ~/Downloads/audio
cp jamhuri.ogg ~/Downloads/audio
cp sindano.ogg ~/Downloads/audio
cp tarumbeta.ogg ~/Downloads/audio
cp fisi.ogg ~/Downloads/audio
cp kamati.ogg ~/Downloads/audio
cp mto.ogg ~/Downloads/audio
cp kifungo.ogg ~/Downloads/audio
cp sisiminzi.ogg ~/Downloads/audio
cp firauni.ogg ~/Downloads/audio
cp pwani.ogg ~/Downloads/audio
cp uji.ogg ~/Downloads/audio
cp mafunzo.ogg ~/Downloads/audio
cp pipa.ogg ~/Downloads/audio
cp imara.ogg ~/Downloads/audio
cp rais.ogg ~/Downloads/audio
cp amari.ogg ~/Downloads/audio
cp janga.ogg ~/Downloads/audio
cp chenza.ogg ~/Downloads/audio
cp idara.ogg ~/Downloads/audio
cp mraba.ogg ~/Downloads/audio
cp nyati.ogg ~/Downloads/audio
cp kitanda.ogg ~/Downloads/audio
cp lenzi.ogg ~/Downloads/audio
cp mwamvuli.ogg ~/Downloads/audio
cp moto.ogg ~/Downloads/audio
cp chaguo.ogg ~/Downloads/audio
cp kukaanga.ogg ~/Downloads/audio
cp taka.ogg ~/Downloads/audio
cp mafuta.ogg ~/Downloads/audio
cp panzi.ogg ~/Downloads/audio
cp chama.ogg ~/Downloads/audio
cp jogoo.ogg ~/Downloads/audio
cp picha.ogg ~/Downloads/audio
cp duma.ogg ~/Downloads/audio
cp malaika.ogg ~/Downloads/audio
cp kisu.ogg ~/Downloads/audio
cp chembe.ogg ~/Downloads/audio
cp fedha.ogg ~/Downloads/audio
cp tambaa.ogg ~/Downloads/audio
cp farakano.ogg ~/Downloads/audio
cp mlango.ogg ~/Downloads/audio
cp zoezi.ogg ~/Downloads/audio
cp mazoezi.ogg ~/Downloads/audio
cp mwiko.ogg ~/Downloads/audio
cp imarisha.ogg ~/Downloads/audio
cp ngazi.ogg ~/Downloads/audio
cp demokrasia.ogg ~/Downloads/audio
cp mnyororo.ogg ~/Downloads/audio
cp baharia.ogg ~/Downloads/audio
cp nyusi.ogg ~/Downloads/audio
cp magodoro.ogg ~/Downloads/audio
cp kahawia.ogg ~/Downloads/audio
cp kozi.ogg ~/Downloads/audio
cp usingizi.ogg ~/Downloads/audio
cp ufutio.ogg ~/Downloads/audio
cp nyeupe.ogg ~/Downloads/audio
cp dari.ogg ~/Downloads/audio
cp tembea.ogg ~/Downloads/audio
cp yadi.ogg ~/Downloads/audio
cp jamaa.ogg ~/Downloads/audio
cp mti.ogg ~/Downloads/audio
cp albamu.ogg ~/Downloads/audio
cp mkate.ogg ~/Downloads/audio
cp amiba.ogg ~/Downloads/audio
cp mwamba.ogg ~/Downloads/audio
cp gitaa.ogg ~/Downloads/audio
cp fahali.ogg ~/Downloads/audio
cp gome.ogg ~/Downloads/audio
cp mamba.ogg ~/Downloads/audio
cp mpira.ogg ~/Downloads/audio
cp kuumia.ogg ~/Downloads/audio
cp fremu.ogg ~/Downloads/audio
cp kurunzi.ogg ~/Downloads/audio
cp jaketi.ogg ~/Downloads/audio
cp ngisi.ogg ~/Downloads/audio
cp friji.ogg ~/Downloads/audio
cp wanafunzi.ogg ~/Downloads/audio
cp uma.ogg ~/Downloads/audio
cp komamanga.ogg ~/Downloads/audio
cp mshumaa.ogg ~/Downloads/audio
cp upendo.ogg ~/Downloads/audio
cp kabidhi.ogg ~/Downloads/audio
cp strouberi.ogg ~/Downloads/audio
cp twiga.ogg ~/Downloads/audio
cp feri.ogg ~/Downloads/audio
cp magonjwa.ogg ~/Downloads/audio
cp blanketi.ogg ~/Downloads/audio
cp ua.ogg ~/Downloads/audio
cp tofali.ogg ~/Downloads/audio
cp ziada.ogg ~/Downloads/audio
cp uyoga.ogg ~/Downloads/audio
cp ugonjwa.ogg ~/Downloads/audio
cp marimba.ogg ~/Downloads/audio
cp jamiana.ogg ~/Downloads/audio
cp basi.ogg ~/Downloads/audio
cp kenge.ogg ~/Downloads/audio
cp wimbi.ogg ~/Downloads/audio
cp ajabu.ogg ~/Downloads/audio
cp kichanganyio.ogg ~/Downloads/audio
cp chaki.ogg ~/Downloads/audio
cp mvua.ogg ~/Downloads/audio
cp kinanda.ogg ~/Downloads/audio
cp bwawa.ogg ~/Downloads/audio
cp njaa.ogg ~/Downloads/audio
cp vuguvugu.ogg ~/Downloads/audio
cp pointi.ogg ~/Downloads/audio
cp afya.ogg ~/Downloads/audio
cp utepe.ogg ~/Downloads/audio
cp sakafu.ogg ~/Downloads/audio
cp bluu.ogg ~/Downloads/audio
cp godoro.ogg ~/Downloads/audio
cp gazeti.ogg ~/Downloads/audio
cp glopu.ogg ~/Downloads/audio
cp mvuke.ogg ~/Downloads/audio
cp tupa.ogg ~/Downloads/audio
cp kabila.ogg ~/Downloads/audio
cp tofaa.ogg ~/Downloads/audio
cp meno.ogg ~/Downloads/audio
cp mapafu.ogg ~/Downloads/audio
cp roketi.ogg ~/Downloads/audio
cp wanawake.ogg ~/Downloads/audio
cp sabuni.ogg ~/Downloads/audio
cp ibada.ogg ~/Downloads/audio
cp mkoba.ogg ~/Downloads/audio
cp jokofu.ogg ~/Downloads/audio
cp ghashi.ogg ~/Downloads/audio
cp bajeti.ogg ~/Downloads/audio
cp konokono.ogg ~/Downloads/audio
cp dhoruba.ogg ~/Downloads/audio
cp kinywa.ogg ~/Downloads/audio
cp taswira.ogg ~/Downloads/audio
cp rafiki.ogg ~/Downloads/audio
cp trekta.ogg ~/Downloads/audio
cp yavuyavu.ogg ~/Downloads/audio
cp chiku.ogg ~/Downloads/audio
cp ubavu.ogg ~/Downloads/audio
cp mashua.ogg ~/Downloads/audio
cp shinda.ogg ~/Downloads/audio
cp ukuaji.ogg ~/Downloads/audio
cp midomo.ogg ~/Downloads/audio
cp askari.ogg ~/Downloads/audio
cp nondo.ogg ~/Downloads/audio
cp kuchoka.ogg ~/Downloads/audio
cp susu.ogg ~/Downloads/audio
cp chumvi.ogg ~/Downloads/audio
cp kaa.ogg ~/Downloads/audio
cp tembo.ogg ~/Downloads/audio
cp bakuli.ogg ~/Downloads/audio
cp mbayuwayu.ogg ~/Downloads/audio
cp cheo.ogg ~/Downloads/audio
cp karatasi.ogg ~/Downloads/audio
cp mkunga.ogg ~/Downloads/audio
cp nyanya.ogg ~/Downloads/audio
cp nyundo.ogg ~/Downloads/audio
cp shavu.ogg ~/Downloads/audio
cp kidani.ogg ~/Downloads/audio
cp dagla.ogg ~/Downloads/audio
cp kipanga.ogg ~/Downloads/audio
cp vuli.ogg ~/Downloads/audio
cp kolibri.ogg ~/Downloads/audio
cp kaoshi.ogg ~/Downloads/audio
cp kumwaga.ogg ~/Downloads/audio
cp tandu.ogg ~/Downloads/audio
cp baseball.ogg ~/Downloads/audio
cp taji.ogg ~/Downloads/audio
cp kalamu.ogg ~/Downloads/audio
cp jarari.ogg ~/Downloads/audio
cp nge.ogg ~/Downloads/audio
cp pato.ogg ~/Downloads/audio
cp seremala.ogg ~/Downloads/audio
cp waandishi.ogg ~/Downloads/audio
cp ndege.ogg ~/Downloads/audio
cp chai.ogg ~/Downloads/audio
cp wanaume.ogg ~/Downloads/audio
cp kamba.ogg ~/Downloads/audio
cp dazani.ogg ~/Downloads/audio
cp haja.ogg ~/Downloads/audio
cp ghali.ogg ~/Downloads/audio
cp mmea.ogg ~/Downloads/audio
cp sokwe.ogg ~/Downloads/audio
cp uso.ogg ~/Downloads/audio
cp nene.ogg ~/Downloads/audio
cp walezi.ogg ~/Downloads/audio
cp funga.ogg ~/Downloads/audio
cp jongoo.ogg ~/Downloads/audio
cp tango.ogg ~/Downloads/audio
cp machungwa.ogg ~/Downloads/audio
cp vikundi.ogg ~/Downloads/audio
cp hofu.ogg ~/Downloads/audio
cp thread.ogg ~/Downloads/audio
cp kisigino.ogg ~/Downloads/audio
cp dubu.ogg ~/Downloads/audio
cp njiwa.ogg ~/Downloads/audio
cp adhibu.ogg ~/Downloads/audio
cp dada.ogg ~/Downloads/audio
cp mwewe.ogg ~/Downloads/audio
cp tano.ogg ~/Downloads/audio
cp ukungu.ogg ~/Downloads/audio
cp ngwini.ogg ~/Downloads/audio
cp puto.ogg ~/Downloads/audio
cp kijivu.ogg ~/Downloads/audio
cp shule.ogg ~/Downloads/audio
cp uchovu.ogg ~/Downloads/audio
cp povu.ogg ~/Downloads/audio
cp ndovu.ogg ~/Downloads/audio
cp mshale.ogg ~/Downloads/audio
cp pango.ogg ~/Downloads/audio
cp ukanda.ogg ~/Downloads/audio
cp hadithi.ogg ~/Downloads/audio
cp nafuu.ogg ~/Downloads/audio
cp suruali.ogg ~/Downloads/audio
cp mtindi.ogg ~/Downloads/audio
cp shomoro.ogg ~/Downloads/audio
cp teleka.ogg ~/Downloads/audio
cp soksi.ogg ~/Downloads/audio
cp haramia.ogg ~/Downloads/audio
cp mapera.ogg ~/Downloads/audio
cp saa.ogg ~/Downloads/audio
cp pikipiki.ogg ~/Downloads/audio
cp sataranji.ogg ~/Downloads/audio
cp puliza.ogg ~/Downloads/audio
cp njano.ogg ~/Downloads/audio
cp hatari.ogg ~/Downloads/audio
cp cheka.ogg ~/Downloads/audio
cp msisimko.ogg ~/Downloads/audio
cp sahani.ogg ~/Downloads/audio
cp mbuzi.ogg ~/Downloads/audio
cp sharubu.ogg ~/Downloads/audio
cp zawadi.ogg ~/Downloads/audio
cp kambi.ogg ~/Downloads/audio
cp pweza.ogg ~/Downloads/audio
cp gari.ogg ~/Downloads/audio
cp kadhaa.ogg ~/Downloads/audio
cp zambarau.ogg ~/Downloads/audio
cp nakala.ogg ~/Downloads/audio
cp medali.ogg ~/Downloads/audio
cp nyota.ogg ~/Downloads/audio
cp sanduku.ogg ~/Downloads/audio
cp kimbunga.ogg ~/Downloads/audio
cp nafasi.ogg ~/Downloads/audio
cp kipimio.ogg ~/Downloads/audio
cp nyoka.ogg ~/Downloads/audio
cp kionesha.ogg ~/Downloads/audio
cp ulimwengu.ogg ~/Downloads/audio
cp oka.ogg ~/Downloads/audio
cp pazia.ogg ~/Downloads/audio
cp bambika.ogg ~/Downloads/audio
