class CollectedItemData {
  final String imageName;
  final String categoryName;

  CollectedItemData(this.imageName, this.categoryName);

  @override
  String toString() {
    return '{imageName:$imageName,categoryName:$categoryName}';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollectedItemData &&
          runtimeType == other.runtimeType &&
          imageName == other.imageName &&
          categoryName == other.categoryName; 

  @override
  int get hashcode => imageName.hashCode ^ categoryName.hashCode;



}

class CollectionTitle {
  final String imageName;
  final String categoryName;

  CollectionTitle(this.imageName, this.categoryName);
}

Map<CollectionTitle, List<CollectedItemData>> list = {
  CollectionTitle('assets/alphabet.png', 'Alphabet'): [
    CollectedItemData('assets/camera.png', 'Orange'),
    CollectedItemData('assets/camera.png', 'Alphabet'),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/animal.png', 'Animal'): [
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/camera.png', 'camera'): [
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/clothes.png', 'Clothes'): [
    CollectedItemData('assets/camera.png', 'Clothes' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/electronic.png', 'Electronic'): [
    CollectedItemData('assets/camera.png', 'Electron' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/emotion.png', 'Emotions'): [
    CollectedItemData('assets/camera.png', 'Emotions' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/fruit.png', 'Fruits'): [
    CollectedItemData('assets/camera.png', 'Fruits' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/furniture.png', 'Furniture'): [
    CollectedItemData('assets/camera.png', 'Furniture' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/grains.png', 'Grains'): [
    CollectedItemData('assets/camera.png', 'Grains' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/mic.png', 'Mic'): [
    CollectedItemData('assets/camera.png', 'Mic' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/number.png', 'number'): [
    CollectedItemData('assets/camera.png', 'Number' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/stickers.png', 'stickers'): [
    CollectedItemData('assets/camera.png', 'Stickers' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/shape.png', 'Shape'): [
    CollectedItemData('assets/camera.png', 'Shape' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/stationary.png', 'Stationary'): [
    CollectedItemData('assets/camera.png', 'Stationary' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/text.png', 'Text'): [
    CollectedItemData('assets/camera.png', 'Text' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
  CollectionTitle('assets/tools.png', 'Tools'): [
    CollectedItemData('assets/camera.png', 'Tools' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
    CollectedItemData('assets/camera.png', 'Alphabet' ),
    CollectedItemData('assets/camera.png', 'hat2' ),
    CollectedItemData('assets/camera.png', 'glasses1' ),
    CollectedItemData('assets/camera.png', 'glasses2' ),
    CollectedItemData('assets/camera.png', 'tattoo1' ),
    CollectedItemData('assets/camera.png', 'tattoo2' ),
    CollectedItemData('assets/camera.png', 'earring1' ),
    CollectedItemData('assets/camera.png', 'earring2' ),
    CollectedItemData('assets/camera.png', 'hat1' ),
    CollectedItemData('assets/camera.png', 'beard1' ),
    CollectedItemData('assets/camera.png', 'beard2' ),
    CollectedItemData('assets/camera.png', 'Orange' ),
  ],
};

