INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra', 2, 'Zebra', 'assets/topic/zebra.svg', 'With their signature black and white stripes who cannot recognize a zebra! Zebras are single-hoofed animals that are native of Africa. Zebras belong to horse family and are very closely realted to horses and donkeys. Zebras are now in the endangered animals list with only 2500 - 2700 population in the world.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra3', 1, 'I can draw a Zebra', 'Image of Zebra without stripes(Not available under CC0)', 'Draw stripes using the black color on the animal to create a zebra.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra4', 1, 'Creating a Zebra', 'assets/topic/zebrahandprint_4.jpg', 'Create a zebra on the given hand print.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra4', 2, 1, 'assets/topic/zebra_hand_template_1.png');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra6', 1, 'My creative park of Zebras', 'assets/topic/zebra_5.jpg', 'Using the pictures, create your park of Zebras.', 'zebra');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra7', 1, 'Zebra Crossing on the Road', 'assets/topic/CrossRoadWithoutZebra_6.jpg', 'Draw zebra crossing to help the people cross the road.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra8', 3, 'Looking between the lines of their family', 'assets/topic/zebra_5.jpg', 'Zebras are native to the African Continent. Often times we think zebras are just horses with stripes. No, you are wrong. Zebras belong to horse family but they are very much unique.  But horses and donkeys are their close relatives. There are three different types of zebras. The plains zebra, the mountain zebra and the grevvy''s zebra. The plains zebra are found in the treeless grasslands and woodlands of eastern and southern Africa. The mountain zebras are native to mountainous regions of southwestern Africa. The Grevvy''s zebra are found in small areas of Kenya and Ethopia. The Gravvy''s zebra weighs around 350 - 450 kilograms. The mountain zebra weighs around 240 to 372 kilograms and the Plains zebra weighs around 350 kilograms. Wow! that''s truly a heavy weight.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra9', 3, 'Unique habits of the striped friend', 'assets/topic/zebraArticle_9.jpg', 'Zebras live in family groups led by a male zebra with several female zebras and offsprings. The male zebra is known as a stallion. The female zebra is known as a mare. The baby zebra is known as a foal.
Zebras mostly eat grass and will travel upto 1800 miles in search of food. Being herbivorous they sometimes eat barks, twigs and also leaves. Female zebras carry their youngones in womb for a period of 12 to 14 months. The baby zebras will weigh from 25 to 40 kgs at their birth. Soon after the birth the baby zebras are able to walk and run. Zebras will become fully independant at 3 to 6 years old.  Zebras will have a life span of 30 to 40 years. Aren''t these habits unique!', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra10', 3, 'Social bonding of Zebras', 'assets/topic/zebra_5.jpg', 'Zebras are often found among other animal groups, especially the wild beasts for safety in numbers. A large herd of animals are usually confusing to the predators. Zebras have several ways to communicate with one another. Facial expressions, such as wide-open eyes or barred teeth, all mean something. They also bark, bray, snort or huff to get their point across. Even the position of their ears signal their feelings. They can rotate their ears to almost any direction. Zebras sleep standing up and its really cool. Do you think you will be able to fall asleep standing up? and, they sleep only when they are in the safety of their group. Aren''t their social bonding amazing!', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra11', 3, 'Important facts that Zebra carry', 'assets/topic/zebra_5.jpg', 'The swahili name of a zebra is "Punda Milia"
This is super cool! No two zebras, ever have the same 2 stripes. They are just like our fingerprints. Wow! there must be loads of different patterns!
Zebra crossings are named after the black and white stripes of zebras. Zebra crossings are also known as pedestrian crossings. Now isn''t that an inspiration!
Zebras are super speedy animals. In fact, they can run upto 65 miles per hour. Now that is seriously fast!
Zebras look cute and friendly, but they can be aggressive animals too! The piercing bites and powerful kicks are strong enough to cause serious damage and sometimes even kill! That''s a caution! Keep yourself away from the striped animal.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra12', 0, 'Does zebra belong to a horse family?', 'assets/topic/zebra_5.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra12', 1, 1, 'yes');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra12', 0, 1, 'no');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra15', 0, 'A zebra is a super cute animal, but can be _______________.', 'assets/topic/zebraArticle_9.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra15', 1, 1, 'very aggressive');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra15', 0, 1, 'very friendly');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra15', 0, 2, 'very mild');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra19', 0, 'No two _____________________ are identical.', 'assets/topic/zebraArticle_9.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra19', 1, 1, 'stripes');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra19', 0, 1, 'tails');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra19', 0, 2, 'patterns');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra23', 0, 'Is zebra a herbivore?', 'assets/topic/zebra_5.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra23', 1, 1, 'yes');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra23', 0, 1, 'no');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra26', 0, 'Match the parts to complete the picture', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra26', 1, 1, 'assets/topic/zebraEars_35.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra26', 1, 2, 'Ear');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra26', 1, 3, 'assets/topic/zebraLegs_36.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra26', 1, 4, 'Leg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra26', 1, 5, 'assets/topic/zebraTail_37.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra26', 1, 6, 'Tail');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra33', 0, 'Choose the correct word', 'assets/topic/zebra_5.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra33', 1, 1, 'herbivorous');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra33', 0, 1, 'bivorherous');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra33', 0, 2, 'vorousherbi');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra37', 0, 'Choose the correct word', 'assets/topic/zebraAfrica_39.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra37', 1, 1, 'africa');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra37', 0, 1, 'ricafa');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra37', 0, 2, 'carifa');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra41', 0, 'Choose the correct word', 'assets/topic/zebra_5.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra41', 1, 1, 'zebra');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra41', 0, 1, 'braez');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra41', 0, 2, 'rabez');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird', 2, 'Fischer''s Lovebird', 'assets/topic/lovebird.svg', 'This cute looking bird has a cute name just like its look and its called as "Fischer''s Lovebird". It looks like a tiny parrot. This amazing bird was initially discovered by a German explorer, Gustav Fischer in 19th century. That''s why the name Fischer''s Lovebird.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird3', 1, 'My cute little ''Fischer''', 'assets/topic/fischerslovebird_7.jpg', 'Choose the images and create the picture of a Fischer''s Lovebird.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird4', 1, 'I can make my own Fischer''s lovebird', NULL, 'Using the drawing tools draw, color and create your own Fischer''s lovebird', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird5', 1, 'My Bird Sanctuary', 'assets/topic/fischerslovebird_7.jpg', 'Using the images and the drawing tools create a bird sanctuary for your Fischer''s lovebirds.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird6', 1, 'Colourless to colourful', 'assets/topic/lovebirdArticle_6.jpg', 'Colour the fischer''s lovebirds using different colours of your choice.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird7', 3, 'A little knowledge about the little bird', 'assets/topic/lovebirdArticle_6.jpg', 'Fischer''s lovebirds are native to central Africa. Fischer''s lovebirds stay in isolated group of trees with grass plains between them. It generally stays at a height of 1,100 to 2000 metres above sea level and more often near water. These tiny birds make their home in holes of trees, rocks or shrubs in the wild. They usually nest in groups or pair off creating their own home. The Fischer''s lovebirds can live from 15 to 25 years.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird8', 3, 'Impressive personality it owns', 'assets/topic/fischerslovebird_7.jpg', 'Fischer''s lovebirds are very tiny in size compared to that of a parrot. With 5.5 inches length and 43 to 58 grams weight they almost look like a toy parrot. In spite of their small size they are bold, curious and always on the go. Fischer lovebird is also known by its eye ring. It has a white circle around its eye. Fischer''s lovebirds are very colourful. Orange, red, yellow, green, blue, grey, white and pink colours are beautifully and wonderfully shaded all over their tiny bodies.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird9', 3, 'Get to know the behaviour', 'assets/topic/lovebirdArticle_6.jpg', 'Fischer''s lovebirds display lot of social bonding. They are always seen in pairs. If the lovebirds are seperated from their flock they go into depression. Fischer''s lovebird has a fast flight. It''s so fast that the sound of their wings is heard as they fly. These tiny little creatures are chatty bunch. They keep singing and whistling all day long. They are especially vocal during the dawn and the dusk. Their chirping sound is pleasant to ears. They are flocking birds and they love talking to each other. Isn''t that an interesting behaviour!', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird10', 3, 'All about the chicks', 'assets/topic/lovebirdEgg_10.jpg', 'Fischer''s lovebirds lay eggs in season from january to july. The eggs are laid in the holes of the trees. The eggs are white in colour and they are usually 4 to 8 in numbers. The female lovebird sits on the eggs for 21 to 23 days until its all hatched. The small babies fledge from the nest about 38-42 days after hatching. The baby lovebirds are called as chicks. The female lovebird will feed the chicks while they are in the nest. The male lovebird will teach the chicks to eat regular food. That makes a happy family.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird11', 3, 'Important facts that can''t be missed', 'assets/topic/lovebirdArticle_6.jpg', 'Fischer''s Love birds are kept as a pet in almost all over the world. Hope you have seen it!
These Love birds often feed each other. One bird transfers the food to an other bird. So, now we know how they carry their name.
There are 9 different types of love birds in all. Hanging parrot found in Asia is their closest relative. 
Fischer''s love birds have a healthy diet. They eat seeds, berries, fruit and ocassionaly insect larva in the wild. They sometimes enjoy eating millets and maize. Hence  they carry the name as "Crafty Crop Pests".
Love birds are agressive in nature. They are quiet jealous or disturbed when other birds enter their group. So, watch out the little friend gets angry too.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird12', 0, 'Which is the native of Fischer''s lovebird?', 'assets/topic/zebraAfrica_39.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird12', 1, 1, 'Central Africa');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird12', 0, 1, 'America');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird12', 0, 2, 'India');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird16', 0, 'Fischer''s lovebird was first discovered by a  ___________ explorer, Gustav Fischer.', 'assets/topic/fischerslovebird_7.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird16', 1, 1, 'german');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird16', 0, 1, 'chinese');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird16', 0, 2, 'african');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird20', 0, 'Identify the body parts and match it with their names', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird20', 1, 1, 'tail');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird20', 1, 2, 'assets/topic/birdtail_31.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird20', 1, 3, 'body');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird20', 1, 4, 'assets/topic/birdbody_33.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird20', 1, 5, 'beak');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird20', 1, 6, 'assets/topic/birdbeak_35.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird20', 1, 7, 'feather');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird20', 1, 8, 'assets/topic/birdfeather_37.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird20', 1, 9, 'foot');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird20', 1, 10, 'assets/topic/birdfeet_39.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird31', 0, 'Fischer''s lovebirds make their homes inside the water', 'assets/topic/lovebirdArticle_6.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird31', 1, 1, 'False');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird31', 0, 1, 'True');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird34', 0, 'baby  _______', 'assets/topic/lovebirdchick_34.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird34', 1, 1, 'chicks');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird34', 0, 1, 'calf');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird37', 0, 'Gustav  _________', 'assets/topic/fischerslovebird_7.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird37', 1, 1, 'Fischer');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird37', 0, 1, 'Marvel');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird40', 0, 'Ring ___________', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird40', 1, 1, 'eyes');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird40', 0, 1, 'tail');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile', 2, 'Crocodile', NULL, 'Who don''t recognise this water animal? Crocodiles......... aren''t they frightening. Crocodiles are water reptiles, and among the most feared carnivorous animal on earth. There are over 23 different types of crocodiles on the planet. These scary animals are one of the ancient living beings on earth. They have been here since 240 million years. The oldest ancestor ever.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile3', 1, 'The scariest reptile', 'assets/topic/blankCrocodile_3.png', 'Draw scales on the given picture of the crocodile. Make it a scary crocodile.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile4', 1, 'Look what I have drawn', NULL, 'Using the drawing tools draw, color and create the picture of a crocodile', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile5', 1, 'Caution - Float of crocodiles', 'assets/topic/crocodileTrees_7.jpg, crocodiles_7.jpg, crocodilerocks_7.jpg, crocodilewarning_7.jpg', 'Using the images and the drawing tools create a group of crocodiles in the water with a danger zone board.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile6', 1, 'A Colourful and Trendy Crocodile', NULL, 'Colour the picture of the crocodile using your choice of colours. Add on dress, cap/hat or any accessories and make it a trendy looking crocodile.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile7', 3, 'Getting to know the wild predator', NULL, 'The large scariest water monster is a carnivor. Being a meat eater it enjoys eating birds, fish and mammals. sometimes they attack man too. Small crocodiles are also the easiest prey to this wild predator. It sounds strange but true. It will not spare it''s young ones too. Despite of being grouped under reptiles, crocodile is more closely related to dinosaur. It is believed to have been living alongside dinosaur and birds. we don''t see the dinosaur anymore but crocodiles still survive. This is truly amazing.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile8', 3, 'Amazing features of the giant', NULL, 'These giant neighbours vary in size and weight. The largest crocodile can grow from 13 to 18 feet and weigh upto 2200 pounds. The smallest being the dwarf in the crocodile family can reach 5 feet and will weigh around  40 to 70 pounds. Now, being a pure meat eater this water beast has twenty four sharp teeth.  The skin on their back contains bony structures which make them bullet proof. The skin on the belly is gentle. So, finally something is gentle.  They have a long snout which varies in shape and proportion. The nostrils, eye and ear opening are the highest part of the head. The body of the crocodile is streamlined with thier webbed feet tucking out. That''s the amazing body features of the giant water monster.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile9', 3, 'Fascinating eating habits of the crocodile', NULL, 'Crocodiles are carnivorous. This means they eat only and only meat. Eating is so fun and specially when we eat our favourite food. We just chew and chew and keep chewing. Now, stop there, crocodiles eat their favorite food too. But, eating is just swalloing for these wild water animals. They use their strong and sharp teeth to tear their prey into big pieces after clamping them down in their jaws. They swallow stones just as their prey for digestion. These stones help in grinding the food inside their stomach. Isn''t that someting fascinating! Now, beware! don''t you do the same.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile10', 3, 'A little more into the crocodile world', NULL, 'Crocodiles are cold blooded animals. They change their body temperature accoring to the environment they are in. That means it''s just like an air conditioner. If they need body warmth then they bathe in the sun. If they need to cool down, then they move into the water. These strong animals have strong sense organs too. Their acute senses makes them perfect predators. Can we see in the night? of course yes, but we need light to guide us. It''s not the same with our crocodile friend. Their night vision is very good. So are their senses of smell and hearing. With all these strong features, crocodiles live from 50 to 60 years and sometimes to 80 years. Great life of a great animal.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile11', 3, 'Amazing facts of the Crocodile', NULL, 'Crocodile tears - Have you heard this somewhere? Crocodiles produce tears when they eat. No, its not for the dead prey, but its because they swallow too much air which gets in touch with the tear glands and hence the tears roll out. 
Crocodiles have one of the strongest bites in the whole of animal world. Hence, the water monster.
Did you know that, crocodiles are very strong swimmers. They can swim at a speed of 25 miles per hour. And this ability is because of its strong tail. Wow, what a strong tail indeed!
Crocodiles are often seen with their jaws wide open. Any guess! The fact is they open their jaws to cool themselves because they don''t have sweat glands.
A female crocodile lays 20 to 80 eggs and takes care of them for 3 months. and this is truly amazing.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile12', 0, 'Crocodiles are carnivorous animals.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile12', 1, 1, 'Yes');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile12', 0, 1, 'no');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile15', 0, 'Crocodile is a _____________ blooded animal.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile15', 1, 1, 'cold');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile15', 0, 1, 'warm');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile15', 0, 2, 'hot');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile19', 0, 'Identify the body parts and match it with their names', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile19', 1, 1, 'webbed feet');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile19', 1, 2, 'assets/topic/crocfeet_30.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile19', 1, 3, 'teeth');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile19', 1, 4, 'assets/topic/crocTeeth_32.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile19', 1, 5, 'tail');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile19', 1, 6, 'assets/topic/crocTail_34.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile19', 1, 7, 'eyes');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile19', 1, 8, 'assets/topic/crocEye_36.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile19', 1, 9, 'snout');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile19', 1, 10, 'assets/topic/crocSnout_38.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile30', 0, 'Crocodiles''s can live upto 1000 years.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile30', 1, 1, 'False');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile30', 0, 1, 'True');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile33', 0, 'crocodile  _______', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile33', 1, 1, 'tears');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile33', 0, 1, 'cakes');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile33', 0, 2, 'mistakes');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile37', 0, 'Bullet   ___________', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile37', 1, 1, 'proof');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile37', 0, 1, 'jacket');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile37', 0, 2, 'machine');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile41', 0, 'Sharp ___________', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile41', 1, 1, 'teeth');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile41', 0, 1, 'tail');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile41', 0, 2, 'eyes');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion', 2, 'Lion', 'assets/topic/lion.svg', 'The king of the forest. The big cat. The king of the beasts. The lion is known throughout the history for its courage and strength. This majestic animal is considered to be the second biggest cat in the world. Its truly a facinating creature.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion3', 1, 'The Majestic animal', 'assets/topic/lion-150173__340.png', 'Use different colours of your choice to make the lion colourful.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion4', 1, 'Look what I have drawn', 'assets/topic/lion-2521451__340.png', 'Using the drawing tools draw, color and create the picture of a lion', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion5', 1, 'Pride of lions', 'assets/topic/pexels-photo-1201477.jpeg', 'Using the images and the drawing tools create a group of lions', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion6', 1, 'Magic in no time', 'assets/topic/lion-150173__340.png', 'Add mane using the drawing tools to the face of the lioness and make it a lion.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion7', 3, 'History of the lion', 'assets/topic/pexels-photo-627667.jpeg', 'The majestic king of the forest once roamed most of Africa and parts of Asia and Europe. Today they are found in sub - saharan Africa. Very small population of Asian lions survive in India. The lions evolved between 1 million and 800,000 years ago in Africa. Lions are constantly being reduced but they are still not endangered. Hope our king of the forest will always stay and grow in numbers.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion8', 3, 'Lets understand the body craft', 'assets/topic/pride-48373__340.png', 'The amazing king is a muscular, deep chested cat. It has a short rounded head, a reduced neck and round ears. There''s a hairy tuff at the end of the tail. The king is larger than a queen. The king weighs from 150 to 250 kgs. When it comes to the length, the lion is larger than the lioness. The queen weighs from 120 to 182 kgs. A male lion has a mane. The majestic creature has a short life span. They live approximately  15 years. But, the lions in captive will go on to live for 30 years too.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion9', 3, 'Lions and their Hunting', 'pexels-photo-627667', 'The male lions take care of their area. The whole of their area includes 100 square miles of grasslands or open woodlands. These animals mark the area with urine. They roar to scare the other animals who try to walk into their area. They even chase the other animals from their place. Female lions are called as lioness. The lioness hunts for the group of lions. The group of lions is called as a pride. The female lions work together to hunt their prey. The pride enjoys their prey equally. They share with their young ones. The youngones are called as cubs. The cubs do not help to hunt untill they are a 1 year old. The lions are known for their team work. They are the only cats that stay in pride.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion10', 3, 'Lions and the Cats', 'assets/topic/lions-1132745_960_720.jpg', 'Lions are called to be big cats. These big cats have most of their behaviour similar to the pet cats at home. Lions are very good climbers. They are often seen up in trees checking the area for prey. Lions are awake only for 3 to 4 hours a day. Can you imagine? they spend their whole day in sleeping. Wow! that''s strange, but it''s true. They sleep in lots of unusual positions. They sleep on their back with their paws in air. Isn''t these habits similar to that of a pet cat?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion11', 3, 'Interesting facts about the Lion king', 'assets/topic/Unknown.jpg', 'Each individual lion has a unique pattern of whiskers on its muzzle. Imagine the number of patterns!
A lion''s roar can be heard upto 3 miles away. Isn''t that too loud! Scary scream
The heaviest lion on record weighed around 375 kgs. That is too heavy. 
A female lion eats 5 kgs of meat everyday. A male lion eats 7 kgs of meat everyday. Now that is called a heavy diet.
Lioness are caring mothers. They even take care of the neglected cubs.
Lions will kill anything from mice, lizards to wild beasts. It''s truly a survivor.
After carrying the youngones in womb for 105 days, a lioness gives birth to 2 to 3 cubs.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion12', 0, 'Select the lion''s food', NULL, NULL, 'many');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion12', 1, 1, 'assets/topic/deer-2264354__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion12', 1, 2, 'assets/topic/animals-1782431__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion12', 1, 3, 'assets/topic/rabit-2808713_960_720.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion12', 1, 4, 'assets/topic/zebra-1141302_960_720.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion12', 0, 1, 'assets/topic/still-life-562357_960_720.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion12', 0, 2, 'assets/topic/basket-605148__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion12', 0, 3, 'assets/topic/popcorn-1554145__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion12', 0, 4, 'assets/topic/cake-1227842__340.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion21', 0, 'The female lions hunts the ________.', 'assets/topic/lion-693059__340.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion21', 1, 1, 'prey');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion21', 0, 1, 'games');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion21', 0, 2, 'water');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion25', 0, 'Identify the body parts and match it with their names', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion25', 1, 1, 'lion''s mane');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion25', 1, 2, 'assets/topic/lion-1281302_960_720.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion25', 1, 3, 'claws');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion25', 1, 4, 'assets/topic/stock-photo--lion-s-paw-with-claws-450899818.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion25', 1, 5, 'tail');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion25', 1, 6, 'assets/topic/lion-tail-857949__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion25', 1, 7, 'roar');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion25', 1, 8, 'assets/topic/lion-2635913__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion25', 1, 9, 'cub');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion25', 1, 10, 'assets/topic/lion-2990717__340.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion36', 0, 'A lion hunts for the pride.', 'assets/topic/lion-3221778__340.png', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion36', 1, 1, 'assets/topic/lion-565820_960_720.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion36', 0, 1, 'True');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion39', 0, 'Lion''s   _______', 'assets/topic/africa-17344_960_720.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion39', 1, 1, 'mane');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion39', 0, 1, 'assets/topic/lions-1660044_960_720.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion39', 0, 2, 'shirt');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion43', 0, 'Roaring   ___________', 'assets/topic/lion-3012515__340.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion43', 1, 1, 'lion');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion43', 0, 1, 'assets/topic/raven-2162966__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion43', 0, 2, 'assets/topic/ant-564617_960_720.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion47', 0, 'caring ___________', 'assets/topic/lion-608251__340.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion47', 1, 1, 'assets/topic/lion-762698__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion47', 0, 1, 'claws');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion47', 0, 2, 'whiskers');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant', 2, 'Elephant', 'assets/topic/elephant.svg', 'Have you ever stood beside an elephant? They are so big and beautiful with one long trunk, two tusks and 4 heavy legs. Wow! it''s such an amazing animal. Elephant is considered to be the world''s largest land mammal.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant3', 1, 'Elephant recreated', 'assets/topic/elephant-3292752__340.jpg', 'Choose the images and recreate your elephant.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant13', 1, 'A stay for my Elephant', NULL, 'Create a stay for your elephant by planting the trees of your choice.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant13', 2, 1, 'assets/topic/elephant-family-amboseli-260nw-305729312.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant20', 1, 'A rainbow Elephant', 'assets/topic/elephant-2403410__340.png', 'Use different colors of your choice to color the elephant in the picture.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant20', 2, 1, 'assets/topic/elephant-1316325__340.png');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant22', 1, 'Cuteness Overloaded', NULL, 'Using the drawing tools, add ornaments; chain, crown, dress, earrings, bangles, footware etc for the given picture of the elephant.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant22', 2, 1, 'assets/topic/baby-elephants-playing-260nw-75308080.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant24', 3, 'Let''s know about the Elephant', 'assets/topic/elephant-family-amboseli-260nw-305729312.jpg', 'Being the world''s largest land mammal, elephants continue to be in the top list. Elephants weigh upto 6000 kgs and measures upto 14 ft in height. Give a minute to just imagine the elephant.... that''s really big! Elephants have a skillful trunk which does all its important work. It has two really big ears and two curved tusks. This huge animal friend has a small tail which is as long as 1.3 metres. The life span of an African elephant is 60 to 70 years. The life span of an Asian elephant is 48 years.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant25', 3, 'Let''s ride into their senses', 'assets/topic/elephant-111695_960_720.jpg', 'Elephants use their trunk for smelling, breathing, detecting vibrations, caressing their youngones, sucking up water and grasping objects. Isn''t that amazing! Similar to their trunk their ears also serve many purpose. Elephants use their ears to communicate visually. Flapping their ears can either show aggression or joy. One elephant can hear the call of another elephant to 4 kms away. These pretty creatures havea keen sense of smell. Elephants connect to each other more often with a sense of touch. They use all parts of their body to interact with one another. But when it comes to eyes, they have a moderate visionary.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant26', 3, 'Trying to know about their habitat', 'assets/topic/female-314976__340.jpg', 'The female elephants are called as cows. The male elephants are called as bulls. The female elephants live in family groups with their young ones. The male elephants tend to roam on their own. Elephants have longer pregnancy than any other animals. The young ones are in the womb for almost 22 months. At birth baby elephants weigh some 100 kgs and stand 3 feet tall. There are two types of elephants. The African elephant and the Asian elephant. The African elephants are larger in size compared to Asian elephants.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant27', 3, 'A little knowledge about the tusk', 'assets/topic/nature-1284285_960_720.jpg', 'A tusk in the elephant is it''s big teeth. One third of the tusk is actually hidden from view.  It is covered deep inside it''s head. Elephant''s tusks never stop growing. Elephants use their tusk to dig, strip the barks of the tree and move the things out of their way. Most of the times they use them as weapons to scare their predators. Elephants tusk is known as Ivory. And it is very expensive in the market. Tusks have been the main reason behind elephant hunting. Now, this is not fair. If elephant killing continues, very soon elephant will become extinct.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant28', 3, 'Fascinating facts about the Elephant', 'assets/topic/elephant-839098_960_720.jpg', 'The oldest known elephant lived for 86 years. The average life span of an elephant is 50 to 70 years.
Did you know that elephants can''t jump, trot or gallop? It can either run or walk.
Elephants are similar to human when it comes to emotions. They display grief, compassion, self-awareness, play, art and music. Isn''t this an amazing fact!
Elephants follow a structured lifestyle. Female elephants live their entire life in groups made up of mothers, aunts, sisters, daughters and grandmothers. Male elephants prefer to live the life of a bachelor. Does this remind of a human lifestyle?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant29', 0, 'Elephant is the world''s ___________ animal.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant29', 1, 1, 'largest');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant29', 0, 1, 'smallest');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant29', 0, 2, 'tallest');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant33', 0, 'Elephants can __________ and __________.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant33', 1, 1, 'run, walk');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant33', 0, 1, 'trot, gallop');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant33', 0, 2, 'jump, gallop');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant37', 0, 'How much does a baby elephant weigh at it''s birth?', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant37', 1, 1, '100 kgs');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant37', 0, 1, '200 kgs');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant37', 0, 2, '500 kgs');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant41', 0, 'Identify the body parts and match it with their names', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant41', 1, 1, 'elephant''s trunk');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant41', 1, 2, 'assets/topic/african-1551762__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant41', 1, 3, 'elephant''s ear');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant41', 1, 4, 'assets/topic/elephant-2668679__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant41', 1, 5, 'elephant''s tusk');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant41', 1, 6, 'assets/topic/elephant-3292752__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant41', 1, 7, 'elephant''s tail');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant41', 1, 8, 'assets/topic/elephant-3679295__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant41', 1, 9, 'baby elephant');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant41', 1, 10, 'assets/topic/baby-elephants-playing-260nw-75308080.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant52', 0, 'The tusk of an elephant is also known as Ivory', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant52', 1, 1, 'assets/topic/africa-animal-photography-barbaric-631317.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant52', 0, 1, 'False');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant55', 0, 'long   _______', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant55', 1, 1, 'trunk');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant55', 0, 1, 'eyes');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant55', 0, 2, 'hair');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant59', 0, 'white   ___________', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant59', 1, 1, 'tusk');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant59', 0, 1, 'tail');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant59', 0, 2, 'ear');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant63', 0, 'large ___________', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant63', 1, 1, 'body');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant63', 0, 1, 'nails');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant63', 0, 2, 'eyes');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant', 2, 'African Safari Ant', NULL, 'Don''t go by the size. Size is not a matter for these safari ants. They are commonly known as driver ants and found in Africa. Although it''s not common, safari ants can kill humans. Yes, you read it right. Tiny ants can take a man''s life! and that is truly scary.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant3', 1, 'Colour the Safari Ant', 'Image of blank Safari Ant(Not available)', 'Colour the safari ants using the colours of your choice.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant4', 1, 'I can draw a Safari Ant', NULL, 'Use the drawing tools to draw the picture of a safari ant.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant5', 1, 'Column of Safari Ants', NULL, 'Use the images and create a column of safari ants', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant8', 3, 'Let''s know about the terrific insect', NULL, 'The safari ant also known as the driver ant and saifu. These are found in central and east Africa. It is also found in Asia. The word saifu is a swahili word. These insects have nomadic existance. They keep moving from one place to another. These ferocious colonies of ants keep changing the place everyday. Their search for prey involves climbing into trees and shrubs. Quiet active, arent they?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant9', 3, 'Lifecycle of the mighty ants', NULL, 'Safari ants are known to be carnivore. These ants are known to be the strongest hunter. They use their numerous number to kill the prey. Its when the food supply become short, they leave the hill and form marching columns of 50,000,000 ants. This is a true problem for the people. Specially when these columns go through homes, they are more problematic. It''s risk for the one who is unable to move from their way. Using their powerful cutting jaws, these ants attack everything in their path. It may be snakes, birds, mammals and even human beings. They are truly ferocious.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant10', 3, 'Important facts to know', NULL, 'A safari ant can travel about 20 metres in an hour. Not bad...
Safari ant is considered to be the most deadly insect in the world. They can skelentonize a human body in 4 hours.
Having a nomadic character these insects move to a new spot each day.
These tiny insects have extremely strong jaws. One can pull it into two without it releasing its hold. And, this is called as a strong hold.
A male safari ants are sometimes known as sausage flies. It is called by the name because it has a bloated stomach.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant11', 0, 'African Safari ant is also known as _______', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant11', 1, 1, 'driver ant');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant11', 0, 1, 'dragon ant');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant11', 0, 2, 'monitor ant');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant15', 0, 'A column of safari ants can travel ________ metres in an hour.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant15', 1, 1, '20');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant15', 0, 1, '100');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant15', 0, 2, '10');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant19', 0, 'What is a male safari ant called as?', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant19', 1, 1, 'sausage flies');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant19', 0, 1, 'stomach flies');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant19', 0, 2, 'burger flies');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant23', 0, 'The safari ant can skelentonize a human body in about 1 hour.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant23', 1, 1, 'False');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant23', 0, 1, 'True');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant26', 0, 'cutting   _______', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant26', 1, 1, 'jaws');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant26', 0, 1, 'eyes');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant26', 0, 2, 'antennae');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant30', 0, '___________ flies', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant30', 1, 1, 'sausage');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant30', 0, 1, 'house');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant30', 0, 2, 'deadly');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant34', 0, '_________ character', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant34', 1, 1, 'nomadic');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant34', 0, 1, 'lazy');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant34', 0, 2, 'harsh');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis', 2, 'Africanis', NULL, 'With an origin that goes back approximately 7000 years back, Africanis is one of the ancient African dog breed. Africanis is considered the dog of Africa.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis3', 1, 'My Africanis, the best dog', 'assets/topic/africanisdog_3.jpg', 'Using the images, build a kennel for your dog. Write a name on the name board and display at the kennel. Treat your pet with the bone. Add decorations using the drawing tools.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis8', 1, 'Colour me Please', 'Image of a blank Africani dog breed(Not available)', 'Using the colours ofg your choice, colour the picture of the dog.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis9', 1, 'Modified Africanis', 'Image of an African dog with missing legs, ears, tail(Not available)', 'Using the images modify the picture of the dog as desired.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis17', 1, 'Happy Family time', NULL, 'Using the images create a fun family time picture.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis22', 3, 'Admired personality of Africanis', NULL, 'Dog is always considered to be man''s best friend. This is very true when it comes to Africanis breed. Being friendly and playful in nature this dog is a perfect pet for homes. It''s playful nature makes it a good companion for kids. Apart from being playful, it is watchful and alert. Who doesn''t love to be independant. Yes, exactly like us, Africanis too loves to be independant. But, at the same time it stays obidient to its owner. However, it grows grumpy and moody as it grows old. After all, everyone have their mood swings.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis23', 3, 'The Bodycraft of an Africanis', NULL, 'Africanis have a thin built body. This helps them to be more flexible and natural in their movements. It has a well muscled body. The ribs are visible when it is healthy. Not being too tall, the Africanis have a normal height of 20 to 24 inches in height and will weigh around 25 to 45 kgs. Their coat comes in variety of colours such as black, dark brown, chocolate brown, honey, white, cream and golden merle. The cute sleek friend has a cone shaped face. Don''t you think it makes a royal look?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis24', 3, 'Lovely Characteristics of Africanis', NULL, 'Africanis is very friendly with kids. Don''t you love to have one?
The dog is highly trainable as it is very obidient to it''s master.
The dog is quiet territorial about it''s surroundings. It doesn''t like any one entering it''s boundaries. It won''t go well when it is in group. 
Having well built muscles, it has a great stamina to walk and trot for a long distance.
The dog is quiet healthy all through his life but, sometimes has a risk of contracting rabies.
Africanis is loyal and courageous in nature. There are believed to give their life for their owners. Wow! what a loyalty.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis25', 3, 'The must to be known facts about Africanis', NULL, 'Africanis is a hound. and hence it''s sleek body.
The average life span varies from 10 to 12 years. Very short life!
Bantu dog, hottentot hunting dog, zulu dog, khoikhoi dog are the other names of an Africanis.
Africanis is an intelligent dog with a friendly nature.
Africanis is a medium sized breed of dog.
Africanis is considered to be one of the best hunting dog.
Africanis have a short hair and does not need any grooming.Isn''t that easy to keep a pet Africanis?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis26', 0, 'Africanis dog breed is the origin of south ___________.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis26', 1, 1, 'Africa');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis26', 0, 1, 'america');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis26', 0, 2, 'asia');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis30', 0, 'Africanis is an _________________ dog.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis30', 1, 1, 'intelligent');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis30', 0, 1, 'lazy');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis30', 0, 2, 'ferocious');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis34', 0, 'What is the life span of an Africanis breed dog?', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis34', 1, 1, '10 to 12 years');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis34', 0, 1, '15 to 20 years');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis34', 0, 2, '5 to 10 years');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis38', 0, 'Identify the body parts and match it with their names', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis38', 1, 1, 'tail');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis38', 1, 2, 'image of an Africanis tail');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis38', 1, 3, 'ear');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis38', 1, 4, 'image of an Africanis ear');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis38', 1, 5, 'face');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis38', 1, 6, 'image of an Africanis face');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis38', 1, 7, 'legs');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis38', 1, 8, 'image of an Africanis legs');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis38', 1, 9, 'body');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis38', 1, 10, 'image of an Africanis body');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis49', 0, 'Africanis dog is also known as Bantu dog.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis49', 1, 1, 'True');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis49', 0, 1, 'False');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis52', 0, 'Sleek   _______', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis52', 1, 1, 'body');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis52', 0, 1, 'nose');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis52', 0, 2, 'hair');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis56', 0, '___________ face', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis56', 1, 1, 'cone shaped');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis56', 0, 1, 'square');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis56', 0, 2, 'broad');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis60', 0, 'Muscled __________', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis60', 1, 1, 'body');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis60', 0, 1, 'tail');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis60', 0, 2, 'eyes');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat', 2, 'Goat', NULL, 'Who does''nt recognise a stout bodied mammal with horns and cloven hooves? Yes, you are right! It’s the goat, our domestic friend. Did you even know that goats were among the first animals to be domesticated by man 11,000 years ago in the North east! Being goat''s milk one of the most popular drink world-wide, goats have always been man''s most useful animal next door.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat3', 1, 'Creating a Goat', 'image of a goat without legs, ears and tail(Image not available)', 'Using the drawing tools, draw the missing body parts of the goat.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat4', 1, 'I can draw a goat.', NULL, 'Using the drawing tools draw the picture of a goat .', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat5', 1, 'My Healthy Goat', NULL, 'Add feed for the goat using the drawing tools.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat6', 1, 'Three Billy Goats Gruff', 'images of 4 sequential story cards - The Three Billy Goats Gruff(Image not available)', 'Color the story cards "Three Billy Goats Gruff"', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat7', 3, 'The origin of the Goat', NULL, 'Goats and humans have a long and productive history together. The great goat domestication took place about 11,000 years ago in North-east. There are two types of goats and they are called as mountain goats and domestic goats. Mountain goats. Mountain goats are found in rocky mountains, typically in Alaska, Western Montana, Central Idaho, South Dakota, Colorado and Washington. Domestic goats are raised all over the world in almost all homes.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat8', 3, 'Cool Habits of the grass eater', NULL, 'Goats are very social creatures and live in small groups. The goups are called as herds. Mountain goats are more social during the winter and go solo during summer. Goats typically spend their days grazing on grasses within their home range. Mountain goats will dig 1 to 1 inch depressions in the ground to sleep, rest and to bathe in dust. Goats are herbivorous, which means they eat only vegetation. Mountain goats eat mosses and plants. Domestic goats eat thrash, house plants are just anything lying around.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat9', 3, 'Let''s know the goat family', NULL, 'A male goat is called a buck or a billy. The female goat is called a nanny or doe. The baby goat is called a kid. The female goat carries the baby in its womb for a period of 150 to 180 days before giving birth. The baby goats are very active and quick. Within minutes of being born, kids are up and walking. The kids are adults when they are 30 months old.  There are around 200 breeds of domestic goats. The domestic goats weigh from 9 to 113 kgs depending upon their breed. The Mountain goats weigh from 57 to 82 kgs. Goats ahave a short life span. The mountain goats live from 9 to 12 years. The domestic goats live somewhere around 10 to 18 years. Isn''t the goat family as simple as a goat.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat10', 3, 'Interesting facts to share about the bleating friend.', NULL, 'A baby goat is called a kid. But the fact is goat giving birth is called to be "kidding".
Goats don''t have teeth in their upper jaw. Now, this is funny! can''t imagine having the same pattern in man.
Goats can climb trees and jump over 5 feet. Great strenth!
Goats bleat differ from region to region. That means the bleat of a goat in one country is different from the bleat of the goat in another country. Some identity like we humans. 
Goats do not like to get wet. They run to the shelter when its raining. But, we like to get wet and play in rain.
A goat has 4 stomachs called as rumen. This helps in proper digestion of the food. Now, this is the secret of its continuous grazing.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat11', 0, 'The bleats of a goat differ from region to region.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat11', 1, 1, 'true');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat11', 0, 1, 'false');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat14', 0, 'There are  _______ types of goats.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat14', 1, 1, 'two');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat14', 0, 1, 'five');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat14', 0, 2, 'three');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat18', 0, 'Select the items that we get from a goat.', NULL, NULL, 'many');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat18', 1, 1, 'assets/topic/goatmeat_27.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat18', 1, 2, 'assets/topic/goatwool_28.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat18', 1, 3, 'assets/topic/goatmilk_29.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat18', 0, 1, 'assets/topic/goat_eggs_30.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat18', 0, 2, 'assets/topic/Igoat_carrot_31.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat18', 0, 3, 'assets/topic/goat_beetroot_32.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat18', 0, 4, 'assets/topic/goat_potato_33.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat18', 0, 5, 'assets/topic/goat_onion_34.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat18', 0, 6, 'assets/topic/goat_cookies_35.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat28', 0, 'The goat has _________ stomachs.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat28', 1, 1, 'four');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat28', 0, 1, 'one');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat28', 0, 2, 'six');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat32', 0, 'Match the pictures to their names', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat32', 1, 1, 'Horns');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat32', 1, 2, 'assets/topic/goathorns_44.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat32', 1, 3, 'ears');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat32', 1, 4, 'goathorns_44.jpg(ears)');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat32', 1, 5, 'kid');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat32', 1, 6, 'assets/topic/goatkid_48.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat32', 1, 7, 'Nostrils');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat32', 1, 8, 'goathorns_44.jpg(nostrils)');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat32', 1, 9, 'Tail');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat32', 1, 10, 'assets/topic/goattail_52.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat43', 0, 'Goat _______', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat43', 1, 1, 'bleats');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat43', 0, 1, 'cries');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat46', 0, 'Mountain _________', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat46', 1, 1, 'goats');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat46', 0, 1, 'rats');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat49', 0, 'Four ___________', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat49', 1, 1, 'stomachs');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat49', 0, 1, 'tails');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon', 2, 'Baboon', NULL, 'Who doesn''t recognize this playful creature. Yes, you guessed it right. This is the baboon a native of Africa and Arabia. Baboon is known to be the old world monkey. Baboon is omnivore in nature. With 5 different types of baboons they are considered to be the world''s largest monkeys.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon3', 1, 'My Playful Baboon', 'assets/topic/baboon_3.jpg', 'Using the play toys, create a picture of playful baboon. Add more pictures and fun using the drawing tools.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon8', 1, 'Baboon the Rockstar', 'Image of a blank baboon(Not available under CC0)', 'Using the images and the drawing tools, create a rockstar baboon', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon13', 1, 'Baboon could be better', NULL, 'Imagine a baboon with a giraffe neck or an elephants ear or maybe with a dogs tail etc. Create a better baboon as per your imagination using the drawing tools.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon14', 1, 'Fun with the colours', 'assets/topic/baboon_3.jpg', 'Colour the picture of baboon', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon15', 3, 'Let''s peek into the baboons', NULL, 'Baboons are considered to be some of the biggest monkeys on earth. Baboons have a strong muscular body, powerful jaws and a razor sharp canine teeth. There are 5 different types of baboons. Chachma baboon, red baboon, hamadrayas baboon, olive baboon and yellow baboon. There is wide difference in size among the different types of baboons. The height varies from 20 inches to 47 inches and the weight varies from 13.6 kgs to 40.8 kgs. Baboons have a life span of 20 to 30 years in an average.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon16', 3, 'Eating Habits of the big monkeys', NULL, 'Baboons are omnivores. They eat both plants and animals. It proves that baboons can survive eating almost everything and anything. Grass is the important part of their diet. But baboons also eat pods, roots, blossoms, fruits, sap and bark of the trees. Baboons eat very small quantity of meat. antelope, fish, birds, rabbits and shelfish are their meat meal.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon17', 3, 'Let''s explore a little more about the baboons.', NULL, 'Baboons as other monkeys maintain a good social bond. They are always in troops. This troop range from 10 to 200 monkeys. the troop further has many small groups which has family made of mother, children and a male. Baboons communicate through their facial expression, sounds, posturing and gesturing. The sounds include grunts, lip-smacking, screams and alarm calls.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon18', 3, 'The amazing facts of Baboons', NULL, 'Whos doesn''t know that the big monkeys are extremely crafty and very intelligent.
Baboons are just like humans. They wake up in the morning hours, have a grooming session. Small baboons play together and together they all set off in columns in search of food. 
Baboons can walk around 6 miles a day. Isn''t that crazy!
A female baboon carries the baby in her womb for 6 months. After giving birth, the mother carries the baby everywhere with her holding onto her stomach. Isn''t she an amazing mother!
Baboons resemble humans in most of the characteristics.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon19', 0, 'Baboons are considered to be some of the ____________ monkeys on earth.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon19', 1, 1, 'biggest');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon19', 0, 1, 'smallest');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon19', 0, 2, 'tallest');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon23', 0, 'Baboons are ______________.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon23', 1, 1, 'omnivores');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon23', 0, 1, 'carnivores');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon23', 0, 2, 'herbivores');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon27', 0, 'Baboons can walk around  _____________ a day.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon27', 1, 1, '6 miles');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon27', 0, 1, '10 miles');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon27', 0, 2, '50 miles');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon31', 0, 'Identify the body parts and match it with their names', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon31', 1, 1, 'tail');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon31', 1, 2, 'assets/topic/baboontail_41.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon31', 1, 3, 'ear');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon31', 1, 4, 'assets/topic/baboonear_43.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon31', 1, 5, 'snout');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon31', 1, 6, 'assets/topic/baboonsnout_45.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon31', 1, 7, 'legs');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon31', 1, 8, 'assets/topic/baboonleg_47.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon31', 1, 9, 'eyes');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon31', 1, 10, 'assets/topic/babooneyes_49.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon42', 0, 'Baboons live in troops.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon42', 1, 1, 'True');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon42', 0, 1, 'False');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon45', 0, '_______ jaws', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon45', 1, 1, 'powerful');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon45', 0, 1, 'weak');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon45', 0, 2, 'loose');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon49', 0, 'canine ____________', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon49', 1, 1, 'teeth');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon49', 0, 1, 'tail');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon49', 0, 2, 'legs');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Baboon53', 0, 'lip-_______________', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon53', 1, 1, 'smacking');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon53', 0, 1, 'folding');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Baboon53', 0, 2, 'smacking');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba', 2, 'Black Mamba', 'assets/topic/32373010733_5809c5b197_z.jpeg', 'Black mamba is an extremely poisonous snake. These reptiles are native of Africa. In fact black mamba is considered to be the longest poisonous snake in the whole of African continent.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba3', 1, 'Look, what I have drawn!', NULL, 'Using the drawing tools draw a black mamba.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba4', 1, 'Colour me Please', 'assets/topic/snake-2479740_960_720.jpeg', 'Using the colours of your choice, colour the picture of mamba', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba5', 1, 'My James Bond Mamba', 'assets/topic/14707823092_fc246dc441_b.jpeg', 'Using the drawing tools, draw legs and hands to mamba. Add other details to make a James bond Mamba.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba10', 3, 'All About Black Mamba', 'assets/topic/4152356336_7a86cd8d2c_z.jpeg', 'Black mambas are considered to be the worlds deadliest snake. These creatures are very fast, nervous, highly poisonous and very aggressive. They have a record of numerous human death. It is recorded that nearly 20,000 people die from black mambas bite in Africa. Black mambas are also known as black mouthed mamba, southern brown mamba or swart mamba. Black mambas are actually brownish in colour. They have their name because of the colour of inside of their mouth which is ink black.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba11', 3, 'Unusual Behaviour of the deadliest mamba', 'assets/topic/16326192408_607190ed65_z.jpg', 'Can you believe? Black mambas are shy in nature. They always seek to escape whenever they are face to face with other creatures. But when they are cornered they will open their mouth and hiss. sometimes with one third of their body off the ground they attack. The mambas will strike not once but repeatedly. In early days the black mamba bite was sure of death, but now their is a vaccine which can prevent the death.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba12', 3, 'The Family Line', 'assets/topic/black_mamba_1_by_8twilightangel8_d2ogovt-fullview.jpg', 'The female black mamba will lay eggs in late spring or early summer. The female will lay between 10 to 25 eggs. Quiet good number. Starnge but, they lay eggs in decaying vegetation. These vegetation warms the eggs and helps in speedy hatching of the eggs. Isn''t the black mamba brainy. The mama hatchlings are around 51 centimetres long. They are greyish green in colour when they are hatched. Now this is amazing! the hatchlings are independent immediately.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba13', 3, 'Few important facts to know', 'assets/topic/16327651789_b2a9ab0859_z.jpg', 'These wild snakes have a life span of 11 years. 
Did you know that they run so fast that they can outrun humans. 
Black mamba possess a cobra like neck which they spread open when they are threatened. And now its the man who is threatened.
Black mambas use their speed only when they are cornered. So never corner a mamba.
These deadliest animals love to feast on birds and mammals.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba14', 0, 'Black mambas are also known as ____________ mamba', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba14', 1, 1, 'black mouthed');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba14', 0, 1, 'white mouthed');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba14', 0, 2, 'red mouthed');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba18', 0, 'Black mamba is the worlds ___________ snake.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba18', 1, 1, 'deadliest');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba18', 0, 1, 'lazy');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba18', 0, 2, 'ferocious');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba22', 0, 'What is the life span of a black mamba?', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba22', 1, 1, '11 years');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba22', 0, 1, '15 years');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba22', 0, 2, '20 years');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba26', 0, 'Black mambas are shy in nature.', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba26', 1, 1, 'True');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba26', 0, 1, 'False');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba29', 0, 'black   _______', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba29', 1, 1, 'mouthed');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba29', 0, 1, 'nose');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba29', 0, 2, 'hair');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba33', 0, '__________ green', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba33', 1, 1, 'greyish');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba33', 0, 1, 'reddish');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba33', 0, 2, 'pinkish');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Black Mamba37', 0, 'decaying ____________', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba37', 1, 1, 'vegetation');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba37', 0, 1, 'sand');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Black Mamba37', 0, 2, 'stones');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Animals', 2, 'Animals', NULL, NULL, NULL);
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 1, 'Zebra3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 2, 'Zebra4');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 3, 'Zebra6');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 4, 'Zebra7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 5, 'Zebra8');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 6, 'Zebra9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 7, 'Zebra10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 8, 'Zebra11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 9, 'Zebra12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 10, 'Zebra15');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 11, 'Zebra19');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 12, 'Zebra23');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 13, 'Zebra26');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 14, 'Zebra33');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 15, 'Zebra37');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 16, 'Zebra41');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 1, 'Fischer''s lovebird3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 2, 'Fischer''s lovebird4');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 3, 'Fischer''s lovebird5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 4, 'Fischer''s lovebird6');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 5, 'Fischer''s lovebird7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 6, 'Fischer''s lovebird8');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 7, 'Fischer''s lovebird9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 8, 'Fischer''s lovebird10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 9, 'Fischer''s lovebird11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 10, 'Fischer''s lovebird12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 11, 'Fischer''s lovebird16');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 12, 'Fischer''s lovebird20');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 13, 'Fischer''s lovebird31');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 14, 'Fischer''s lovebird34');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 15, 'Fischer''s lovebird37');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 16, 'Fischer''s lovebird40');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 1, 'Crocodile3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 2, 'Crocodile4');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 3, 'Crocodile5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 4, 'Crocodile6');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 5, 'Crocodile7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 6, 'Crocodile8');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 7, 'Crocodile9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 8, 'Crocodile10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 9, 'Crocodile11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 10, 'Crocodile12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 11, 'Crocodile15');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 12, 'Crocodile19');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 13, 'Crocodile30');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 14, 'Crocodile33');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 15, 'Crocodile37');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 16, 'Crocodile41');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 1, 'Lion3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 2, 'Lion4');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 3, 'Lion5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 4, 'Lion6');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 5, 'Lion7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 6, 'Lion8');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 7, 'Lion9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 8, 'Lion10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 9, 'Lion11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 10, 'Lion12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 11, 'Lion21');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 12, 'Lion25');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 13, 'Lion36');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 14, 'Lion39');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 15, 'Lion43');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 16, 'Lion47');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 1, 'Elephant3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 2, 'Elephant13');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 3, 'Elephant20');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 4, 'Elephant22');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 5, 'Elephant24');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 6, 'Elephant25');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 7, 'Elephant26');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 8, 'Elephant27');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 9, 'Elephant28');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 10, 'Elephant29');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 11, 'Elephant33');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 12, 'Elephant37');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 13, 'Elephant41');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 14, 'Elephant52');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 15, 'Elephant55');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 16, 'Elephant59');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 17, 'Elephant63');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 1, 'African Safari Ant3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 2, 'African Safari Ant4');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 3, 'African Safari Ant5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 4, 'African Safari Ant8');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 5, 'African Safari Ant9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 6, 'African Safari Ant10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 7, 'African Safari Ant11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 8, 'African Safari Ant15');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 9, 'African Safari Ant19');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 10, 'African Safari Ant23');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 11, 'African Safari Ant26');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 12, 'African Safari Ant30');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 13, 'African Safari Ant34');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 1, 'Africanis3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 2, 'Africanis8');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 3, 'Africanis9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 4, 'Africanis17');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 5, 'Africanis22');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 6, 'Africanis23');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 7, 'Africanis24');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 8, 'Africanis25');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 9, 'Africanis26');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 10, 'Africanis30');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 11, 'Africanis34');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 12, 'Africanis38');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 13, 'Africanis49');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 14, 'Africanis52');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 15, 'Africanis56');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 16, 'Africanis60');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 1, 'Goat3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 2, 'Goat4');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 3, 'Goat5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 4, 'Goat6');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 5, 'Goat7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 6, 'Goat8');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 7, 'Goat9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 8, 'Goat10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 9, 'Goat11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 10, 'Goat14');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 11, 'Goat18');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 12, 'Goat28');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 13, 'Goat32');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 14, 'Goat43');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 15, 'Goat46');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 16, 'Goat49');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 1, 'Baboon3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 2, 'Baboon8');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 3, 'Baboon13');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 4, 'Baboon14');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 5, 'Baboon15');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 6, 'Baboon16');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 7, 'Baboon17');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 8, 'Baboon18');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 9, 'Baboon19');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 10, 'Baboon23');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 11, 'Baboon27');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 12, 'Baboon31');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 13, 'Baboon42');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 14, 'Baboon45');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 15, 'Baboon49');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Baboon', 16, 'Baboon53');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 1, 'Black Mamba3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 2, 'Black Mamba4');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 3, 'Black Mamba5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 4, 'Black Mamba10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 5, 'Black Mamba11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 6, 'Black Mamba12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 7, 'Black Mamba13');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 8, 'Black Mamba14');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 9, 'Black Mamba18');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 10, 'Black Mamba22');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 11, 'Black Mamba26');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 12, 'Black Mamba29');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 13, 'Black Mamba33');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Black Mamba', 14, 'Black Mamba37');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Animals', 0, 'Zebra');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Animals', 1, 'Fischer''s lovebird');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Animals', 2, 'Crocodile');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Animals', 3, 'Lion');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Animals', 4, 'Elephant');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Animals', 5, 'African Safari Ant');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Animals', 6, 'Africanis');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Animals', 7, 'Goat');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Animals', 8, 'Baboon');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Animals', 9, 'Black Mamba');
