INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fisherman', 2, 'Fisherman', 'assets/topic/fisherman.svg', 'A fisherman or fisher is someone who catch fish and other water animals for their living or for sport.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fisherman_3', 1, 'Draw a fisherman', 'assets/topic/fisherman_bg.svg', 'Draw a fisherman catching fish', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fisherman_3', 2, 1, 'assets/topic/fisherman_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fisherman_5', 1, 'Take a picture of fisherman', 'assets/topic/fisherman_background.svg', 'Take a picture of fisherman and decorate it', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fisherman_5', 2, 1, 'assets/topic/fisherman_background.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fisherman_7', 1, 'Draw a fishing stick', 'assets/topic/fishing_bg.svg', 'Draw a fishing stick and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fisherman_7', 2, 1, 'assets/topic/fishing_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Engineer', 2, 'Engineer', 'assets/topic/engineer.svg', 'Engineers are people who design or build things that we use every day.
Engineering is the use of science and math to design or make things. 
People who do engineering are called engineers.', 'FFF4E1B5');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Engineer_3', 1, 'Take a picture of electrical engineer.', 'assets/topic/engineer_svg01.svg', 'Take a picture of electrical engineer and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Engineer_3', 2, 1, 'assets/topic/engineer_svg01.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Engineer_5', 1, 'Take a picture of mechanical engineer.', 'assets/topic/mech_engineer.svg', 'Take a picture of mechanical engineer and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Engineer_5', 2, 1, 'assets/topic/mech_engineer.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Engineer_7', 1, 'Take a picture of civil engineer.', 'assets/topic/civ_engineer.svg', 'Take a picture of civil engineer and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Engineer_7', 2, 1, 'assets/topic/civ_engineer.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Farmer', 2, 'Farmer.', 'assets/topic/farmer.svg', 'A farmer is  an individual who grows crops and raises animals for human use. Farmers work hard and for long hours. They work in all season and all weather conditions.', 'FFCFB5DD');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Farmer_3', 1, 'Draw a farmer.', 'assets/topic/crop_svg01.svg', 'Draw a farmer', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Farmer_3', 2, 1, 'assets/topic/crop_svg01.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Farmer_5', 1, 'Take a picture of a farmer.', 'assets/topic/agriculture-2027001.svg', 'Take a picture of a farmer and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Farmer_5', 2, 1, 'assets/topic/agriculture-2027001.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Farmer_7', 1, 'Take picture of different crops.', 'assets/topic/forest_svg02.svg', 'Take picture of five different crops and post it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Farmer_7', 2, 1, 'assets/topic/forest_svg02.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Farmer_9', 1, 'Take picture of domestic animals', 'assets/topic/bull-47873.svg', 'Take picture of three different domesticated animals for farming', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Farmer_9', 2, 1, 'assets/topic/bull-47873.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Teacher', 2, 'Teacher', 'assets/topic/teacher.svg', 'A teacher is an individual who is trained to teach children. A teacher teaches from early stage of the children to their adult stage.', 'FFB3C8FF');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Teacher_3', 1, 'Draw a teacher', 'assets/topic/teacher_svg01.svg', 'Draw teacher with black board behind her.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Teacher_3', 2, 1, 'assets/topic/teacher_svg01.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Teacher_5', 1, 'Take a picture of teacher', 'assets/topic/ground_svg02.svg', 'Take a picture of teacher and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Teacher_5', 2, 1, 'assets/topic/ground_svg02.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Teacher_7', 1, 'Take a picture of school.', 'assets/topic/school-295210.svg', 'Take a picture of school. Paint and decorate the picture', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Teacher_7', 2, 1, 'assets/topic/school-295210.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Doctor', 2, 'Doctor', 'assets/topic/doctor.svg', 'A Doctor is a person who gives treatment to sick people. The doctor prescribes the medicine for the sick people. The doctor advices precautionary measures to lead a healthy life.', 'FFCFB5DD');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Doctor_3', 1, 'Draw a doctor with a patient.', 'assets/topic/doctorPat.svg', 'Draw a doctor with a patient.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Doctor_3', 2, 1, 'assets/topic/doctorPat.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Doctor_5', 1, 'Draw a stethoscope.', 'assets/topic/stethoscope-311855.svg', 'Draw a stethoscope.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Doctor_5', 2, 1, 'assets/topic/stethoscope-311855.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Doctor_7', 1, 'Take a picture of hospital.', 'assets/topic/hospitalbuilding.svg', 'Take a picture of the hospital and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Doctor_7', 2, 1, 'assets/topic/hospitalbuilding.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Barber', 2, 'Barber', 'assets/topic/barber.svg', 'A barber is a person whose occupation is mainly to cut, dress, groom, style and shave men''s and boys'' hair.', 'FFF4E1B5');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Barber_3', 1, 'Draw a barber', 'assets/topic/barber_svg1.svg', 'Draw a barber with scissors.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Barber_3', 2, 1, 'assets/topic/barber_svg1.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Barber_5', 1, 'Take a picture of barber', 'assets/topic/barber_svg2.svg', 'Take a picture of barber and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Barber_5', 2, 1, 'assets/topic/barber_svg2.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Barber_7', 1, 'A Barber shop', 'assets/topic/barber_svg3.svg', 'Make a barber shop with customers', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Barber_7', 2, 1, 'assets/topic/barber_svg3.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Plumber', 2, 'Plumber', 'assets/topic/plumber.svg', 'A plumber is a person whose main job is to connect and repair things such as water and drainage pipes, baths and toilets.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Plumber_3', 1, 'Draw a plumber', 'assets/topic/plumbtemp_4.svg', 'Draw a plumber and paint it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Plumber_3', 2, 1, 'assets/topic/plumbtemp_4.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Plumber_5', 1, 'Take picture of plumber', 'assets/topic/plumbtemp_6.svg', 'Take a picture of plumber and decorate it', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Plumber_5', 2, 1, 'assets/topic/plumbtemp_6.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Plumber_7', 1, 'Draw a tap connected to a pipe.', 'assets/topic/plumbtemp_8.svg', 'Draw a tap connected to a pipe.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Plumber_7', 2, 1, 'assets/topic/plumbtemp_8.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Police', 2, 'Police officer', 'assets/topic/police.svg', 'A police officer is a person who is working in a police force in order to maintain peace among people.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Police_3', 1, 'Draw a police officer.', 'assets/topic/police_temp.svg', 'Draw a police officer and paint it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Police_3', 2, 1, 'assets/topic/police_temp.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Police_5', 1, 'Take a picture of a police car.', 'assets/topic/police_car.svg', 'Take a picture of a police car and record the sound of its siren.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Police_5', 2, 1, 'assets/topic/police_car.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Police_7', 1, 'Decorate the police station.', 'assets/topic/station_bg.svg', 'Decorate the police station with police dog, police car, and police.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Police_7', 2, 1, 'assets/topic/station_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('House wife', 2, 'House wife', 'assets/topic/housewife.svg', 'A house wife''s main role is to take care of her own family that includes her home, her children, and her husband mainly.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('House wife_3', 1, 'Draw a house wife.', 'assets/topic/living-room_temp_housewife.svg', 'Draw an house wife and paint it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('House wife_3', 2, 1, 'assets/topic/living-room_temp_housewife.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('House wife_5', 1, 'Take a picture of house wife.', 'assets/topic/kitchen-temp_housewife.svg', 'Take a picture of house wife and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('House wife_5', 2, 1, 'assets/topic/kitchen-temp_housewife.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('House wife_7', 1, 'Take a picture of house wife.', 'assets/topic/room-temp_housewife.svg', 'Take a picture of house wife with different activity such as, cooking, washing, playing with children, cleaning house etc.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('House wife_7', 2, 1, 'assets/topic/room-temp_housewife.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Carpenter', 2, 'Carpenter', 'assets/topic/carpenter.svg', 'A carpenter is a person who works with wood and make wooden furnitures like cots, cabinets, build houses, or do other useful things.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Carpenter_3', 1, 'Draw a carpenter', 'assets/topic/carpenTemp_4.svg', 'Draw a carpenter and paint it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Carpenter_3', 2, 1, 'assets/topic/carpenTemp_4.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Carpenter_5', 1, 'Take a picture of carpenter making chair.', 'assets/topic/carpenTemp_6.svg', 'Take a picture of carpenter making chair and decorate it..', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Carpenter_5', 2, 1, 'assets/topic/carpenTemp_6.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Carpenter_7', 1, 'Take a picture of carpenter tool.', 'assets/topic/carpenTemp_8.svg', 'Take a picture of carpenter tool and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Carpenter_7', 2, 1, 'assets/topic/carpenTemp_8.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Occupations', 2, 'Occupations', NULL, NULL, NULL);
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fisherman', 1, 'Fisherman_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fisherman', 2, 'Fisherman_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fisherman', 3, 'Fisherman_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Engineer', 1, 'Engineer_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Engineer', 2, 'Engineer_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Engineer', 3, 'Engineer_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Farmer', 1, 'Farmer_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Farmer', 2, 'Farmer_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Farmer', 3, 'Farmer_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Farmer', 4, 'Farmer_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Teacher', 1, 'Teacher_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Teacher', 2, 'Teacher_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Teacher', 3, 'Teacher_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Doctor', 1, 'Doctor_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Doctor', 2, 'Doctor_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Doctor', 3, 'Doctor_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Barber', 1, 'Barber_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Barber', 2, 'Barber_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Barber', 3, 'Barber_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Plumber', 1, 'Plumber_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Plumber', 2, 'Plumber_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Plumber', 3, 'Plumber_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Police', 1, 'Police_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Police', 2, 'Police_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Police', 3, 'Police_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('House wife', 1, 'House wife_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('House wife', 2, 'House wife_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('House wife', 3, 'House wife_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Carpenter', 1, 'Carpenter_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Carpenter', 2, 'Carpenter_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Carpenter', 3, 'Carpenter_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Occupations', 0, 'Fisherman');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Occupations', 1, 'Engineer');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Occupations', 2, 'Farmer');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Occupations', 3, 'Teacher');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Occupations', 4, 'Doctor');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Occupations', 5, 'Barber');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Occupations', 6, 'Plumber');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Occupations', 7, 'Police');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Occupations', 8, 'House wife');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Occupations', 9, 'Carpenter');
