INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw', 2, 'Auto rikshaw', 'assets/topic/Auto.svg', 'A riksha or rickshaw is a kind of vehicle that has two wheels. They were usually pulled by a man. 
Now, these rickshaws can be pulled by a bicycle or motor.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor', 2, 'Tractor', 'assets/topic/tractor.svg', 'A tractor is a strong work vehicle used for farming. It usually has one seat for the driver. Tractors can be used to pull many different tools or trailers.', 'FFF4E1B5');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat', 2, 'Boat', 'assets/topic/boat.svg', 'Can you ever imagine travelling over water? Yes, its possible by water vehicle which can easily be balanced on water. Boats come in large range of types and sizes.', 'FFB3C8FF');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane', 2, 'Airplane', 'assets/topic/plane.svg', 'Have you ever seen anything moving in air with two giant wings? It looks similar to a bird but not a bird. Yes, you have guessed it right. It is an airplane. Being the fastest means of transport, airplane is a common view in the sky quiet often.', 'FFB3C8FF');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train', 2, 'Train', 'assets/topic/train.svg', 'Who is not aware of a train? Everyone knows but, today we will learn some interesting facts about the train. Basically a train is a set of vehicles connected to each other which moves on a railway track. The vehicles in a set are called as cars or wagons.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks', 2, 'Truck', 'assets/topic/lorry.svg', 'Who hasn''t seen this vehicle in the picture? It''s a truck. A truck is a vehicle used to transport goods from one place to another place. It can be a short distance or long distance transport. And these trucks are usually powered by diesel fuel.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle', 2, 'Bicycle', 'assets/topic/cycle.svg', 'Who dont know what a bicycle is ? This is everyones favourite. And, today we are going to learn some basic and interesting facts about a bicycle.', 'FFB3C8FF');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car', 2, 'Car', 'assets/topic/car.svg', 'A car is a vehicle that has four wheels and carries small number of people. It can be used personally and also for public travelling from one place to another.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus', 2, 'Bus', 'assets/topic/bus.svg', 'A bus is a public transport that is used to commute from one place to another.  Bus is very convenient and safe way to travel.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Vehicles', 2, 'Vehicles', NULL, NULL, NULL);
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 0, 'Auto rickshaw');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 1, 'Tractor');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 2, 'Boat');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 3, 'Airplane');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 4, 'Train');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 5, 'Trucks');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 6, 'Bicycle');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 7, 'Car');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 8, 'Bus');
