INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw', 2, NULL, 'assets/topic/Auto.svg', 'A riksha or rickshaw is a kind of vehicle that has two wheels. They were usually pulled by a man. 
Now, these rickshaws can be pulled by a bicycle or motor.', 'FFCFB5DD');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_3', 1, 'Draw a rickshaw.', 'assets/topic/road_bg.svg', 'Draw a rickshaw and paint it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_3', 2, 1, 'assets/topic/road_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_5', 1, 'Take a picture of an auto rickshaw.', 'assets/topic/forest_bg.svg', 'Take a picture of an auto rickshaw and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_5', 2, 1, 'assets/topic/forest_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_7', 1, 'Make an auto rickshaw horn sound', 'assets/topic/mountain_bg.svg', 'Make the sound of an auto rickshaw horn and record it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_7', 2, 1, 'assets/topic/mountain_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_9', 3, 'Rickshaw', 'assets/topic/pulled_rikshaw2.jpg', 'The most common commutor on the road is a rickshaw. A Rickshaw was originally denoted as a two or three-wheeled passenger cart.  Now its known as a pulled rickshaw.  The rickshaw was generally pulled by one man carrying one passenger.  Over the time, cycle rickshaws, also known as pedicabs or trishaws, auto rickshaws, and electric rickshaws were invented. Can''t ignore that all these new changes have helped the tourism.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_10', 3, 'Pulled rickshaw', 'assets/topic/pulled_rikshaw.jpg', 'In the early days of invention, these pulled rickshaws created a popular form of transportation. It was also a source of employment for male laborers. But their popularity came down as cars, trains and other forms of transportation became widely available. True that it''s no more used in big cities. But the smaller towns still have the pulled rickshaws.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_11', 3, 'Auto rickshaw', 'assets/topic/auto.jpg', 'An auto rickshaw is a motorized development of the traditional pulled rickshaw or cycle rickshaw. Most of them have three wheels and do not tilt. "The auto rickshaw is a common form of urban transport.  The vehicle is used for hire and also for private use. These auto rickshaws are widely in use in many countries around the world.  India is the world''s largest auto rickshaw manufacturer. Auto rickshaws were driven using petrol and now these run on diesel. Latest invention is done where auto run by the power of elctricty known as electric rickshaws.  Solarpowered rickshaws are also coming into existance. Great technology!', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_12', 3, 'Auto rickshaw in tanzania', 'assets/topic/auto_tanzania.jpg', 'Rickshaws are locally known as "bajaji" and are a common mode of transportation in Dar es Salaam. Auto rickshaws are locally called "baby taxis" and they also run on "CNGs" meaning compressed natural gas. It is one of the most popular modes of transportion in tanzania. It is known for its size and speed that helps it to cover longer distance and move freely even in crowded places.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_13', 0, 'A cart having two wheels and pulled by
man carrying passenger is called as?', 'assets/topic/pulled_rikshaw3.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_13', 1, 1, 'Pulled rickshaw');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_13', 0, 1, 'Auto rickshaw');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_13', 0, 2, 'Bus');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_13', 0, 3, 'Train');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_18', 0, 'What are rickshaws locally known as in 
Tanzania?', 'assets/topic/auto_tanzania.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_18', 1, 1, 'Bajaji');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_18', 0, 1, 'Cab');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_18', 0, 2, 'Cycle');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_18', 0, 3, 'Bus');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_23', 0, 'Group different types of rickshaw?', 'assets/topic/different_rikshsaw.jpg', NULL, 'many');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_23', 1, 1, 'Pulled rickshaw');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_23', 1, 2, 'Auto rickshaw');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_23', 1, 3, 'Electric rickshaw');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_23', 1, 4, 'CNG rickshaws');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_23', 0, 1, 'Bus');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_23', 0, 2, 'Cab');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_30', 0, 'Auto rickshaw is also called as baby taxy.', 'assets/topic/rikshaw-2.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_30', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_30', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_33', 0, 'In the early days of invention, these pulled rickshaws created a popular form of 
transportation?', 'assets/topic/pulled_rikshaw.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_33', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_33', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_36', 0, 'The rickshaw was generally pulled by two 
men carrying one passenger.', 'assets/topic/pulled_rikshaw2.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_36', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_36', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Auto rickshaw_39', 0, 'Match the images with their name.', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_39', 1, 1, 'assets/topic/old_rikshaw.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_39', 1, 2, 'Pulled rickshaw');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_39', 1, 3, 'assets/topic/new_rikshaw.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Auto rickshaw_39', 1, 4, 'Auto rickshaw');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor', 2, 'Tractor', 'assets/topic/tractor.svg', 'A tractor is a strong work vehicle used for farming. It usually has one seat for the driver. Tractors can be used to pull many different tools or trailers.', 'FFF4E1B5');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_3', 1, 'Draw a tractor', 'assets/topic/farm_bg.svg', 'Draw and paint a tractor.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_3', 2, 1, 'assets/topic/farm_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_5', 1, 'Take a picture', 'assets/topic/forest_bg.svg', 'Take picture of a tractor and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_5', 2, 1, 'assets/topic/forest_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_7', 3, 'The farm vehicle', 'assets/topic/Tractor-on-farm.jpg', 'A tractor is a vehicle used in farming. The farm tractor is used for pulling or pushing agricultural 
machinery or trailers. It is also used for plowing, tilling, disking, harrowing, planting, and doing 
other similar tasks.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_8', 3, 'Why is tractor so important ?', 'assets/topic/Tractor_working_Farm.jpg', 'A tractor is basically a machine that provides machine power for performing agricultural tasks. Tractors can be used to pull a variety of farm equipments for plowing, planting, cultivating, fertilizing, and harvesting crops. It can also be used for pulling materials and personal transportation.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_9', 3, 'Tractors replaced human labor.', 'assets/topic/Farming-Agriculture-Tractor.jpg', 'Within the first few decades, tractor was rarely used. Later the farmers realized the benefits of 
a tractor-driven farming. There was no need for human labor when a simple machine like a 
tractor could do the job for you. This saved lot of time and money. Isn''t this a magical 
vehicle?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_10', 3, 'Initially cost was very high.', 'assets/topic/tractor-pulling-farm.jpg', 'Initially the price of a tractor was very high. In just two years of its invention, the price dropped by nearly half. The tractor was an affordable tool of agricultural machinery for almost every farmer. This is because the production increased. The requirement and the sale was high. And hence it was sold at an affordable price. It can in fact be called as a farmer''s friend.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_11', 3, 'Tractor and its equipments', 'assets/topic/tractor-farm-equipment.jpg', 'Tractor, in agriculture is used to pull equipments such as plows, cultivators, and mowers. 
It is helpful to power stationary devices such as saws and winches.  Tractors are also used to 
push snowplows and earth-moving implements. Early tractors were steam-driven and now they 
are generally powered by gasoline or diesel engines. The two main types are wheeled tractors 
and caterpillar tractors, that move on treads.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_12', 0, 'How many seats are there on a tractor?', 'assets/topic/tractor-seats.png', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_12', 1, 1, 'one');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_12', 0, 1, 'two');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_12', 0, 2, 'Three');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_12', 0, 3, 'Four');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_17', 0, 'With what were the early tractors driven by?', 'assets/topic/tractor-engine.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_17', 1, 1, 'Steam driven');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_17', 0, 1, 'Petrol driven');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_17', 0, 2, 'Diesel driven');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_17', 0, 3, 'Gasoline driven');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_22', 0, 'The farm tractor is used for ___________, __________, _____________, _____________, _____________.', 'assets/topic/Tractor-Fields.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_22', 1, 1, 'Plowing');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_22', 1, 2, 'Tilling');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_22', 1, 3, 'Disking');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_22', 1, 4, 'Harrowing');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_22', 1, 5, 'Planting');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_22', 0, 1, 'Digging');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_22', 0, 2, 'Bunking');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_30', 0, 'The most common use of the term 
"tractor" is for the vehicles used on farms.', 'assets/topic/tractor-vehicle-farm.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_30', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_30', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_33', 0, 'Todays tractor are generally powered by
diesel.', 'tractor-diesel-engine.JPG', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_33', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_33', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_36', 0, 'Tractor has two seats for drivers?', 'assets/topic/tractor_driver.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_36', 1, 1, 'False.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_36', 0, 1, 'True.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Tractor_39', 0, 'Match the images with their name.', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_39', 1, 1, 'assets/topic/tractor-plow.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_39', 1, 2, 'Plow');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_39', 1, 3, 'assets/topic/tractor_field_cultivator.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_39', 1, 4, 'Cultivator');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_39', 1, 5, 'assets/topic/tractor-mower.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Tractor_39', 1, 6, 'Mower');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat', 2, 'Boat', 'assets/topic/boat.svg', 'Can you ever imagine travelling over water? Yes, its possible by water vehicle which can easily be balanced on water. Boats come in large range of types and sizes.', 'FFCFB5DD');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_3', 1, 'Draw a boat', 'assets/topic/water_bg.svg', 'Draw a boat and paint it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_3', 2, 1, 'assets/topic/water_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_5', 1, 'Take a picture of boat', 'assets/topic/water_bg.svg', 'Take a picture of boat and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_5', 2, 1, 'assets/topic/water_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_7', 1, 'Draw a life jacket', 'assets/topic/water_bg.svg', 'Draw a man wearing life jacket.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_7', 2, 1, 'assets/topic/water_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_9', 3, 'Fun fact of boat part 1', 'assets/topic/boatDec.jpg', 'If you have ever been on a boat you know how fun it is. Boats have been around for
thousands of years and play an important role in the field of transportation. We depend on these "water-vehicles" for many things. Read on to discover all about boats. We will be exploring the history of the boat, the different types of boats and so much more. So grab your life jacket and lets dive right in.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_10', 3, 'Fun fact of boat part 2', 'assets/topic/boatart1.jpg', 'Believe it or not, the first known boat dates back around 8,000 years-ago. All praises go to the ancient egyptians to have founded it. The egyptians made the boat from the papyrus plant. These boats were long and thin and were used for short trips or fishing along the Nile.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_11', 3, 'All About the boat', 'assets/topic/boatart2.jpg', 'Who hasn''t seen a boat? True it moves on water and are considered to be the water transport. There are many types of water transport. Boat, ship, canoes, fishing boats, house boats, lighters and lifeboats are few of them. A boat is a very small vessel and can be easily carried on ship which is very huge in size. Small boats are found on inland waterways such as lakes, rivers or in protected coastal areas. You might have seen different varieties of boats. Yes, boats vary in size and shapes. That is because of the available materials or the local traditions.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_12', 3, 'What do a boat consist of?', 'assets/topic/boatart3.jpg', 'The tall pole on a sailboat is called, the mast.
The body of a boat is the hull.
The back part of a boat is called, the stern.
The front of the boat is a bow.
The right, forward-facing side of a boat is called, starboard.
The left side of a boat is the port.
A long, thin pole with a blade at one end, inserted into an water and used to row or steer a boat is called oar.
The person in charge of the boat is called, Captain.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_13', 3, 'Life Jacket', 'assets/topic/lifejacket.jpg', 'You should always wear a lifejacket in a boat even if you are a great swimmer, these specially 
designed vests will keep you floating on water if you unexpectedly fell in to water. 
And should never forget carrying it with you.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_14', 0, 'What is the incharge of the boat called?', 'assets/topic/captain.png', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_14', 1, 1, 'Captain');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_14', 0, 1, 'Sailor');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_14', 0, 2, 'Passenger');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_14', 0, 3, 'Driver');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_19', 0, 'Boat consists of:', 'assets/topic/boattype.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_19', 1, 1, 'Mast');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_19', 1, 2, 'Stern');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_19', 1, 3, 'Bow');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_19', 1, 4, 'Port');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_19', 1, 5, 'Hull');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_19', 0, 1, 'Tree');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_19', 0, 2, 'Donkey');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_27', 0, 'The body of a boat is called as hull.', 'assets/topic/boatbody.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_27', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_27', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_30', 0, 'Life jacket helps you to float on water.', 'assets/topic/lifejacketsaver.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_30', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_30', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_33', 0, 'A boat is a very big vessel.', 'assets/topic/Bigship.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_33', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_33', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Boat_36', 0, 'Match the images with their names', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_36', 1, 1, 'assets/topic/oar.png');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_36', 1, 2, 'Oar');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_36', 1, 3, 'assets/topic/boatnew.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_36', 1, 4, 'Boat');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_36', 1, 5, 'assets/topic/Redjacket.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Boat_36', 1, 6, 'Life jacket');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane', 2, 'Airplane', 'assets/topic/plane.svg', 'Have you ever seen anything moving in air with two giant wings? It looks similar to a bird but not a bird. Yes, you have guessed it right. It is an airplane. Being the fastest means of transport, airplane is a common view in the sky quiet often.', 'FFF4E1B5');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_3', 1, 'Draw an airplane', 'assets/topic/sky_bg.svg', 'Draw an airplane and paint it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_3', 2, 1, 'assets/topic/sky_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_5', 1, 'Take a picture', 'assets/topic/no_bg.svg', 'Take a picture of an airplane from gallery and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_5', 2, 1, 'assets/topic/no_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_7', 1, 'Add the parts of an airplane', 'assets/topic/plane_wings.svg', 'Add wings to the airplane', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_7', 2, 1, 'assets/topic/plane_wings.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_9', 3, 'Introduction', 'assets/topic/airplane-invention.jpg', 'Whenever we see a bird flying around we feel like fying too. Wanting to have wings and flying high in the sky, inspired man to invent airplane. Many of them tried and invented many machines but success came to wright brothers. Wright brothers invented airplane which is always remembered  to be a human wonder.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_10', 3, 'History', 'assets/topic/airplane-evolution.jpeg', 'Airplane comes in different sizes and shapes. Initially the plane could carry maximum of two people. Later airplane were developed to carry more number of people travelling  from one place to another. Travel included flying across the seas and mountains reaching far off places. The time taken to travel was too short when compared to other means of transport. Isn''t this an amazing invenstion?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_11', 3, 'Diferent types of planes', 'assets/topic/Collection_of_military_aircraft.jpg', 'Passenger plane is a vehicle used to carry passengers from one place to another. Cargo plane is a vehicle used to carry goods from one place to another in short period of time. There are fighter planes which are used in military. Some planes are designed in such a way that the plane can even land on  water.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_12', 3, 'Airports', 'assets/topic/airport.jpg', 'Airport is an aerodrome with facilities to store and maintain aircrafts. There is a complex for runways and buildings for the take-off, landing and maintenance of aircrafts and control tower. Airports have facilities for the passengers. Every big city has an airport.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_13', 3, 'Super fast plane', 'assets/topic/super-fast-planes.jpeg', 'Can u imagine going long distance within a hour or some times less than an hour? Yes, it is possible 
only with airplane.  Airplane is super powered and it uses white petrol as a fuel. Airplane reaches any place within a short period of time. It need not climb mountain or drive through a busy road. It is not required to even move on seas breaking all the barriers. The airplane flies above the bad roads, huge mountains or even seas. So now you know why it moves so fast!', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_14', 0, 'How many wings does an airplane have?', 'assets/topic/aircrafts.jpeg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_14', 1, 1, 'Two');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_14', 0, 1, 'Three');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_14', 0, 2, 'Five');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_14', 0, 3, 'one');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_19', 0, 'What is the place where people board and get down the plane called?', 'assets/topic/airport-india.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_19', 1, 1, 'Airport');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_19', 0, 1, 'Railway station');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_19', 0, 2, 'Bus stand');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_19', 0, 3, 'Fire station');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_24', 0, 'What are the different types of planes used for different purpose?', 'assets/topic/typplanes.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_24', 1, 1, 'Pasenger plane');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_24', 1, 2, 'Cargo plane');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_24', 1, 3, 'Super fast plane');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_24', 1, 4, 'Fighter plane');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_24', 1, 5, 'Personal plane');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_24', 0, 1, 'Fire plane');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_24', 0, 2, 'Water plane');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_32', 0, 'Airplane flies over the seas and oceans', 'assets/topic/airplane-over-ocean.jpeg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_32', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_32', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_35', 0, 'Airplane travells quickly in short period of time.', 'assets/topic/super-fast-planes.jpeg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_35', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_35', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_38', 0, 'Airplane rides upon mountains and hills.', 'assets/topic/airplane-over-mountain.jpeg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_38', 1, 1, 'False.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_38', 0, 1, 'True.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Airplane_41', 0, 'Match the images with their names', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_41', 1, 1, 'assets/topic/Yoke.png');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_41', 1, 2, 'Yoke');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_41', 1, 3, 'assets/topic/pilot.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_41', 1, 4, 'Pilot');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_41', 1, 5, 'assets/topic/wing.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_41', 1, 6, 'Airplane wings');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_41', 1, 7, 'assets/topic/cargo-plane.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Airplane_41', 1, 8, 'Cargo plane');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train', 2, 'Train', 'assets/topic/train.svg', 'Who is not aware of a train? Everyone knows but, today we will learn some interesting facts about the train. Basically a train is a set of vehicles connected to each other which moves on a railway track. The vehicles in a set are called as cars or wagons.', 'FFF4E1B5');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_3', 1, 'Train horn', 'assets/topic/track.svg', 'Make the running and horn sound of a train and record it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_3', 2, 1, 'assets/topic/track.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_5', 1, 'My perfect Train', 'assets/topic/track_mountain.svg', 'Join different wagons to the engine and make a perfect train.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_5', 2, 1, 'assets/topic/track_mountain.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_7', 1, 'Colourful Train', 'assets/topic/track_mountain.svg', 'Paint the train with diferent colours and decorate using different stickers.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_7', 2, 1, 'assets/topic/track_mountain.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_9', 3, 'Facts about a train', 'assets/topic/train_at_Station.jpg', 'A place where a train stops to let people get on and off is called a railway station. Hope you all have seen it!
Early trains used horse power and ran on wooden or iron tracks.
Did you know that the first steam trains were built in England!
There is a railway engine that pulls the cars along the track. 
Some trains look like a special bus that can only drive on rails. 
Trains are used to carry people, as well as cargo, such as fuel, imported/exported goods, and so on.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_10', 3, 'Goods train', 'assets/topic/goods-train.jpg', 'Goods train have goods cars or goods wagons to carry goods from one place to another. Some goods wagons are closed or opened depending upon cargo transported from one place to another and also we have special wagon so they can carry special cargo.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_11', 3, 'Pasenger train', 'assets/topic/passenger-train.jpg', 'Passenger trains have passenger cars or coaches made so that people can sit on them and ride from one train stop to another which is called as train staion. Passenger trains are usually very comfortable for travelling from one place to another. There are long distance passenger train and also short distance. And in todays world we see fast moving passenger train, called as bullet train. These train runs on speacial tracks.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_12', 0, 'Where does the train run ?', 'assets/topic/train on tracks.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_12', 1, 1, 'Railway track');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_12', 0, 1, 'Running Track');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_12', 0, 2, 'Bus Track');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_12', 0, 3, 'Wagon track');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_17', 0, 'What is the name of the place where people get on and off the train?', 'assets/topic/train-railway-station.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_17', 1, 1, 'Railway station');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_17', 0, 1, 'Bus station');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_17', 0, 2, 'Car station');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_17', 0, 3, 'Bike station');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_22', 0, 'Select the items related to a train', 'assets/topic/train-parts.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_22', 1, 1, 'Wagon');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_22', 1, 2, 'Engine');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_22', 1, 3, 'Railway track');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_22', 1, 4, 'railway station');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_22', 0, 1, 'Sand');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_22', 0, 2, 'mountain');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_29', 0, 'People travel through passenger train.', 'assets/topic/Train_Interior.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_29', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_29', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_32', 0, 'Cargo is transported in a passenger train.', 'train-cargo.JPG', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_32', 1, 1, 'False.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_32', 0, 1, 'True.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_35', 0, 'Early trains used horse power and ran on 
wooden or iron tracks.', 'assets/topic/train-horsepower.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_35', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_35', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Train_38', 0, 'Match the images with their names', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_38', 1, 1, 'assets/topic/Train_front.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_38', 1, 2, 'Front engine of train');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_38', 1, 3, 'assets/topic/railway_station.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_38', 1, 4, 'Railway station');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_38', 1, 5, 'assets/topic/railway_track.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Train_38', 1, 6, 'Railway track');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks', 2, 'Truck', 'assets/topic/lorry.svg', 'Who hasn''t seen this vehicle in the picture? It''s a truck. A truck is a vehicle used to transport goods from one place to another place. It can be a short distance or long distance transport. And these trucks are usually powered by diesel fuel.', 'FFF4E1B5');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_3', 1, 'I can draw a truck', 'assets/topic/road_bg.svg', 'Draw a truck using the drawing tools.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_3', 2, 1, 'assets/topic/road_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_5', 1, 'Add parts of the truck', 'assets/topic/truck_tire.svg', 'Add tiers to truck', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_5', 2, 1, 'assets/topic/truck_tire.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_7', 1, 'Loaded Truck', 'assets/topic/mountain_bg.svg', 'Load the truck with any of these stones,mud or sand.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_7', 2, 1, 'assets/topic/mountain_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_9', 1, 'Road train', 'assets/topic/farm_bg.svg', 'Make a road train by adding trailers.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_9', 2, 1, 'assets/topic/farm_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_11', 1, 'Take a picture', 'assets/topic/forest_bg.svg', 'Take picture of the truck and decorate it', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_11', 2, 1, 'assets/topic/forest_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_13', 3, 'What is a truck?', 'assets/topic/trainloaded.jpg', 'Truck is a heavy road vehicle which comes in different sizes and shapes.  These trucks are used as per the requirement of goods that has to be transported from one place to another. It was named truck because of its heavy duty performance.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_14', 3, 'Types of Trucks', 'assets/topic/trucktype.png', 'There are different types of trucks based on the requirement. The light trucks are the trucks whose size is similar to a car. They are usually owned by individual and also small companies. Medium trucks are heavier than light trucks but lighter than heavier trucks that run on road. These trucks are mainly used for local delivery and public service such as garbage trucks. Heavy trucks are heaviest truck that run on the road. They are also known as lorries. Often heavy trucks pull trailers. Truck drivers are called truckers, teamster, driver or a truckie.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_15', 3, 'Australian truck', 'assets/topic/austtruck.jpg', 'Can you guess which part of the world has the largest truck? And just imagine how it looks? The largest truck is found in Australia and it is very different from any other trucks. Actually these trucks are named as Australian train truck. Huge number of trailers are attached to truck engine. This resembles a train and looks like a train on the road. Isn''t these trucks awesome.  Yes, it is really a wonderful invention road train.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_16', 3, 'Toy truck', 'assets/topic/toytruck.jpg', 'Who doesn''t love to play with a toy truck. It may be children are adults, everyone love playing with trucks. There are a lot of toy making companies that manufactures different types of toy trucks. Do you know how to play with a toy truck? yes, it depends on your imagination. Filling and refilling the sand, mud and stones, loading and unloading the small toys etc. Now, let go your imaginations and have a fun filled truck play.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_17', 0, 'Trucks are also known as_________.', 'assets/topic/lorryimg.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_17', 1, 1, 'Lorry');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_17', 0, 1, 'Airplane');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_17', 0, 2, 'Bus');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_17', 0, 3, 'Ship');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_22', 0, 'Where we can see a road train?', 'assets/topic/semitrailer.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_22', 1, 1, 'Australia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_22', 0, 1, 'Russia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_22', 0, 2, 'Canada');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_22', 0, 3, 'China');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_27', 0, 'Light truck are similar to size of a _______.', 'assets/topic/lighttruck.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_27', 1, 1, 'Car');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_27', 0, 1, 'Train');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_27', 0, 2, 'Airplane');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_27', 0, 3, 'Bicycle');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_32', 0, 'Australian truck is called as a road train.', 'assets/topic/austtruck.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_32', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_32', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_35', 0, 'Children are attracted to the toy trucks.', 'assets/topic/toytruck.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_35', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_35', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_38', 0, 'Trucks do not come in various shapes 
and sizes.', 'assets/topic/trucktype.png', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_38', 1, 1, 'False.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_38', 0, 1, 'True.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Trucks_41', 0, 'Match the images with relating 
names that suits bests.', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_41', 1, 1, 'assets/topic/toymini.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_41', 1, 2, 'children');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_41', 1, 3, 'assets/topic/trainloaded.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_41', 1, 4, 'Road train');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_41', 1, 5, 'assets/topic/deliverytruck.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Trucks_41', 1, 6, 'Local delivery');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle', 2, 'Bicycle', 'assets/topic/cycle.svg', 'Who dont know what a bicycle is ? This is everyones favourite. And, today we are going to learn some basic and interesting facts about a bicycle.', 'FFB3C8FF');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_3', 1, 'Cycle horn', 'assets/topic/mountain_bg.svg', 'Make a sound of the cycle horn and record it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_3', 2, 1, 'assets/topic/mountain_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_5', 1, 'Colouring Fun', 'assets/topic/road_bg.svg', 'Draw a cycle and color it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_5', 2, 1, 'assets/topic/road_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_7', 1, 'Picture of cycle', 'assets/topic/forest_bg.svg', 'Click a picture of a cycle and decorate it.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_7', 2, 1, 'assets/topic/forest_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_9', 3, 'About', 'assets/topic/cycle-hero.jpg', 'A bicycle also called as cycle is a human powered, pedal driven vehicle.  It has two wheels attched to the frame one behind the other. A bicycle rider is called cyclist or bicyclist. Were you aware that bicycles were first introduced in Europe? Later, it was spread to all other parts of the world. Bicycle have been used by children and elders and also for many public services such as courier services, daily needs supply etc.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_10', 3, 'Bicycle used for public and commodity 
transportation', 'assets/topic/woman-cycle.jpg', 'In many countries people still use bicycle for public and commodity transportation. Things are transported by attaching a carriage to the bicycle. And hence it becomes three wheeled bicycle. Normaly maximum people who can sit on a bicycle is two and a carrier is provided to carry things. It is most effecient and widely used vehicle for moving from one place to another and does not need any fuel to run it. Fuel free vehicle is affordable even by the common man.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_11', 3, 'Uses', 'assets/topic/cycle-transport.jpg', 'From the beginning till day, bicycles have been and are employed for many uses. In a good 
and profitable way, bicycles are used for transportation. It can be used as a ''work horse'' used by 
mail carriers, police, messengers, public transportation and general delivery services.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_12', 0, 'How many wheels does a cycle with carriage consists of?', 'assets/topic/cycle-transport2.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_12', 1, 1, 'Three');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_12', 0, 1, 'Four');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_12', 0, 2, 'Two');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_12', 0, 3, 'One');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_17', 0, 'Bicycle is basically  ____________.', 'assets/topic/cycle_police.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_17', 1, 1, 'Human powered');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_17', 0, 1, 'Coal powered');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_17', 0, 2, 'Diesel powered');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_17', 0, 3, 'Steam powered');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_22', 0, 'Bicycle is used by ________________.', 'assets/topic/bicycle-bike.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_22', 1, 1, 'Mail carriers');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_22', 1, 2, 'Police');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_22', 1, 3, 'Postman');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_22', 1, 4, 'Public transportation');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_22', 1, 5, 'Personal use');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_22', 0, 1, 'Train driver');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_22', 0, 2, 'Bus driver');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_30', 0, 'Cycle is also known as a work horse.', 'assets/topic/bicycle_ride.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_30', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_30', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_33', 0, 'Bicycles were first introduced in Europe.', 'assets/topic/cycle-hero.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_33', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_33', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_36', 0, 'Bicycles are only used for personal use.', 'assets/topic/bicycles1.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_36', 1, 1, 'False.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_36', 0, 1, 'True.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bicycle_39', 0, 'Match the images with their names.', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_39', 1, 1, 'assets/topic/bicycle-saddle.png');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_39', 1, 2, 'Cycle seat');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_39', 1, 3, 'assets/topic/bell-bicycle.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_39', 1, 4, 'cycle bell');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_39', 1, 5, 'assets/topic/cycle-transport.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bicycle_39', 1, 6, 'Cycle carriage');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car', 2, 'Car', 'assets/topic/car.svg', 'A car is a vehicle that has four wheels and carries small number of people. It can be used personally and also for public travelling from one place to another.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_3', 1, 'I can a draw a car', 'assets/topic/forest_bg.svg', 'Draw a car using the drawing tools', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_3', 2, 1, 'assets/topic/forest_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_5', 1, 'My Colourful Car', 'assets/topic/road_bg.svg', 'Paint the car using the colours of your choice', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_5', 2, 1, 'assets/topic/road_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_7', 1, 'How loud is your car horn?', 'assets/topic/mountain_bg.svg', 'Make a car horn sound.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_7', 2, 1, 'assets/topic/mountain_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_9', 3, 'Types of cars', 'assets/topic/multicar.jpg', 'As we all know, there are two types of cars. When we mention two types it''s not models. Because there are many varieties of models. But when it comes to types one is the personally used car which we own it and other is public transportation car. Taxies and cabs which run on the road are listed under public transport.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_10', 3, 'History part 1', 'assets/topic/carOld.jpg', 'Can you imagine! the very first moving vehicle was a machine that had only three wheels and 
was drawn by steam power. And it was first built in France. But these cars were not so effective. The reason being, the machine was very heavy which made the vehicle move very slow.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_12', 3, 'Safety measures', 'assets/topic/seatbelt.jpg', 'As we all know, cars are vehicles that move very fast. It is important that we should buckle up seat belt for safety purpose. It''s not the person at the driving seat but everyone in the car should use the seat belt. Following the safety measures and traffic rules helps us in avoiding the road accidents.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_13', 0, 'How many wheels do cars have?', 'assets/topic/bottomcar.jpg', 'Quiz', 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_13', 1, 1, 'four');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_13', 0, 1, 'two');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_13', 0, 2, 'one');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_13', 0, 3, 'five');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_18', 0, 'What is a public transportation car 
called as?', 'assets/topic/taxi.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_18', 1, 1, 'Taxi');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_18', 0, 1, 'Maggie');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_18', 0, 2, 'Airplane');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_18', 0, 3, 'Plant');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_23', 0, 'Rearrange the  cars invented in order', 'assets/topic/oldtonew.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_23', 1, 1, 'Steam powered car');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_23', 1, 2, 'Electric car');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_23', 1, 3, 'Petrol run car');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_23', 1, 4, 'Diesel run car');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_23', 1, 5, 'solar powered car');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_29', 0, 'Solar powered car uses solar energy.', 'assets/topic/solarcar.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_29', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_29', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_32', 0, 'There are no seat belts in a car.', 'assets/topic/car.png', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_32', 1, 1, 'False.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_32', 0, 1, 'True.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_35', 0, 'The very first moving vehicle was a
machine that had only three wheels.', 'assets/topic/4wheel.png', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_35', 1, 1, 'True.');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_35', 0, 1, 'False.');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Car_38', 0, 'Match the images with their names.', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_38', 1, 1, 'assets/topic/seat-cushion.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_38', 1, 2, 'assets/topic/carseatbelt.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_38', 1, 3, 'assets/topic/Wing_mirror.jpeg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_38', 1, 4, 'assets/topic/CRV_side_mirror.jpeg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_38', 1, 5, 'assets/topic/bmw-i8-car-steering-wheel.jpeg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Car_38', 1, 6, 'assets/topic/Driver_free_car.jpeg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus', 2, 'Bus', 'assets/topic/bus.svg', 'A bus is a public transport that is used to commute from one place to another.  Bus is very convenient and safe way to travel.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_3', 1, 'I can a draw a bus', 'assets/topic/road_bg.svg', 'Draw a Bus.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_3', 2, 1, 'assets/topic/road_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_5', 1, 'Add parts of the bus', 'assets/topic/bus_tire.svg', 'Add tires to the bus.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_5', 2, 1, 'assets/topic/bus_tire.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_7', 1, 'Paint', 'assets/topic/road_bg.svg', 'Paint the bus using three to four colours of your choice.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_7', 2, 1, 'assets/topic/road_bg.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_9', 3, 'About', 'assets/topic/aboutbus.jpg', 'A bus is a large wheeled vehicle meant to carry many people along with a driver. It is larger than a car. The name ''bus'' is a shortened version of ''omnibus'', which means "for everyone". Buses are an important means of public transport in places all over the world. Many people who do not have cars or other small vehicles use buses to commute around.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_10', 3, 'History of the bus', 'assets/topic/historybus.jpg', 'Can you imagine! the very first bus was driven by horse. Yes, your guess is correct. Horse was the first driver. Isn''t it funny!. People rode on the roof top too. Wow! that gave them the full view of the town. Slowly horses were replaced by steam-engine and electric trolley buses . It was all fun and to make it more easy and fun we have now the new version of buses, which run with diesel. It''s more safe, fun, easy and of course less expensive. The best way to travel around the town and have fun. Isn''t the story of bus interesting?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_11', 3, 'Yellow bus', 'assets/topic/yellowbus.jpg', 'Have you ever wondered why the school bus is yellow? These facts may surprise you. Yellow is an eye catching colour. In fact, studies show that people notice the color yellow faster than any other other colours. The colour yellow is easier to detect in dim light or bad weather. Because of these reasons, all the school buses across the world is yellow.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_12', 3, 'Why are there no seat belts?', 'assets/topic/busseat.jpg', 'You are probably always told by a car driver to "buckle up!" So why then these buses have no seat belts? Have you ever given a thought? It''s because seat belts don''t work the same way in buses as they do cars. The closley spaced bus seats function as seat belts. They prevent travellers from being thrown around. Now, you know that they are safe even without the belt.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_13', 0, 'What is the colour of a school bus?', 'assets/topic/yellowbustoy.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_13', 1, 1, 'yellow');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_13', 0, 1, 'green');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_13', 0, 2, 'violet');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_13', 0, 3, 'pink');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_18', 0, 'Select the different type of buses?', 'assets/topic/differentbusses.jpg', NULL, 'many');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_18', 1, 1, 'Horse drawn bus');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_18', 1, 2, 'Steam engine bus');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_18', 1, 3, 'Electric trolley bus');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_18', 1, 4, 'Diesel run bus');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_18', 0, 1, 'Airplane');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_18', 0, 2, 'Train');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_25', 0, 'Select the buses invented in order?', 'assets/topic/busorder.jpg', NULL, 'many');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_25', 1, 1, 'Horse drawn bus');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_25', 1, 2, 'Steam engine bus');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_25', 1, 3, 'Electric trolley bus');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_25', 1, 4, 'Diesel run bus');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_25', 1, 5, 'Double decker bus');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_31', 0, 'People rode on roof tops of horse drawn bus.', 'assets/topic/horsebus.png', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_31', 1, 1, 'True');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_31', 0, 1, 'False');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_34', 0, 'The color yellow is easier to detect in dim light or bad weather?', 'assets/topic/businsnow.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_34', 1, 1, 'True');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_34', 0, 1, 'False');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_37', 0, 'There are seat belts in the bus.', 'assets/topic/busseat.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_37', 1, 1, 'False');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_37', 0, 1, 'True');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Bus_40', 0, 'Match the images to their names', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_40', 1, 1, 'assets/topic/historybus.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_40', 1, 2, 'bus');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_40', 1, 3, 'assets/topic/bussteering.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_40', 1, 4, 'steering');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_40', 1, 5, 'assets/topic/buswheel.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Bus_40', 1, 6, 'tire');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Vehicles', 2, 'Vehicles', NULL, NULL, NULL);
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 1, 'Auto rickshaw_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 2, 'Auto rickshaw_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 3, 'Auto rickshaw_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 4, 'Auto rickshaw_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 5, 'Auto rickshaw_10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 6, 'Auto rickshaw_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 7, 'Auto rickshaw_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 8, 'Auto rickshaw_13');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 9, 'Auto rickshaw_18');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 10, 'Auto rickshaw_23');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 11, 'Auto rickshaw_30');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 12, 'Auto rickshaw_33');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 13, 'Auto rickshaw_36');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Auto rickshaw', 14, 'Auto rickshaw_39');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 1, 'Tractor_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 2, 'Tractor_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 3, 'Tractor_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 4, 'Tractor_8');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 5, 'Tractor_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 6, 'Tractor_10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 7, 'Tractor_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 8, 'Tractor_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 9, 'Tractor_17');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 10, 'Tractor_22');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 11, 'Tractor_30');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 12, 'Tractor_33');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 13, 'Tractor_36');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Tractor', 14, 'Tractor_39');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 1, 'Boat_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 2, 'Boat_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 3, 'Boat_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 4, 'Boat_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 5, 'Boat_10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 6, 'Boat_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 7, 'Boat_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 8, 'Boat_13');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 9, 'Boat_14');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 10, 'Boat_19');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 11, 'Boat_27');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 12, 'Boat_30');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 13, 'Boat_33');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Boat', 14, 'Boat_36');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 1, 'Airplane_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 2, 'Airplane_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 3, 'Airplane_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 4, 'Airplane_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 5, 'Airplane_10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 6, 'Airplane_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 7, 'Airplane_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 8, 'Airplane_13');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 9, 'Airplane_14');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 10, 'Airplane_19');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 11, 'Airplane_24');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 12, 'Airplane_32');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 13, 'Airplane_35');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 14, 'Airplane_38');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Airplane', 15, 'Airplane_41');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 1, 'Train_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 2, 'Train_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 3, 'Train_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 4, 'Train_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 5, 'Train_10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 6, 'Train_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 7, 'Train_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 8, 'Train_17');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 9, 'Train_22');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 10, 'Train_29');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 11, 'Train_32');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 12, 'Train_35');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Train', 13, 'Train_38');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 1, 'Trucks_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 2, 'Trucks_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 3, 'Trucks_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 4, 'Trucks_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 5, 'Trucks_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 6, 'Trucks_13');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 7, 'Trucks_14');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 8, 'Trucks_15');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 9, 'Trucks_16');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 10, 'Trucks_17');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 11, 'Trucks_22');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 12, 'Trucks_27');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 13, 'Trucks_32');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 14, 'Trucks_35');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 15, 'Trucks_38');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Trucks', 16, 'Trucks_41');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 1, 'Bicycle_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 2, 'Bicycle_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 3, 'Bicycle_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 4, 'Bicycle_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 5, 'Bicycle_10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 6, 'Bicycle_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 7, 'Bicycle_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 8, 'Bicycle_17');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 9, 'Bicycle_22');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 10, 'Bicycle_30');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 11, 'Bicycle_33');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 12, 'Bicycle_36');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bicycle', 13, 'Bicycle_39');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 1, 'Car_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 2, 'Car_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 3, 'Car_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 4, 'Car_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 5, 'Car_10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 6, 'Car_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 7, 'Car_13');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 8, 'Car_18');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 9, 'Car_23');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 10, 'Car_29');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 11, 'Car_32');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 12, 'Car_35');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Car', 13, 'Car_38');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 1, 'Bus_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 2, 'Bus_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 3, 'Bus_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 4, 'Bus_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 5, 'Bus_10');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 6, 'Bus_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 7, 'Bus_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 8, 'Bus_13');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 9, 'Bus_18');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 10, 'Bus_25');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 11, 'Bus_31');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 12, 'Bus_34');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 13, 'Bus_37');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Bus', 14, 'Bus_40');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 0, 'Auto rickshaw');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 1, 'Tractor');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 2, 'Boat');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 3, 'Airplane');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 4, 'Train');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 5, 'Trucks');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 6, 'Bicycle');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 7, 'Car');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Vehicles', 8, 'Bus');
