INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra', 2, 'Pundamilia', 'assets/topic/zebra.svg', 'pamoja na alama zao za milia myeupe na myeusi, ni nani hatoweza kumtambua Pundamilia! Pundamilia ni mnyama mwenye kwato moja ambao asili yao ni Afrika. Pundamilia ni jamii ya familia ya farasi na wana husiana sana na farasi na Punda. Kwasasa Pundamilia Ni miongoni mwa wanyama walio hatarini kutoweka, kwa orodha ya 2500 - 2700 duniani.', 'FF9DEDE3');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_3', 1, 'Ninaweza kumchora Pundamilia', 'assets/topic/zebraStripless_3.svg', 'Chora Milia kwa kutumia rangi nyeusi kwenye mnyama kubuni Pundamilia', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_3', 2, 1, 'assets/topic/zebraStripless_3.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_5', 1, 'Kubuni Pundamilia', 'assets/topic/zebrahandprint_6.svg', 'Buni Pundamilia kufuatisha Mchoro', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_5', 2, 1, 'assets/topic/zebrahandprint_6.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_7', 1, 'Sehemu yangu ya kubuni ya kuhifadhia Pundamilia', 'assets/topic/zebra_8.svg', 'kwa kutumia Picha, Buni hifadhi ya Pundamilia', 'zebra');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_7', 2, 1, 'assets/topic/zebra_8.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_9', 1, 'Alama za Pundamilia barabarani', 'assets/topic/zebracrossing_10.svg', 'Chora alama za Pundamilia kusaidia watu kuvuka barabara', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_9', 2, 1, 'assets/topic/zebracrossing_10.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_11', 3, 'Kuangalia kati ya uzao wa Familia yao', 'assets/topic/zebra_5.jpg', 'Pundamilia ni asili ya Bara la Afrika. Mara nyingine tunafikiri Pundamilia ni Farasi wenye MIlia. Hapana, hauko sahihi. Pundamilia ni jamii ya familia ya Farasi lakini ni wa kipekee sana. Lakini wana uhusiano wa karibu na Farasi, pamoja na Punda. Kuna aina tatu tofauti za Pundamilia. Pundamilia wa tambarare, pundamilia wa milimani na pundamilia wa nusu kame. Pundamilia wa tambarare wanapatikana kwenye ardhi yenye nyasi isiyokuwa na miti na katika misitu ya mashariki na kusini mwa Africa. Pundamilia wa milimani asili yao ni katika ukanda wa milimani wa kusini magharibi mwa Africa. Pundamilia wa nusu kame wanapatikana katika maeneo machache ya Kenya na Ethiopia. Pundamilia wa nusu kame wana uzito wa kati ya kilo 350 - 450. Pundamilia wa milimani wana uzito wa kati ya 240 hadi 372 na pundamilia wa tambarare wana uzito wa kilo 350. Wow huo ni uzito haswa.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_12', 0, 'Je Pundamilia ni jamii ya Farasi?', 'assets/topic/zebra_5.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_12', 1, 1, 'Ndio');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_12', 0, 1, 'Hapana');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_15', 3, 'Tabia ya kipekee ya rafiki Milia', 'assets/topic/zebraArticle_9.jpg', 'Pundamilia wanaishi kwenye makundi ya kifamilia wakiongozwa na Pundamilia wa kiume mwenye pundamilia wa kike wengi na watoto. Pundamilia wa kiume anajulikana kama fahali.Pundamilia wa kike anajulikana kama Pundamilia jike. Pundamilia mtoto anajulikana kama Kihongwe.  Mara nyingi Pundamilia hula Nyasi na wanaweza kusafiri hadi umbali wa maili 1800 kutafuta chakula. Kuwa wanyama wala Mimea, wakati mwingine hula Magome ya miti, matawi na pia Majani. Pundamilia Jike hubeba mimba kwa muda wa miezi 12 hadi 14. Pundamilia watoto huwa na uzito wa kilo 25 had 40 wanapozaliwa. Punde baada ya kuzaliwa, Pundamilia watoto wana uwezo wa kutembea na kukimbia. Pundamilia hujitegemea wanapofikisha umri wa miaka 3 hadi 6. Uhai wa Pundamilia ni kati ya miaka 30 hadi 40. Je! tabia hizi sio za kipekee?.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_16', 0, 'Chagua neno sahihi', 'assets/topic/zebra_5.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_16', 1, 1, 'Mla mimea');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_16', 0, 1, 'Mla Memia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_16', 0, 2, 'Memia Mla');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_20', 3, 'Muungano wa kijamii wa Pundamilia', 'assets/topic/zebra_5.jpg', 'Mara nyingi Pundamilia hupatikana kwenye makundi mengine ya wanyama, hususani wanyama pori kwa ajili ya usalama wa idadi yao. Mara nyingi Kundi kubwa la wanyama huwachanganya wanyama wala Nyama. Pundamilia wana njia kadhaa za kuwasiliana na wengine. Ishara ya uso kama kufungua macho kwa mapana au kukenua meno, vyote vikiashiria vitu. Pia wanabweka, wanatoa milio na kukoroma ili kueleweka. Hata uwekaji wa masikio yao hutoa ishara za hisia zao. Wanaweza kuzungusha masikio yao kuelekea mwelekeo wowote. Pundamilia hulala wakiwa wamesimama na inapendeza sana. Unafikiri unaweza kulala ukiwa umesimama? na, hulala endapo wapo salama kwenye makundi yao. Je!, Muungano wa jamii yao haushangazi?.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_21', 3, 'Ukweli Muhimu ambao Pundamilia hubeba', 'assets/topic/zebra_5.jpg', 'Jina la Kingereza la Pundamilia ni Zebra.  Hii inapendeza sana! hakuna Pundamilia wawili wenye Milia miwili inayofanana. Wapo kama alama za vidole vyetu. Wow!. Lazima kutakua na tofauti kubwa ya chati zao! Alama za Pundamilia zimetokana na milia myeusi na myeupe ya Pundamilia. Alama za Pundamilia pia zinajulikana kama Kivuko cha watembea kwa miguu. Sasa huo sio uhamasishaji?. Pundamilia wenye kasi zaidi. Ukweli ni kwamba wana uwezo wa kukimbia hadi maili 65 kwa saa. Sasa hii ni kasi kweli!. Pundamilia huonekana wazuri na rafiki, lakini wanaweza kuwa wanyama wenye fujo pia! Ung''ataji wao wa kutoboa na mateke yenye nguvu vinatosha kusababisha uharibu mkubwa na mara nyingine hata kuua.! hiyo ni Tahadhari!. Kuwa mbali na wanyama wenye milia.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_22', 0, 'Chagua neno sahihi', 'assets/topic/zebraAfrica_39.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_22', 1, 1, 'Afrika');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_22', 0, 1, 'Rikafa');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_22', 0, 2, 'Karifa');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_26', 0, 'Chagua neno sahihi', 'assets/topic/zebra_5.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_26', 1, 1, 'Pundamilia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_26', 0, 1, 'Miliapunda');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_26', 0, 2, 'ndapumilia');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_30', 0, 'Pundamilia ni mnyama mzuri sana, lakini anaweza kuwa____.', 'assets/topic/zebraArticle_9.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_30', 1, 1, 'na fujo sana');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_30', 0, 1, 'Rafiki sana');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_30', 0, 2, 'Mkali sana');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_34', 0, 'Hakuna miwili ____________ inayofanana.', 'assets/topic/zebraArticle_9.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_34', 1, 1, 'Milia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_34', 0, 1, 'Mikia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_34', 0, 2, 'Chati');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_38', 0, 'Pundamilia ni Mnyama mla Mimea?', 'assets/topic/zebra_5.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_38', 1, 1, 'Ndio');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_38', 0, 1, 'hapana');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Zebra_41', 0, 'Oaisha sehemu kukamilisha Picha', 'assets/topic/zebra_5.jpg', NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_41', 1, 1, 'assets/topic/zebraEars_35.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_41', 1, 2, 'Sikio');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_41', 1, 3, 'assets/topic/zebraLegs_36.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_41', 1, 4, 'Mguu');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_41', 1, 5, 'assets/topic/zebraTail_37.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Zebra_41', 1, 6, 'Mkia');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird', 2, 'Cherero machungwa', 'assets/topic/lovebird.svg', 'Ndege huyu mzuri kimuonekano ana jina zuri kama muonekano wake, anaitwa Cherero Machungwa. Ana muonekano kama wa Kasuku mdogo. Ndege huyu wa kushangaza, awali aligunduliwa na mchunguzi mjerumani Gustav Fischer katika karne ya 19, ndio maana hufahamika kwa jina la kiingereza Fischer''s Lovebird, yaani "Cherero Machungwa"', 'FFF4E1B5');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_3', 1, 'Cherero machungwa wangu mdogo mzuri', 'assets/topic/lovebirdtemp_4.svg', 'Chagua picha na ubuni ya Cherero Machungwa', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_3', 2, 1, 'assets/topic/lovebirdtemp_4.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_5', 1, 'Ninaweza kutengeneza Cherero machungwa wa peke yangu', 'assets/topic/lovebirdtemp_6.svg', 'Tumia vifaa vya uchoraji kuchora, kupaka rangi na kubuni yako ya Cherero Machungwa', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_5', 2, 1, 'assets/topic/lovebirdtemp_6.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_7', 1, 'Ndege wangu mtakatifu', 'assets/topic/lovebirdtemp_8.svg', 'Kwa kutumia picha na vifaa vya kuchorea, buni nyumba ya ndege kwaajili ya Cherero Machungwa wako.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_7', 2, 1, 'assets/topic/lovebirdtemp_8.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_9', 1, 'isiyo rangi hadi yenye rangi', 'assets/topic/lovebirdtemp_10.svg', 'Mpake rangi Cherero Machungwa kwa kutumia rangi tofauti upendeleazo.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_9', 2, 1, 'assets/topic/lovebirdtemp_10.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_11', 3, 'Uelewa Mdogo kuhusu ndege mdogo', 'assets/topic/lovebirdArticle_6.jpg', 'Asili ya Cherero Machungwa ni Afrika ya kati. Cherero Machungwa hukaa katika sehemu yenye makundi ya miti iliyojitenga pamoja na nyasi katikati yake. Kiujumla hukaa katika urefu wa mita 1100 hadi 200 juu ya uso wa bahari, na mara nyingi karibu na maji. Ndege hawa wadogo huweka makazi yao katika matobo ya miti, miamba na vichaka vilivyopo porini. Mara kwa mara hukaa kimakundi katika viota vyao au hujichukua wawili wawili kwenda kutengeneza makazi yao wenyewe. Cherero Machungwa huweza kuishi miaka 15 hadi 25.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_12', 0, 'Asili ya Cherero machungwa ni wapi?', 'assets/topic/zebraAfrica_39.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_12', 1, 1, 'Afrika ya kati');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_12', 0, 1, 'Marekani');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_12', 0, 2, 'India');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_16', 3, 'Muonekano wake wa kuvutia', 'assets/topic/fischerslovebird_7.jpg', 'Cherero Machungwa wana maumbo madogo kulinganisha na Kasuku. Kwa urefu wa inchi 5.5 na uzito wa gramu 43 hadi gramu 58 wanakaribia kuonekana kama mwanasesere wa Kasuku. Mbali na udogo wa maumbo yao, ni wajasiri, wadadisi na hupaa kila wakati. Cherero Machungwa pia hujulikana kwa macho yao ya duara. Wana utepe mweupe wa duara kuzunguka macho yao. Cherero Machungwa wana rangi Mchanganyiko. Rangi ya Machungwa. Nyekundu, Njano, Kijani , Buluu, Kijivi, nyeupe na waridi nzuri na za ajabu zilizoenea kote katika miili yao midogo.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_17', 0, 'Tambua Sehemu za mwili na oanisha pamoja na majina yake', 'assets/topic/fischerslovebird_7.jpg', NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_17', 1, 1, 'Mkia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_17', 1, 2, 'assets/topic/birdtail_31.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_17', 1, 3, 'Mwili');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_17', 1, 4, 'assets/topic/birdbody_33.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_17', 1, 5, 'Mdomo');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_17', 1, 6, 'assets/topic/birdbeak_35.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_17', 1, 7, 'Nyoya');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_17', 1, 8, 'assets/topic/birdfeather_37.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_17', 1, 9, 'Mguu');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_17', 1, 10, 'assets/topic/birdfeet_39.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_28', 3, 'Kupata kujua Tabia', 'assets/topic/lovebirdArticle_6.jpg', 'Cherero Machungwa huonyesha ushikiriano wa kijamii zaidi. Mara kwa mara huonekana wakiwa wawili wawili. Kama Cherero Machungwa wakitengana kutoka kwenye makundi yao huuzunika. Cherero Machungwa hupaa kwa kasi. Wana kasi sana kiasi kwamba mabawa yao husikika wakati wakipaa. Viumbe hivi vina rundo la sauti mbalimbali. Huendelea kuimba na kupiga filimbi siku nzima. Sauti zao husikika vizuri zaidi nyakati za asubuhi na jioni. Sauti zao nyembamba huvutia kusikika. Ni ndege wa kimakundi na hupendelea kuzungumza kwa pamoja. je! hiyo sio tabia ya kuvutia?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_29', 0, 'Mtoto__________', 'assets/topic/lovebirdchick_34.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_29', 1, 1, 'Vifaranga');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_29', 0, 1, 'Ndama');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_32', 3, 'kuhusu vifaranga', 'assets/topic/lovebirdEgg_10.jpg', 'Cherero Machungwa hulalia mayai kwa msimu kutoka Januari hadi Julai. Mayai hulaliwa katika Matobo ya miti. Maya huwa na rangi nyeupe na kawaida huwa 4 mpaka 8. Cherero Machungwa wa kike hutamia mayai kwa muda wa siku 21 had 23 mpaka yatakapo anguliwa yote. Watoto wadogo hutunzwa kwenye viota kwa siku 38 had 42 baada ya kuanguliwa. Watoto wa Cherero Machungwa huitwa Vifaranga. Cherero machungwa wa kike hulisha vifaranga wakati wakiwa ndani ya kiota. Cherero Machungwa wa kiume hufundisha vifaranga kula vyakula vya kawaida. Hiyo hufanya familia yenye furaha.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_33', 0, 'Cherero machungwa hutengeneza nyumba zao ndani ya maji', 'assets/topic/lovebirdArticle_6.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_33', 1, 1, 'Si kweli');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_33', 0, 1, 'Kweli');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_36', 3, 'Ukweli Muhimu usioweza kuepukika', 'assets/topic/lovebirdArticle_6.jpg', 'Cherero Machungwa huhifadhiwa kama mifugo dunia kote.. Natumaini umeshuhudia!. Ndege hawa hulishana mara kwa mara. Ndege mmoja husafirisha chakula kwenda kwa ndege mwingine. Sasa tumefahamu ni kwa jinsi gani ndege hawa huwakilisha jina lao. Kiujumla kuna aina 9 tofauti za Cherero Machungwa. Kasuku anayening''inia ambaye hupatikana Asia ni jamii yao ya karibu. Cherero Machungwa wana mpangilio mzuri wa chakula. wanakula Mbegu, beri, matunda na mara moja moja hula wadudu wadogo wa porini. Mara nyingine hufurahia kula mtama na mahindi. Hivyo hubeba jina la "ndege wala mazao". Cherero Machungo, kiasili wana fujo. Huwa na wivu kiasi au hughafilika pindi ndege wengine waingiapo kwenye kundi lao. Hivyo, kuwa mwangalifu, marafiki wadogo huwa na hasira pia.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_37', 0, 'Cherero Machungwa aligunduliwa na __________Mchunguzi, Gustav Fuscher.', 'assets/topic/fischerslovebird_7.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_37', 1, 1, 'Mjerumani');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_37', 0, 1, 'Mchina');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_37', 0, 2, 'Muafrika');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_41', 0, 'Gustav_________', 'assets/topic/fischerslovebird_7.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_41', 1, 1, 'Fischer');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_41', 0, 1, 'Marvel');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Fischer''s lovebird_44', 0, 'Ring___________', 'assets/topic/lovebirdEye_40.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_44', 1, 1, 'Macho');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Fischer''s lovebird_44', 0, 1, 'Mkia');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant', 2, 'Siafu safari wa kiafrika', 'assets/topic/ant.svg', 'Msiende kwa kiwango. Kiwango hakihusiani kwa hawa Siafu Safari. Wanajulikana zaidi kama Siafu dereva na wanapatikana Afrika. Japokua haijazoeleka, Siafu Safari huua Binadamu. Ndio!, Unasoma sasa. Siafu mdogo anaweza kuutoa uhai wa binadamu, Hii inaogopesha sana.', 'FFB3C8FF');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_3', 1, 'Mpake rangi Siafu Safari', 'assets/topic/anttemp_4.svg', 'Mpake rangi Siafu Safari kwa kutumia rangi za chaguo lako.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_3', 2, 1, 'assets/topic/anttemp_4.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_5', 1, 'Ninaweza kumchora Siafu Safari', 'assets/topic/anttemp_6.svg', 'Tumia vifaa vya kuchorea kuchora picha ya Siafu Safari', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_5', 2, 1, 'assets/topic/anttemp_6.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_7', 1, 'Msafara wa Siafu Safari', 'assets/topic/anttemp_8.svg', 'Tumia picha kubuni msafara wa Siafu Safari', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_7', 2, 1, 'assets/topic/anttemp_8.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_11', 3, 'Tujue kuhusu Mdudu hatari', 'assets/topic/Safari_ant_8.jpg', 'Siafu Safari pia wanajulikana kama Siafu Dereva na Saifu. Hawa wanapatikana Afrika ya kati na Mashariki. Pia wanapatika Asia. Kwa kingereza wanaitwa Ant. Hawa wadudu wanaishi kwa kuhamahama. Wanajongea kutoka sehemu moja kwenda sehemu nyingine. Koloni hili katili la Siafu safari hubadilisha sehemu wanazoishi kila siku. Utafutaji wao wa mawindo unahusisha kupanda kwenye miti na vichaka. Wachapakazi waliotulia, au sio?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_12', 0, 'Siafu safari wa kiafrika pia anajulikana kama__________', 'assets/topic/safariAnt_3.png', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_12', 1, 1, 'Siafu dereva');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_12', 0, 1, 'Siafu joka');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_12', 0, 2, 'Siafu Kiongozi');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_16', 0, 'Tabia _______', 'assets/topic/safariAnt_3.png', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_16', 1, 1, 'Kuhamahama');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_16', 0, 1, 'Uvivu');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_16', 0, 2, 'Fujo');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_20', 3, 'Mzunguko wa maisha ya Siafu hodari', 'assets/topic/safariAnt_9.jpg', 'Siafu Safari wanajulikana kama canivora. Hawa siafu wanajulikana kuwa wawindaji hodari. Wanatumia Idadi yao kuua Windo lao. Mgawanyo wa chakula unapokua mdogo, wanaondoka kwenye kichuguu na kuunda msafara unaoongozana wa Siafu 50,000,000. Hili ni tatizo haswa kwa watu. hususani kwa msafara kama huu kwenda majumbani, ni tatizo kubwa sana. Ni hatari kwa mtu asiyeweza kutoka kwenye njia yao. kwa kutumia taya zao kali zinazokata, hawa Siafu hushambulia kila kinachokatiza mbele yao. Inaweza kuwa Nyoka, Ndege, Mamalia na hata Binadamu. Ni wakali sana.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_21', 0, 'Msafara wa Siafu Safari unaweza kusafiri ______', 'assets/topic/safariAnt_9.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_21', 1, 1, 'Siafu 20');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_21', 0, 1, 'Siafu 100');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_21', 0, 2, 'Siafu 10');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_25', 0, 'Kukata__________', 'assets/topic/safariAntJaw_26.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_25', 1, 1, 'Taya');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_25', 0, 1, 'Macho');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_25', 0, 2, 'Antena');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_29', 3, 'Ukweli muhimu wa kujua', 'assets/topic/Safari_ant_8.jpg', 'Siafu Safari anaweza akasafiri umbali wa mita 20 ndani ya lisaa. Sio Mbaya… Siafu safari wanachukuliwa kuwa wadudu wauaji zaidi duniani. Wanaweza kumla binadamu na kumla binadamu akabaki mifupa kwa muda wa masaa 4. Kuwa na tabia ya kuhamahama, hawa wadudu huhamia sehemu mpya kila siku. Hawa wadudu wadogo wana taya imara sana. Mmoja anaweza akaivuta mara mbili bila kupoteza kushikilia kwake. Siafu safari wa kiume hujulikana kama Nzi Soseji. Huitwa jina hilo kwasababu ana tumbo lililovimbiana.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_30', 0, 'Nzi ____________', 'assets/topic/safariAnt_9.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_30', 1, 1, 'Soseji');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_30', 0, 1, 'Nyumba');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_30', 0, 2, 'Muuaji');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_34', 0, 'Siafu Safari wa kiume anaitwaje?', 'assets/topic/Safari_ant_8.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_34', 1, 1, 'Nzi Soseji');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_34', 0, 1, 'Nzi tumbo');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_34', 0, 2, 'Nzi Mnyonyaji');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('African Safari Ant_38', 0, 'Siafu safari anaweza kumla binadamu akabaki mifupa kwa lisaa limoja', 'assets/topic/safariAnt_3.png', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_38', 1, 1, 'Si kweli');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('African Safari Ant_38', 0, 1, 'Kweli');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile', 2, 'Mamba', 'assets/topic/crocodile.svg', 'Ni nani asiyemtambua hayu mnyama wa majini? Mamba……….hawaogopeshi!?. Mamba ni wanyama watambaao, na ni mojawapo wa wanyama wala nyama wanaoogopesha zaidi duniani. Kuna zaidi ya aina 23 tofauti za Mamba duniani. Wanyama hawa wa kuogopesha ni mojawapo ya viumbe vya kale duniani. Wameakuwepo duniani tangu miaka milioni 240 iliyopita. Ni wanyama wa kale haswa!', 'FFB3C8FF');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_3', 1, 'Mtambaaji anaeogopesha zaid', 'assets/topic/crocodiletemp_4.svg', 'Chora vipimo katika picha uliyopewa ya Mamba. Mfanye mamba mwenye kuogopesha.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_3', 2, 1, 'assets/topic/crocodiletemp_4.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_5', 1, 'Angalia nilichokichora', 'assets/topic/croctemp_6.svg', 'Tumia vifaa vya kuchorea kuchora,kupaka rangi na kubuni picha ya mamba', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_5', 2, 1, 'assets/topic/croctemp_6.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_7', 1, 'Tahadhari - maogeo ya mamba', 'assets/topic/croctemp_8.svg', 'Tumia picha na vifaa vya kuchorea,buni kundi la mamba wakiwa majini pamoja na ubao wenye tahadhari', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_7', 2, 1, 'assets/topic/croctemp_8.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_9', 1, 'Mamba maarufu mwenye rangi', 'assets/topic/croctemp_10.svg', 'Paka rangi katika picha ya mamba ukitumia rangi upendazo. Ongezea na gauni, kofia au mapambo yoyote na umuweke aonekane mamba maarufu', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_9', 2, 1, 'assets/topic/croctemp_10.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_11', 3, 'Kupata kujua mnyama pori mla nyama', 'assets/topic/crocodile_7.jpg', 'Dubwana kubwa mwenye kuogopesha kwenye maji ni mnyama mla nyama. Kula kwake nyama, hufurahia kula ndege, samaki na hata mamalia. Wakati mwingine hushambulia binadamu pia. Mamba watoto pia ni windo rahisi kwa Mnyama huyu. Inaonekana kushangaza ila ni ukweli. Hawahurumii mamba wadogo pia. Ukiachilia mbali kuwekwa katika kundi la reptilia, mamba wana ufanano wa karibu zaidi na Dinosau. Inaaminika waliishi na dinosau na ndege. Hatuwaoni tena dinosau lakini Mamba bado wanaishi. Hii inastaajabisha kweli.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_12', 0, 'Mamba ni mnyama mwenye damu __________', 'assets/topic/crocodile_8.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_12', 1, 1, 'Baridi');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_12', 0, 1, 'Joto');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_12', 0, 2, 'Moto');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_16', 3, 'Vipengele vya kushangaza vya mkubwa', 'assets/topic/crocodile_8.jpg', 'Viumbe hivi jirani, vikubwa, vinatofautiana ukubwa na uzito. Mamba mkubwa kabisa anaweza kukua kati ya urefu wa futi 13 hadi 18 na uzito wa paundi 2200. Aliye mdogo na mfupi katika familia ya mamba anaweza kuwa na urefu wa futi 5 na uzito wake ni kati ya paundi 40 hadi 70. Sasa,kwa kuwa mlaji halisi wa nyama,dubwana huyu wa kwenye maji ana meno ishirini na nne yenye ukali. Ngozi zao za migongoni zina muundo wa mifupa ambayo huwa kama kizuia risasi. Ngozi zao za kwenye tumbo za kawaida. Hatimaye, ana kitu cha kawaida. Wana pua ndefu zinazotofautiana kimaumbo na kiuwiano. Matundu ya pua, macho na masikio funguzi ni sehemu za juu za kichwa. Mwili wa mamba unahuisha pamoja na miguu yao yenye utando kwa nje. Hizo ndo sehemu za kushangaza za mwili wa dubwana kubwa la majini.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_17', 0, '____________risasi', 'assets/topic/bullet_37.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_17', 1, 1, 'Kizuia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_17', 0, 1, 'Koti');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_17', 0, 2, 'Mashine');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_21', 0, '___________ makali', 'assets/topic/crocTeeth_32.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_21', 1, 1, 'Meno');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_21', 0, 1, 'Mkia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_21', 0, 2, 'Macho');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_25', 3, 'Mvuto wa tabia ya kula ya mamba', 'assets/topic/crocodile_9.jpg', 'Mamba ni mnyama mla nyama. Hii inamaainsha wanakula nyama tu. Kula ni jambo lenye kufurahisha haswa pale tunapokula chakula tukipendacho. Tunatafuna na kutafuna na kuendelea kutafuna. Sasa, komea hapo, mamba hula vyakula wavipendavyo pia. Lakini, kula kwa wanyama hawa wa majini ni kwa kumeza. Wanatumia meno yao yaliyo imara na makali kurarua windo katika vipande vikubwa baada ya kuwabana chini kwenye taya zao. Wanameza mawe punde tu wanapokula mawindo yao kwaajili ya umeng`enyaji. Mawe hayo yanasaidia kusaga chakula ndani ya matumbo yao. Hicho sicho kitu chenye kuvutia!? Sasa, kuwa mwangalifu!, usifanye kama wao.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_26', 0, 'Tambua sehemu za mwili kisha oanisha pamoja na majina yake', 'assets/topic/crocodile_7.jpg', NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_26', 1, 1, 'Miguu Utando');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_26', 1, 2, 'assets/topic/crocfeet_30.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_26', 1, 3, 'Meno');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_26', 1, 4, 'assets/topic/crocTeeth_32.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_26', 1, 5, 'Mkia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_26', 1, 6, 'assets/topic/crocTail_34.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_26', 1, 7, 'Macho');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_26', 1, 8, 'assets/topic/crocEye_36.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_26', 1, 9, 'Pua');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_26', 1, 10, 'assets/topic/crocSnout_38.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_37', 3, 'Kidogo zaidi kwenye ulimwengu wa mamba', 'assets/topic/crocodile_7.jpg', 'Mamba ni wanyama damu baridi. Wanabadili joto la miili yao kutokana na mazingira waliyopo. Hiyo ina maanisha ni kama vile kiyoyozi. Kama wakihitaji mwili wenye joto basi watajianika juani. Kama wakihitaji baridi kidogo, basi huhamia kwenye maji. Wanyama hawa wenye nguvu wana milango ya fahamu hodari. Uhodari wa Hisia zao unawafanya wawe wanyama wala nyama kamili. Tunaweza kuona usiku? ni kweli tunaweza, lakini tunahitaji mwanga kutuongoza. Si sawa kwa rafiki yetu mamba. Maono yao ya usiku yako vizuri sana. Vivyo hata uhisi wao wa harufu na kusikia. Pamoja na hivi vipengele vyenye nguvu, Mamba huishi kuanzia miaka 50 hadi 60 na mara pengine hadi miaka 80. Maisha marefu kwa mnyama mkubwa.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_38', 0, 'Mamba anaweza kuishi hadi miaka 1000', 'assets/topic/crocodile_30.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_38', 1, 1, 'Si kweli');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_38', 0, 1, 'Kweli');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_41', 0, 'Mamba ni wanyama wala nyama', 'assets/topic/crocodile_9.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_41', 1, 1, 'Ndio');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_41', 0, 1, 'Hapana');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_44', 3, 'Ukweli wenye kushangaza wa mamba', 'assets/topic/crocSnout_38.jpg', 'Machozi ya mamba - Umewahi kusikia hili mahali? Mamba hutoa machozi wanapokula. Hapana,sio kwaajili ya Windo lilokufa, lakini kwaajili wanameza hewa nyingi inayoenda kugusa tezi za machozi na hivyo machozi hutiririka. Mamba wana miongoni mwa uumaji wa nguvu sana katika dunia yote ya wanyama. Hivyo ni dubwana la kwenye maji. Ulijua kwamba mamba ni waogeleaji Hodari? Wanaweza kuogelea kwa kasi ya maili 25 kwa saa. Uwezo wake unatokana na mkia wenye nguvu. Wow ni mkia wenye nguvu hakika!. Mamba mara nyingi wanaonekana taya zao zikiwa wazi kwa upana. Nani anaweza akajua ni kwanini!? Ukweli wanafungua taya zao ili kujipoza wenyewe kwasababu hawana tezi za jasho. Mamba jike hulalia mayai 20 hadi 80 kisha huyatunza kwa miezi 3. Hii kweli inashangaza.!', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Crocodile_45', 0, '___________ ya Mamba', 'assets/topic/crocEye_36.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_45', 1, 1, 'Machozi');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_45', 0, 1, 'Keki');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Crocodile_45', 0, 2, 'Makosa');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion', 2, 'Simba', 'assets/topic/lion.svg', 'content(Swahili)', 'FFB3C8FF');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_3', 1, 'Mnyama mkuu', 'assets/topic/africa-1300562.svg', 'Mfalme wa msitu. Paka mkubwa. Mfalme wa wanyama. Simba anajulikana katika historia kwa ujasiri wake na ushupavu. Mnyama huyu mkuu anachukuliwa kuwa Paka mkubwa wa pili duniani. Huyu kweli ni kiumbe mwenye kuvutia!', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_3', 2, 1, 'assets/topic/africa-1300562.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_5', 1, 'Angalia nilichokichora', 'assets/topic/Lion_clipart.svg', 'Tumia vifaa vya uchoraji kuchora,kupaka rangi na kubuni picha ya simba', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_5', 2, 1, 'assets/topic/Lion_clipart.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_7', 1, 'Kiburi cha Simba', 'assets/topic/tree-576848.svg', 'Tumia picha na vifaa vya uchoraji kubuni kundi la simba', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_7', 2, 1, 'assets/topic/tree-576848.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_9', 1, 'Uchawi/maajabu hivi punde', 'assets/topic/lioness.svg', 'Ongezea ukuu wa simba ukitumia vifaa vya uchoraji kwenye uso wa simba jike na umtengeneze simba dume', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_9', 2, 1, 'assets/topic/lioness.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_11', 3, 'Historia ya Simba', 'assets/topic/pexels-photo-627667.jpeg', 'Mfalme mkuu wa msitu alivamia mara moja sehemu kubwa ya afrika na baadhi ya sehemu za asia na Ulaya. Leo wanapatikana Sahara Ndogo ya Afrika. Idadi ndogo sana ya Simba wa Asia wamesalimika India. Simba waliongezeka Afrika kati ya miaka milioni 1 na 800,000. Simba mara kwa mara wanapungua lakini hawawi hatarini.Tunatumaini mfalme wetu wa msitu atabaki na kuendelea kuongezeka kidadi.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_12', 0, 'Chagua chakula cha simba', NULL, NULL, 'many');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_12', 1, 1, 'assets/topic/deer-2264354__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_12', 1, 2, 'assets/topic/animals-1782431__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_12', 1, 3, 'assets/topic/rabit-2808713_960_720.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_12', 1, 4, 'assets/topic/zebra-1141302_960_720.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_12', 0, 1, 'assets/topic/still-life-562357_960_720.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_12', 0, 2, 'assets/topic/basket-605148__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_12', 0, 3, 'assets/topic/popcorn-1554145__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_12', 0, 4, 'assets/topic/cake-1227842__340.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_21', 3, 'Tuelewe hila ya mwili', 'assets/topic/pride-48373__340.png', 'Mfalme wa Ajabu ana misuli, Paka mwenye kifua kikubwa. Ana kichwa kifupi cha duara, shingo fupi na masikio ya duara. Kuna kifundo cha nywele mwishoni mwa mkia. Mfalme ni mkubwa kuliko malkia. Mfalme ana uzito kati ya kilo 150 na 250. Kwa upande wa urefu Simba dume ni mrefu kuliko simba jike. Malkia ana uzito kati ya kilo 120 hadi 182. Simba dume ana ukuu. Kiumbe kikuu kina misha mafupi. Wanaishi takribani miaka 15. Lakini simba waliohifadhiwa wataendelea kuishi miaka 30.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_22', 0, 'Simba ni _______________', 'assets/topic/africa-17344_960_720.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_22', 1, 1, 'Mfalme');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_22', 0, 1, 'assets/topic/lions-1660044_960_720.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_22', 0, 2, 'Shati');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_26', 0, 'Kunguruma _______________', 'assets/topic/lion-3012515__340.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_26', 1, 1, 'Simba');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_26', 0, 1, 'assets/topic/raven-2162966__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_26', 0, 2, 'assets/topic/ant-564617_960_720.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_30', 0, 'Kujali _____________', 'assets/topic/lion-608251__340.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_30', 1, 1, 'assets/topic/lion-762698__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_30', 0, 1, 'assets/topic/lion-s-paw-claw-hand.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_30', 0, 2, 'assets/topic/animals-2609490_960_720.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_34', 3, 'Simba na uwindaji wao', 'pexels-photo-627667', 'Simba dume hulinda maeneo yao. Eneo lao lote ni maili 100 za mraba za nyika au mapori ya wazi.Wanyama hawa huweka alama eneo kwa mikojo. Hunguruma kutishia wanyama wengine wanaojaribu kutembea kwenye maeneo yao. Hukimbiza hata wanyama wengine walio kwenye maeneo yao. Simba jike anafahamika kama malkia. Simba jike huwindia kundi la simba dume. Kundi la simba dume hufahamika kama Fahari. Simba jike hufanya kazi pamoja kuwinda Windo. Fahari hufurahia windo lao kwa usawa. Huwagawia na simba wadogo. Wadogo hao huitwa simba Shibli. Shibli hawasaidii kuwinda hadi wafikishe umri wa mwaka 1. Simba hujulikana kwa kufanya kazi pamoja. Wao ni paka pekee wanaobaki kwa Ufahari.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_35', 0, 'Simba jike huwinda ______________.', 'assets/topic/lion-693059__340.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_35', 1, 1, 'Windo');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_35', 0, 1, 'Michezo');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_35', 0, 2, 'Maji');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_39', 3, NULL, 'assets/topic/lions-1132745_960_720.jpg', 'Simba wanajulikana kama paka wakubwa. Paka hawa wakubwa wanatabia karibu zote zinazofanana na paka wa kufugwa majumbani. Simba ni wakwezi wazuri. Mara nyingi huonekana juu ya miti wakiangalia maeneo ya kuwinda. Simba hua macho kwa masaa 3 hadi 4 kwa siku. Hebu kufikiria!. Wanatumia siku yao nzima kwa kulala. Wow hiyo ni ajabu!, lakini ni kweli. Hulala milalo mingi isiyo ya kawaida. Wanalalia migongo yao huku mikono yao ikiwa hewani. Tabia hizi hazifanani na paka wa majumbani?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_40', 0, 'Tambua sehemu za mwili na uoanishe na majina yao', NULL, NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_40', 1, 1, 'Ufalme wa Simba');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_40', 1, 2, 'assets/topic/lion-1281302_960_720.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_40', 1, 3, 'Makucha');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_40', 1, 4, 'assets/topic/stock-photo--lion-s-paw-with-claws-450899818.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_40', 1, 5, 'Mkia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_40', 1, 6, 'assets/topic/lion-tail-857949__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_40', 1, 7, 'Mngurumo');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_40', 1, 8, 'assets/topic/lion-2635913__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_40', 1, 9, 'Simba mtoto');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_40', 1, 10, 'assets/topic/lion-2990717__340.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_51', 3, 'Ukweli uvutiao kumuhusu mfalme simba', 'assets/topic/Unknown.jpg', 'Kila simba ana mfumo wa ndevu wa kipekee katika kinywa chake. Fikiria idadi ya mifumo! Muungurumo wa simba unaweza kusikika hadi umbali wa maili 3.Hiyo si sauti kubwa!? Mlio wa kutisha! Simba mwenye uzito mkubwa katika rekodi ana uizto wa kilo 375. Huo ni uzito mwingi sana! Simba jike hula nyama kilo 5 kila siku. Simba dume hula nyama kila 7 kila siku. Sasa, hiyo huitwa mlo mzito. Simba jike ni mama mwenye kujali. Antunza hata watoto simba waliotelekezwa. Simba huua chochote kile kuanzia panya, mijusi hadi wanyama pori. Hii ni kweli usalimikaji. Baada ya kubeba mimba kwa siku 105, hatimaye simba jike hujifungua watoto simba 2-3.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Lion_52', 0, 'Simba huwinda kwa kiburi', 'assets/topic/lion-3221778__340.png', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_52', 1, 1, 'assets/topic/lion-565820_960_720.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Lion_52', 0, 1, 'Kweli');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis', 2, 'Afrikanis', 'assets/topic/dog.svg', 'Kwa asili inayotupeleka miaka 7000 iliyopita kwa makadirio, Afrikanis ni moja kati ya aina ya mbwa wa kale wa kiafrika. Afrikanis wanachukuliwa kuwa Mbwa wa Afrika.', 'FFCFB5DD');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_3', 1, 'Afrikanis wangu, Mbwa bora', 'assets/topic/dogtemp_4.svg', 'Kwa kutumia picha, jenga banda la mbwa wako. Andika jina kwenye ubao wa jina kuonesha banda. Mchunge Mnyama wako kwa mfupa. Ongeza mapambo kwa kutumia vifaa vya kuchorea.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_3', 2, 1, 'assets/topic/dogtemp_4.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_9', 1, 'Nipake rangi tafadhali', 'assets/topic/dogtemp_10.svg', 'Kwa kutumia rangi za chaguo lako, paka rangi picha ya Mbwa', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_9', 2, 1, 'assets/topic/dogtemp_10.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_11', 1, 'Afrikanis aliyerekebishwa', 'assets/topic/dogtemp_12.svg', 'kwa kutumia picha, buni picha ya muda wa furaha wa familia.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_11', 2, 1, 'assets/topic/dogtemp_12.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_20', 1, 'Muda wa kufurahi na familia', 'assets/topic/dogtemp_21.svg', 'Kutumia picha huunda picha ya familia ya furaha.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_20', 2, 1, 'assets/topic/dogtemp_21.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_26', 3, 'Muonekano unaopendwa wa Afrikanis', 'assets/topic/africanisdog_9.jpg', 'Mbwa mara nyingi huchukuliwa kuwa rafiki mzuri wa Binadamu. Hii ni kweli kabisa pale inapokuja kwa jamii ya Mbwa Afrikanis. Kuwa rafiki pamoja na asili Michezo, huyu mbwa ni mnyama ni sahihi kabisa kwa nyumbani. Asili yake ya michezo inamfanya awe rafiki mzuri kwa watoto. ukiachana na kuwa na michezo, ni mungalifu na hutoa rahadhari. Nani hapendi kuwa huru?. Ndio, Sawa kabisa na sisi. Afrikanis pia hupenda kuwa huru. lakini muda huo huo huishi kwa adabu na mmiliki wake. Hata na hivyo anakua na ngozi yenye harara na hasira anapozeeka. Pamoja na yote kila mtu hali yake hubadilika.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_27', 0, 'Asili ya aina ya Mbwa Afrikanis ni ______ Kusini.', 'assets/topic/zebraAfrica_39.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_27', 1, 1, 'Afrika');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_27', 0, 1, 'Marekani');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_27', 0, 2, 'Asia');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_31', 3, 'Miili yenye nguvu ya Afrikanis', 'assets/topic/africans_23.jpg', 'Afrikanis wana miili membamba. Hii inawasaidia zaidi wawe rahisi na asili wajongeapo. Wana Mmiili yenye misuli pia. Mbavu zao zinaonekana wanapokua a afya njema. Kutokuwa warefu, wana kimo cha wastani kati ya inchi 20 hadi inchi 24 kwa urefu na uzito wa kilo 25 hadi kilo 45. Ngozi zao zinatofautiana kwa rangi kama nyeusi, kaki mkoleo, Kaki-chokoleti, asali, nyeupe, maziwa na dhahabu. Rafiki Mlaini mzuri ana kichwa chenye shepu ya koni. Je!, huoni anafanya muonekano wa kifalme?.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_32', 0, 'Tambua sehemu za mwili na oanisha na majina yake', 'assets/topic/africans_24.jpg', NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_32', 1, 1, 'Mkia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_32', 1, 2, 'assets/topic/africanisdog_9.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_32', 1, 3, 'Sikio');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_32', 1, 4, 'assets/topic/africanisdog_3.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_32', 1, 5, 'Uso');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_32', 1, 6, 'assets/topic/africanisdog_3.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_32', 1, 7, 'Miguu');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_32', 1, 8, 'assets/topic/africans_46.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_32', 1, 9, 'Mwili');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_32', 1, 10, 'assets/topic/africans_23.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_43', 3, 'Tabia zinazopendwa za Afrikanis', 'assets/topic/africans_24.jpg', 'Afrikanis ni marafiki sana kwa watoto. Je!, hupendelei kumiliki mmojawapo?. Anafundishika kiurahisi kwa kuwa ana heshima sana kwa mmiliki wake. Ana Mipaka kiasi na Mazingira yake. Hapendelei mtu yeyote aingie kwenye mipaka yake. Haitoenda vyema, akiwa kwenye kundi, kuwa kwake na misuli iliyojengeka, kunamfanya awe na nguvu ya kutembea na kukimbia wa umbali mrefu. Ana Afya kiasi kwa maisha yake yote, lakini wakati mwingine huwa katika hatari ya kuambukizwa Kichaa cha Mbwa. Afrikanis wana asili ya uaminifu na ujasiri. Wanaaminika kuwa maisha yao wamiliki wao. Wow! ni uaminifu wa namna gani huo?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_44', 0, 'Afrikanis ni Mbwa _______.', 'assets/topic/africans_24.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_44', 1, 1, 'Mwenye akili');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_44', 0, 1, 'Mvivu');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_44', 0, 2, 'Mkorofi');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_48', 3, 'Kuna ulazima wa kujua ukweli juu ya Afrikanis', 'assets/topic/africanisdog_3.jpg', 'Afrikanis wanahisi na ndio maana wana miili laini. Uhai wao ni wastani wa miaka 10 hadi miaka 12. Maisha Mafupi sana!. Mbwa Bantu, Mbwa muwindaji hottentot, Mbwa zulu, Mbwa khoikhoi, haya ni majina mengine ya Mbwa Afrikanis. Afrikanis ni Mbwa mwenye akili na mwenye asili ya urafiki. Afrikanis ni aina ya Mbwa wenye umbo la kati. Afrikanis wanachukua kuwa Ni mbwa wazuri kwa uwindaji. Afrikanis wana nywele fupi na hawahitaji uangalizi wowote. Je!, si rahisi kumtunza mbwa Afrikanis?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_49', 0, 'Aina ya Afrikanis huishi kwa miaka mingapi?', 'assets/topic/africans_23.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_49', 1, 1, '10 hadi miaka 12');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_49', 0, 1, '15 hadi miaka 20');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_49', 0, 2, '5 hadi miaka 10');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_53', 0, 'Mbwa Afrikanis pia hujulikana kama Mbwa Bantu.', 'assets/topic/africanisdog_9.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_53', 1, 1, 'Kweli');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_53', 0, 1, 'Si kweli');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_56', 0, '____________laini', 'assets/topic/africans_23.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_56', 1, 1, 'Mwili');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_56', 0, 1, 'Pua');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_56', 0, 2, 'Nywele');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_60', 0, 'Uso __________', 'assets/topic/africanisdog_3.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_60', 1, 1, 'wa shape ya koni');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_60', 0, 1, 'wa maraba');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_60', 0, 2, 'mpana');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Africanis_64', 0, '_________ wa misuli', 'assets/topic/africans_46.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_64', 1, 1, 'Mwili');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_64', 0, 1, 'Mkia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Africanis_64', 0, 2, 'Macho');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant', 2, 'Tembo', 'assets/topic/elephant.svg', 'Umeshawahi kusimama pembeni mwa tembo? Ni wakubwa na wazuri wakiwa na mkonga mmoja mrefu, mapembe mawili na miguu minne yenye uzito. Wow! ni wanyama wenye kushangaza kweli. Tembo anachukuliwa kuwa mamalia mkubwa wa ardhini, duniani', 'FFCFB5DD');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_3', 1, 'Tembo mpya', 'assets/topic/Meuble_héraldique_Elephant.svg', 'Chagua picha na ubuni tembo wako.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_3', 2, 1, 'assets/topic/Meuble_héraldique_Elephant.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_14', 1, 'Kubaki kwa tembo wangu', 'assets/topic/pines-576574.svg', 'Buni kubaki kwa tembo wako kwa kupanda miti ya chaguo lako.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_14', 2, 1, 'assets/topic/pines-576574.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_21', 1, 'Tembo upinde wa mvua', 'assets/topic/elephant-2403410__340.png', 'Tumia rangi tofauti za chaguo lako kumpaka tembo rangi kwenye picha', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_21', 2, 1, 'assets/topic/elephant-311596.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_23', 1, 'uzuri uliopitiliza', 'assets/topic/elephant-42339.svg', 'Kwa kutumia vifaa vya kuchorea, ongezea urembo wa; mnyororo, taji, gauni, hereni, bangili, ghala ya viatu, n.k, katika picha uliyopewa ya tembo.', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_23', 2, 1, 'assets/topic/elephant-42339.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_25', 3, 'Tujue kumuhusu Tembo', 'assets/topic/elephant-family-amboseli-260nw-305729312.jpg', 'Kuwa mamalia mkubwa wa ardhini, duniani, tembo wanaendelea kuwa katika orodha ya juu. Uzito wa tembo ni hadi kilo 6000, na kiasi cha urefu wa hadi futi 14. Chukua dakika kumfikiria tembo… Huo ni ukubwa kweli!. Tembo wana mkonga wenye ustadi ambao hufanya kazi zote muhimu. Ana masikio mawili makubwa kweli na pembe mbili zilizojikunja. Mnyama huyu mkubwa na rafiki ana mkia mdogo ambao una urefu wa mita 1.3. Kipimo cha maisha ya tembo wa kiafrika ni miaka 60 hadi 70. Kipimo cha maisha ya tembo wa ki Asia ni miaka 48.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_26', 0, 'Tembo duniani ni _________ mnyama', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_26', 1, 1, 'Mkubwa');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_26', 0, 1, 'Mdogo');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_26', 0, 2, 'Mrefu');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_30', 3, 'Tufanye safari kwenye hisia zao', 'assets/topic/elephant-111695_960_720.jpg', 'Tembo hutumia mkonga wake kwa kunusa , kupumua, kugundua mitetemo, kupapasa watoto wao, kunyonya maji na kushika vitu. Hiyo sio yenye kushangaza!? Sambamba na mkonga wake, masikio yale pia hutumika kwenye madhumuni mengi. Tembo hutumia masikio yao kuwasiliana. Kupigiza masikio yao inaweza kuonyesha shari au furaha. Tembo mmoja huweza kusikia muito wa tembo mwingine kutoka umbali wa mita 4. Viumbe hawa wazuri wana hisia kubwa za kunusa. Tembo huungana na kila mmojawapo mara nyingi kwa hisia ya kugusa. Hutumia viungo vyao vyote vya mwili kuathiriana na kila mmoja. Lakini linapokuja swala la macho, huwa na maono ya wastani.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_31', 0, 'Tambua sehemu za mwili na uoanishe na majina yao', 'assets/topic/african-1551762__340.jpg', NULL, 'pair');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_31', 1, 1, 'Mkonga wa tembo');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_31', 1, 2, 'assets/topic/african-1551762__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_31', 1, 3, 'Masikio ya tembo');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_31', 1, 4, 'assets/topic/elephant-2668679__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_31', 1, 5, 'Pembe za tembo');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_31', 1, 6, 'assets/topic/elephant-3292752__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_31', 1, 7, 'Mkia wa tembo');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_31', 1, 8, 'assets/topic/elephant-3679295__340.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_31', 1, 9, 'Mtoto Tembo');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_31', 1, 10, 'assets/topic/baby-elephants-playing-260nw-75308080.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_42', 3, 'Jaribu kujua kuhusu makazi yao', 'assets/topic/female-314976__340.jpg', 'Tembo wa kike hujulikana kama ng`ombe. Tembo wa kiume hujulikana kama ndovu. Tembo jike huishi katika kundi la familia pamoja na watoto wao. Tembo dume hupendelea kuzurura peke yao. Tembo hubeba ujauzito kwa muda mrefu kuliko mnyama mwingine yeyote. Mimba yake hukaa karibia miezi 22. wakati wa kujifungua tembo mtoto huwa na uzito wa kilo 100 na husimama wima kwa futi 3. Kuna aina mbili za tembo. Tembo wa kiafrika na tembo wa kiasia. Tembo wa kiafrika ni wakubwa kiumbo kulinganisha na tembo wa kiasia.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_43', 0, 'Mtoto wa tembo huwa na uzito gani pindi azaliwapo?', 'assets/topic/baby_elephant.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_43', 1, 1, 'kilo 100');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_43', 0, 1, 'kilo 200');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_43', 0, 2, 'Kilo 500');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_47', 3, 'Elimu kidogo kuhusu pembe', 'assets/topic/nature-1284285_960_720.jpg', 'Pembe za tembo ni meno yake kubwa. Theluthi moja ya pembe imefichwa mwilini mwake. Imefunikwa ndani kabisa ya kichwa chake. Pembe za tembo haziachi kukua. Tembo hutumika hutumia pembe zao kuchimba, kurarua magome ya kwenye miti na kuondoa vitu mbali mbali vilivyopo katika njia yao. Muda mwingi huitumia kama silaha kuwatisha wanyama wala nyama. Pembe za tembo hujulikana kama ndovu, na zina gharama sana katika soko. Pembe za tembo ndio zimekuwa sababu kuu za kuwindwa kwa tembo, Hii si haki!. Kama mauaji ya tembo yataendelea, punde Tembo watatoweka.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_48', 0, 'Pembe la tembo hujulikana pia kama pembe za ndovu?', NULL, NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_48', 1, 1, 'assets/topic/africa-animal-photography-barbaric-631317.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_48', 0, 1, 'Si kweli');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_51', 3, 'ukweli wenye kuvutia kuhusu tembo', 'assets/topic/elephant-839098_960_720.jpg', 'Tembo mkongwe kujulikana aliishi kwa miaka 86. Wastani wa maisha ya tembo ni miaka 50 hadi 70. Je unafahamu kwamba tembo hawezi kuruka, kutembea kwa haraka wala kukimbia kwa kuruka? Anaweza kukimbia ua kutembea. Tembo huwa sawia na binadamu pindi linapokuja swala la hisia. Huonyesha huzuni, huruma, kujitambua,michezo,sanaa na muziki. Je huu sio ukweli wenye kushangaza!? Tembo hufuata aina ya maisha kwa mpangilio. Tembo jike huishi maisha yake yote katika kundi linaloundwa na wakina mama, shangazi,wadada,watoto wa kike na wakina bibi. Tembo dume hupendelea kuishi maisha ya ukapera. Je hii hukumbusha aina ya maisha ya kibinadamu?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_52', 0, 'Tembo zinaweza___________.', 'assets/topic/elephant-family-amboseli-260nw-305729312.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_52', 1, 1, 'miliki');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_52', 0, 1, 'trot');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_52', 0, 2, 'mshambuliaji');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_56', 0, '_________ Mrefu', 'assets/topic/elephant-3679295__340.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_56', 1, 1, 'Mkonga');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_56', 0, 1, 'Macho');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_56', 0, 2, 'Nywele');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_60', 0, '_________ Nyeupe', 'assets/topic/african-1551762__340.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_60', 1, 1, 'Pembe');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_60', 0, 1, 'Mkia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_60', 0, 2, 'Sikio');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Elephant_64', 0, '________ Kubwa', 'assets/topic/elephant-3679295__340.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_64', 1, 1, 'Mwili');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_64', 0, 1, 'Kucha');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Elephant_64', 0, 2, 'Macho');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat', 2, 'Mbuzi', 'assets/topic/Goat.svg', 'Nani asiyetambua miili migumu ya mamalia yenye Pembe na miguu yenye kwato? Ndio, uko sahihi!, Ni Mbuzi, mnyama rafiki wa kufugwa. Je! Unafahamu kwamba Mbuzi alikua ni Miongoni mwa wanyama wa kwanza kufugwa na Binadamu miaka 11000 iliyopita Kaskazini-mashariki. Japokua Maziwa ya Mbuzi ni miongoni mwa Kinywaji maarufu duniani, Pia Mbuzi amekua Mnyama msaidizi wa karibu wa Binadamu.', 'FFB3C8FF');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_3', 1, 'Kubuni Mbuzi', 'assets/topic/goattemp_4.svg', 'Tumia vifaa cha kuchorea, chora sehemu za mwili wa mbuzi zilizokosekana', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_3', 2, 1, 'assets/topic/goattemp_4.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_5', 1, 'Ninaweza kumchora Mbuzi', 'assets/topic/goattemp_8.svg', 'Tumia vifaa cha kuchorea, kuchora picha ya Mbuzi', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_5', 2, 1, 'assets/topic/goattemp_6.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_7', 1, 'Mbuzi wangu mwenye Afya', 'assets/topic/goattemp_8.svg', 'Ongeza chakula kwaajili ya mbuzi ukitumia vifaa vya kuchorea', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_7', 2, 1, 'assets/topic/goattemp_8.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_9', 1, 'Beberu watatu wanalia', 'assets/topic/goattemp_10.svg', 'Paka rangi karatasi za hadithi "Millio ya Beberu watatu"', NULL);
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_9', 2, 1, 'assets/topic/goattemp_10.svg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_11', 3, 'Asili ya Mbuzi', 'assets/topic/goat_8.jpg', 'Mbuzi na Binadamu wana Historia ndefu na ya faida pamoja. Ufugaji mkubwa wa Mbuzi ulienea Miaka ya 11,000 iliyopita Kaskazini-mashariki. Kuna aina mbili za Mbuzi, ambao ni Mbuzi wa Milimani na Mbuzi wa kufugwa. Mbuzi wa Milimani. Mbuzi wa Milimani wanapatikana katika milima ya Miamba, maeneo ya Alaska, Montana Magharibi, Idaho kati, Dakota Kusini, Kolorado na Washington. Mbuzi wakufugwa wanakuzwa duniani kote takribani katika kila Nyumba.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_12', 0, 'Kuna aina ______ za Mbuzi.', 'assets/topic/goat_15.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_12', 1, 1, 'Mbili');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_12', 0, 1, 'Tano');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_12', 0, 2, 'Tatu');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_16', 3, 'Tabia nzuri za Mla Nyasi', 'assets/topic/goat_7.jpg', 'Mbuzi ni viumbe vyenye ushirikiano sana na wanaishi katika makundi madogo. Mbuzi wa milimani wana ushirikiano kipindi cha masika na wana ubinafsi kipindi cha kiangazi. Mbuzi mara nyingi hutumia muda mwingi kula nyasi zao katika mipaka ya Nyumba zao. Mbuzi wa milimani huchimba mashimo ya inchi moja upana na urefu ili kuweza kulala, kupumzika na kuoga kwa mavumbi. Mbuzi ni kundi la Abivorasi yenye maana ni wanyama wanaokula Majani pekee yake. Mbuzi wa Milimani wanakula majani ya mabwawani na Mimea. Mbuzi wa kufugwa hula Mabaki ya vyakula vya nyumbani, mimea ya majumbani na chochote watakachiona ardhini kinachowafaa kula.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_17', 0, 'Chagua vitu tunachopata kutoka kwa mbuzi.', 'assets/topic/goat_7.jpg', NULL, 'many');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_17', 1, 1, 'assets/topic/goatmeat_27.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_17', 1, 2, 'assets/topic/goatwool_28.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_17', 1, 3, 'assets/topic/goatmilk_29.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_17', 0, 1, 'assets/topic/goat_eggs_30.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_17', 0, 2, 'assets/topic/Igoat_carrot_31.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_17', 0, 3, 'assets/topic/goat_beetroot_32.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_17', 0, 4, 'assets/topic/goat_potato_33.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_17', 0, 5, 'assets/topic/goat_onion_34.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_17', 0, 6, 'assets/topic/goat_cookies_35.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_27', 3, 'Tuijue familia ya Mbuzi', 'assets/topic/goatfamily_9.jpg', 'Mbuzi wa kiume huitwa Beberu. Mbuzi wa kike huitwa mbuzi jike. Mbuzi mtoto huitwa Kimbalelo. Mbuzi jike hubeba mimba kwa muda wa siku 150 had siku 180 kabla ya kujifungua. Watoto wa Mbuzi ni wachangamfu na wapo kasi. Mara tu baada ya kuzaliwa husimama na kutembea. Watoto wa Mbuzi huhesabika wamekua mara watimizapo miezi 30. Kuna aina 200 za Mbuzi wa kufugwa. Uzito wa Mbuzi wa kufugwa ni kati ya kilo 9 had kilo 113 kulingana na aina ya Mbuzi. Uzito wa Mbuzi wa milimani ni kati ya kilo 57 hadi kilo 82. Mbuzi wana muda mfupi wa kuishi. Mbuzi wa milimani huishi miaka 9 hadi miaka 12. Mbuzi wa kufugwa huishi kati ya miaka 10 hadi miaka 18. Je! familia ya Mbuzi si ya kawaida kama Mbuzi mwenyewe?', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_28', 0, 'Oanisha picha kwa majina yake', 'assets/topic/goat_7.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_28', 1, 1, 'Pembe');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_28', 1, 2, 'assets/topic/goathorns_44.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_28', 1, 3, 'Masikio');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_28', 1, 4, 'assets/topic/goathorns_44.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_28', 1, 5, 'Mtoto');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_28', 1, 6, 'assets/topic/goatkid_48.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_28', 1, 7, 'Matundu ya pua');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_28', 1, 8, 'assets/topic/goathorns_44.jpg');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_28', 1, 9, 'Mkia');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_28', 1, 10, 'assets/topic/goattail_52.jpg');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_39', 3, 'Ukweli wa kuvutia kushirikishana, kuhusu rafiki anayelia', 'assets/topic/goatbleeting_10.jpg', 'Mtoto wa Mbuzi anaitwa Kimbalelo. Lakini ukweli ni kwamba Mbuzi ajifunguapo huchukuliwa kama "utani". Mbuzi hana meno katika taya yake ya juu. Sasa hiki ni kichekesho. Sijui ingekuaje kama Binadamu angekua hana meno kwenye taya ya juu kama mbuzi. Mbuzi anaweza kupanda miti na kuruka urefu wa futi 5. Hodari sana!!. Mbuzi wana milio tofauti kutoka kanda moja hadi kanda nyingine. Hii ina maana milion ya mbuzi ya nchi moja inatofautiana na milio ya mbuzi wa nchi nyingine. Mfanano kiasi na sisi binadamu. Mbuzi hawapendi kulowa na kucheza kwenye mvua. Mbuzi wana matumbo manne yanayojulikana kama RUMEN. Hii huwasaidia kwenye mmeng''enyo kamilifu wa chakula. Sasa hii ndo siri ya malisho yao endelevu.', NULL);
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_40', 0, 'Mbuzi ana tumbo ____________.', 'assets/topic/goat_28.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_40', 1, 1, 'Nne');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_40', 0, 1, 'Moja');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_40', 0, 2, 'Sita');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_44', 0, 'Milio ya Mbuzi inatofautiana kutoka kanda moja mpaka nyingine', 'assets/topic/goatbleeting_10.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_44', 1, 1, 'kweli');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_44', 0, 1, 'Si kweli');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_47', 0, 'Mbuzi ______', 'assets/topic/goatbleeting_10.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_47', 1, 1, 'Milio');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_47', 0, 1, 'Vilio');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_50', 0, 'Milima ______', 'assets/topic/goat_46.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_50', 1, 1, 'Mbuzi');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_50', 0, 1, 'Panya');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Goat_53', 0, 'Nne______', 'assets/topic/goat_8.jpg', NULL, 'oneAtATime');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_53', 1, 1, 'Tumbo');
INSERT INTO `cardExtra` (cardId, type, serial, content) VALUES ('Goat_53', 0, 1, 'Mikia');
INSERT INTO `card` (id, type, title, header, content, option) VALUES ('Wanyama', 2, 'Wanyama', NULL, NULL, NULL);
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 1, 'Zebra_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 2, 'Zebra_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 3, 'Zebra_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 4, 'Zebra_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 5, 'Zebra_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 6, 'Zebra_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 7, 'Zebra_15');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 8, 'Zebra_16');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 9, 'Zebra_20');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 10, 'Zebra_21');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 11, 'Zebra_22');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 12, 'Zebra_26');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 13, 'Zebra_30');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 14, 'Zebra_34');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 15, 'Zebra_38');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Zebra', 16, 'Zebra_41');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 1, 'Fischer''s lovebird_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 2, 'Fischer''s lovebird_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 3, 'Fischer''s lovebird_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 4, 'Fischer''s lovebird_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 5, 'Fischer''s lovebird_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 6, 'Fischer''s lovebird_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 7, 'Fischer''s lovebird_16');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 8, 'Fischer''s lovebird_17');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 9, 'Fischer''s lovebird_28');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 10, 'Fischer''s lovebird_29');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 11, 'Fischer''s lovebird_32');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 12, 'Fischer''s lovebird_33');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 13, 'Fischer''s lovebird_36');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 14, 'Fischer''s lovebird_37');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 15, 'Fischer''s lovebird_41');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Fischer''s lovebird', 16, 'Fischer''s lovebird_44');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 1, 'African Safari Ant_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 2, 'African Safari Ant_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 3, 'African Safari Ant_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 4, 'African Safari Ant_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 5, 'African Safari Ant_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 6, 'African Safari Ant_16');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 7, 'African Safari Ant_20');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 8, 'African Safari Ant_21');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 9, 'African Safari Ant_25');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 10, 'African Safari Ant_29');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 11, 'African Safari Ant_30');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 12, 'African Safari Ant_34');
INSERT INTO `collection` (id, serial, cardId) VALUES ('African Safari Ant', 13, 'African Safari Ant_38');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 1, 'Crocodile_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 2, 'Crocodile_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 3, 'Crocodile_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 4, 'Crocodile_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 5, 'Crocodile_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 6, 'Crocodile_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 7, 'Crocodile_16');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 8, 'Crocodile_17');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 9, 'Crocodile_21');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 10, 'Crocodile_25');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 11, 'Crocodile_26');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 12, 'Crocodile_37');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 13, 'Crocodile_38');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 14, 'Crocodile_41');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 15, 'Crocodile_44');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Crocodile', 16, 'Crocodile_45');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 1, 'Lion_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 2, 'Lion_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 3, 'Lion_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 4, 'Lion_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 5, 'Lion_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 6, 'Lion_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 7, 'Lion_21');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 8, 'Lion_22');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 9, 'Lion_26');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 10, 'Lion_30');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 11, 'Lion_34');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 12, 'Lion_35');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 13, 'Lion_39');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 14, 'Lion_40');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 15, 'Lion_51');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Lion', 16, 'Lion_52');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 1, 'Africanis_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 2, 'Africanis_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 3, 'Africanis_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 4, 'Africanis_20');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 5, 'Africanis_26');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 6, 'Africanis_27');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 7, 'Africanis_31');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 8, 'Africanis_32');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 9, 'Africanis_43');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 10, 'Africanis_44');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 11, 'Africanis_48');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 12, 'Africanis_49');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 13, 'Africanis_53');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 14, 'Africanis_56');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 15, 'Africanis_60');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Africanis', 16, 'Africanis_64');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 1, 'Elephant_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 2, 'Elephant_14');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 3, 'Elephant_21');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 4, 'Elephant_23');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 5, 'Elephant_25');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 6, 'Elephant_26');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 7, 'Elephant_30');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 8, 'Elephant_31');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 9, 'Elephant_42');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 10, 'Elephant_43');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 11, 'Elephant_47');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 12, 'Elephant_48');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 13, 'Elephant_51');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 14, 'Elephant_52');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 15, 'Elephant_56');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 16, 'Elephant_60');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Elephant', 17, 'Elephant_64');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 1, 'Goat_3');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 2, 'Goat_5');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 3, 'Goat_7');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 4, 'Goat_9');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 5, 'Goat_11');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 6, 'Goat_12');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 7, 'Goat_16');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 8, 'Goat_17');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 9, 'Goat_27');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 10, 'Goat_28');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 11, 'Goat_39');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 12, 'Goat_40');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 13, 'Goat_44');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 14, 'Goat_47');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 15, 'Goat_50');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Goat', 16, 'Goat_53');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Wanyama', 0, 'Zebra');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Wanyama', 1, 'Fischer''s lovebird');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Wanyama', 2, 'African Safari Ant');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Wanyama', 3, 'Crocodile');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Wanyama', 4, 'Lion');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Wanyama', 5, 'Africanis');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Wanyama', 6, 'Elephant');
INSERT INTO `collection` (id, serial, cardId) VALUES ('Wanyama', 7, 'Goat');
